
DELETE FROM P2P_BKPF_STAGING
WHERE EXISTS (SELECT 1 FROM BKPF_DELTA as NEW_DATA 
                  WHERE P2P_BKPF_STAGING.MANDT=NEW_DATA.MANDT and P2P_BKPF_STAGING.BUKRS=NEW_DATA.BUKRS 
                  AND P2P_BKPF_STAGING.BELNR=NEW_DATA.BELNR and P2P_BKPF_STAGING.GJAHR=NEW_DATA.GJAHR);

INSERT INTO P2P_BKPF_STAGING 
SELECT DISTINCT
    BKPF.MANDT,
    BKPF.BUKRS,
    BKPF.BELNR,
    BKPF.GJAHR,
    CAST(BKPF.BLDAT AS DATE) AS TS_BLDAT, 
    CAST(BKPF.BUDAT AS DATE) AS TS_BUDAT, 
    CAST(BKPF.CPUDT AS DATE) AS TS_CPUDT,
    CAST(BKPF.CPUDT AS DATE) + CAST(BKPF.CPUTM AS TIME) AS TS_CPUDT_CPUTM,
    CAST(BKPF.AEDAT AS DATE) AS TS_AEDAT, 
    CAST(BKPF.UPDDT AS DATE) AS TS_UPDDT, 
    CAST(BKPF.WWERT AS DATE) AS TS_WWERT, 
    CAST(BKPF.STODT AS DATE) AS TS_STODT, 
    CAST(BKPF.REINDAT AS DATE) AS TS_REINDAT, 
    CAST(BKPF.VATDATE AS DATE) AS TS_VATDATE, 
    CAST(BKPF.INTDATE AS DATE) AS TS_INTDATE, 
    CAST(BKPF.PSOBT AS DATE) AS TS_PSOBT, 
    CAST(BKPF.PSODT AS DATE) AS TS_PSODT, 
    CAST(BKPF.PSODT AS DATE) + CAST(BKPF.PSOTM AS TIME) AS TS_PSODT_PSOTM,
    CAST(BKPF.OFFSET_REFER_DAT AS DATE) AS TS_OFFSET_REFER_DAT, 
    SUBSTRING(BKPF.AWKEY,1,14) AS RBKPKEY -- Join to MM (RBKP)
FROM    
	BKPF_DELTA AS BKPF
    JOIN RSEG ON
        RSEG.MANDT=BKPF.MANDT
        AND SUBSTRING(BKPF.AWKEY,1,14) = RSEG.BELNR || CAST(RSEG.GJAHR AS VARCHAR(4)) 
     JOIN EKPO  ON 1=1
        AND RSEG.MANDT = EKPO.MANDT
        AND RSEG.EBELN = EKPO.EBELN
        AND RSEG.EBELP = EKPO.EBELP
     JOIN EKKO  ON 1=1
    	AND EKKO.MANDT = EKPO.MANDT
    	AND EKKO.EBELN = EKPO.EBELN
        AND EKKO.BSTYP = '<%=purchaseDoc%>'
;

SELECT ANALYZE_STATISTICS ('P2P_BKPF_STAGING'); 
