DELETE FROM P2P_EKET_STAGING
WHERE EXISTS (SELECT 1 FROM <$EKET> as NEW_DATA 
              WHERE P2P_EKET_STAGING.MANDT=NEW_DATA.MANDT 
              AND P2P_EKET_STAGING.EBELN=NEW_DATA.EBELN
              AND P2P_EKET_STAGING.EBELP=NEW_DATA.EBELP
              AND P2P_EKET_STAGING.ETENR=NEW_DATA.ETENR
              );
INSERT INTO P2P_EKET_STAGING
SELECT 
    EKET.MANDT,
    EKET.EBELN,
    EKET.EBELP,
    EKET.ETENR,
    CAST(EKET.ALTDT AS DATE) AS TS_ALTDT, 
    CAST(EKET.DAT01 AS DATE) AS TS_DAT01, 
    CAST(EKET.EINDT AS DATE) AS TS_EINDT, 
    CAST(EKET.ELDAT AS DATE) AS TS_ELDAT, 
    CAST(EKET.LDDAT AS DATE) AS TS_LDDAT, 
    CAST(EKET.MBDAT AS DATE) AS TS_MBDAT, 
    CAST(EKET.SLFDT AS DATE) AS TS_SLFDT
FROM 
    <$EKET> AS EKET
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKPO_STAGING AS C
    WHERE 1=1 
        AND EKET.MANDT = C.MANDT
        AND EKET.EBELN = C.EBELN
        AND EKET.EBELP = C.EBELP)
;

SELECT ANALYZE_STATISTICS ('P2P_EKET_STAGING'); 


