
DELETE FROM P2P_EKES_STAGING
WHERE EXISTS (SELECT 1 FROM <$EKES> as NEW_DATA 
              WHERE P2P_EKES_STAGING.MANDT=NEW_DATA.MANDT 
              AND P2P_EKES_STAGING.EBELN=NEW_DATA.EBELN
              AND P2P_EKES_STAGING.EBELP=NEW_DATA.EBELP
              AND P2P_EKES_STAGING.ETENS=NEW_DATA.ETENS
              );

INSERT INTO P2P_EKES_STAGING
SELECT 
    EKES.MANDT,
    EKES.EBELN,
    EKES.EBELP,
    EKES.ETENS,
    CAST(EKES.EINDT AS DATE) AS TS_EINDT, 
    CAST(EKES.ERDAT AS DATE) AS TS_ERDAT
FROM 
    <$EKES> AS EKES
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKPO_STAGING AS C
    WHERE 1=1 
        AND EKES.MANDT = C.MANDT
        AND EKES.EBELN = C.EBELN
        AND EKES.EBELP = C.EBELP
    )
;

SELECT ANALYZE_STATISTICS ('P2P_EKES_STAGING'); 

