
DELETE FROM P2P_MSEG_STAGING
WHERE EXISTS (SELECT 1 FROM <$MSEG> as NEW_DATA 
              WHERE P2P_MSEG_STAGING.MANDT=NEW_DATA.MANDT 
              AND P2P_MSEG_STAGING.MBLNR=NEW_DATA.MBLNR
              AND P2P_MSEG_STAGING.MJAHR=NEW_DATA.MJAHR
              AND P2P_MSEG_STAGING.ZEILE=NEW_DATA.ZEILE
              );


INSERT INTO P2P_MSEG_STAGING 
SELECT
	MSEG.MANDT,
    MSEG.MBLNR,
    MSEG.MJAHR,
    MSEG.ZEILE,
    CAST(MSEG.VFDAT AS DATE) AS TS_VFDAT,
    CAST(MSEG.DABRBZ AS DATE) AS TS_DABRBZ,
    CAST(MSEG.DABRZ AS DATE) AS TS_DABRZ,
    CAST(MSEG.HSDAT AS DATE) AS TS_HSDAT,
    CAST(MSEG.BUDAT_MKPF AS DATE) AS TS_BUDAT_MKPF,
    CAST(MSEG.CPUDT_MKPF AS DATE) AS TS_CPUDT_MKPF
FROM 
	<$MSEG>  AS MSEG
WHERE EXISTS(
    SELECT * 
    FROM EKPO AS C
    WHERE 1=1 
        AND MSEG.MANDT = C.MANDT
        AND MSEG.EBELN = C.EBELN
        AND MSEG.EBELP = C.EBELP)
;


SELECT ANALYZE_STATISTICS ('P2P_MSEG_STAGING'); 

