-- Query 1
DROP TABLE IF EXISTS TMP_PR_CDHDR_CDPOS;

-- Query 2
CREATE TABLE TMP_PR_CDHDR_CDPOS AS (
	SELECT
	CDPOS.MANDANT
	,CDPOS.FNAME
	,CDPOS.TABNAME
	,CDPOS.TABKEY
	,CDPOS.VALUE_OLD
	,CDPOS.VALUE_NEW
	,CDHDR.UDATE  
  ,CDHDR.UTIME 
	,CDHDR.CHANGENR
  ,CDPOS.CHNGIND
	,CDHDR.TCODE
	,CDPOS.OBJECTCLAS
	,CDPOS.OBJECTID
	,CDHDR.USERNAME
	FROM CDHDR AS CDHDR
	    JOIN <$CDPOS> AS CDPOS ON
		    CDPOS.MANDANT = CDHDR.MANDANT AND
		    CDPOS.OBJECTCLAS = CDHDR.OBJECTCLAS AND
		    CDPOS.OBJECTID = CDHDR.OBJECTID AND
		    CDPOS.CHANGENR = CDHDR.CHANGENR
	WHERE 1=1
    AND CDPOS.CHNGIND IN ('U', 'I')
		AND CDPOS.TABNAME IN ('EBAN','EKKO','EKPO') );

    SELECT ANALYZE_STATISTICS ('TMP_PR_CDHDR_CDPOS'); 
