INSERT INTO _CEL_PR_CDHDR_ACTIVITIES_DELTA (
    _CASE_KEY
	,MANDT
	,BANFN
	,BNFPO
    ,ACTIVITY_DE
    ,ACTIVITY_EN
    ,EVENTTIME
    ,_SORTING
    ,USER_NAME
    ,USER_TYPE
    ,CHANGED_TABLE
    ,CHANGED_FIELD
    ,CHANGED_FROM
    ,CHANGED_TO
    ,CHANGE_NUMBER
    ,TRANSACTION_CODE
    ,_ACTIVITY_KEY)

SELECT
	 EBAN.MANDT || EBAN.BANFN || EBAN.BNFPO AS _CASE_KEY
	,EBAN.MANDT AS MANDT
	,EBAN.BANFN AS BANFN
	,EBAN.BNFPO AS BNFPO
    ,CASE 
        WHEN CHANGES.VALUE_NEW IN <%=blockPrIndicators%> THEN 'Lehne BANF ab'
        WHEN CHANGES.VALUE_NEW IN <%=releasePrIndicators%> THEN 'Gebe BANF frei' 
    END AS ACTIVITY_DE
    ,CASE
        WHEN CHANGES.VALUE_NEW IN <%=blockPrIndicators%> THEN 'Refuse Purchase Requisition'
        WHEN CHANGES.VALUE_NEW IN <%=releasePrIndicators%>  THEN 'Release Purchase Requisition' 
    END AS ACTIVITY_EN
    ,CAST(CHANGES.UDATE AS DATE) + CAST(CHANGES.UTIME AS TIME) AS EVENTTIME
    ,CASE 
		WHEN CHANGES.VALUE_NEW IN <%=blockPrIndicators%> THEN 300
        WHEN CHANGES.VALUE_NEW IN <%=releasePrIndicators%> THEN 400	
	END AS _SORTING
    ,CHANGES.USERNAME AS USER_NAME
    ,USR02.USTYP AS USER_TYPE
    ,CHANGES.TABNAME AS CHANGED_TABLE
    ,CHANGES.FNAME AS CHANGED_FIELD
    ,CHANGES.VALUE_OLD AS CHANGED_FROM
    ,CHANGES.VALUE_NEW AS CHANGED_TO
    ,CHANGES.CHANGENR AS CHANGE_NUMBER
    ,CHANGES.TCODE AS TRANSACTION_CODE
    ,CHANGES.MANDANT || CHANGES.OBJECTCLAS || CHANGES.OBJECTID || CHANGES.CHANGENR AS _ACTIVITY_KEY
FROM 
	<$EBAN> AS EBAN 
    JOIN PR_CDHDR_CDPOS AS CHANGES ON 1=1 
	  AND EBAN.MANDT = CHANGES.MANDANT
		AND EBAN.MANDT || EBAN.BANFN || EBAN.BNFPO = CHANGES.TABKEY
    AND CHANGES.OBJECTCLAS = 'BANF'
    AND CHANGES.FNAME = 'FRGKZ' 
    AND (CHANGES.VALUE_NEW IN <%=blockPrIndicators%> OR CHANGES.VALUE_NEW IN <%=releasePrIndicators%> OR CHANGES.VALUE_NEW = 'N')
    LEFT JOIN USR02 AS USR02 ON
		CHANGES.MANDANT = USR02.MANDT AND
		CHANGES.USERNAME = USR02.BNAME
;
