
DROP VIEW IF EXISTS _CEL_PR_ACTIVITIES;
CREATE VIEW _CEL_PR_ACTIVITIES AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>._CEL_PR_ACTIVITIES 
);

DROP VIEW IF EXISTS PR_EBAN;
CREATE VIEW PR_EBAN AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_EBAN    
);

DROP VIEW IF EXISTS PR_EBAN_HEADER;
CREATE VIEW PR_EBAN_HEADER AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_EBAN_HEADER    
);

DROP VIEW IF EXISTS "PR_CONTRACT_RECOMMENDATION";
CREATE VIEW PR_CONTRACT_RECOMMENDATION AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_CONTRACT_RECOMMENDATION    
);

DROP VIEW IF EXISTS PR_LFA1;
CREATE VIEW PR_LFA1 AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_LFA1 
);

DROP VIEW IF EXISTS PR_LFM1;
CREATE VIEW PR_LFM1 AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_LFM1 
);

DROP VIEW IF EXISTS PR_EKPO;
CREATE VIEW PR_EKPO AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_EKPO 
);

DROP VIEW IF EXISTS PR_EKKO;
CREATE VIEW PR_EKKO AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_EKKO 
);

DROP VIEW IF EXISTS PR_EKBE;
CREATE VIEW PR_EKBE AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_EKBE 
);

DROP VIEW IF EXISTS PR_EKET;
CREATE VIEW PR_EKET AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_EKET 
);

DROP VIEW IF EXISTS PR_CATALOGS;
CREATE VIEW PR_CATALOGS AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_CATALOGS 
);

DROP VIEW IF EXISTS PR_CONTRACTS;
CREATE VIEW PR_CONTRACTS AS (
SELECT *, EPOCH  FROM <%=DATASOURCE:JDBC%>.PR_CONTRACTS 
);

DROP VIEW IF EXISTS PR_TCURF;
CREATE VIEW "PR_TCURF" AS (
            SELECT *, EPOCH 
            FROM <%=DATASOURCE:JDBC%>."TCURF"
        );

DROP VIEW IF EXISTS PR_TCURR;
CREATE VIEW "PR_TCURR" AS (
            SELECT *, EPOCH 
            FROM <%=DATASOURCE:JDBC%>."TCURR"
        );

DROP VIEW IF EXISTS PR_TCURX;
CREATE VIEW "PR_TCURX" AS (
            SELECT *, EPOCH 
            FROM <%=DATASOURCE:JDBC%>."TCURX"
        );
