DROP VIEW IF EXISTS "_CEL_P2P_ACTIVITIES";
CREATE VIEW "_CEL_P2P_ACTIVITIES" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."_CEL_P2P_ACTIVITIES"
        );

DROP VIEW IF EXISTS _CEL_P2P_ACTIVITY_MASTER_DATA;
CREATE VIEW "_CEL_P2P_ACTIVITY_MASTER_DATA" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."_CEL_P2P_ACTIVITY_MASTER_DATA"
        );

DROP VIEW IF EXISTS "P2P_BKPF";
CREATE VIEW "P2P_BKPF" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_BKPF"
        );

DROP VIEW IF EXISTS "P2P_BSEG";
CREATE VIEW "P2P_BSEG" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_BSEG"
        );

DROP VIEW IF EXISTS "P2P_EBAN";
CREATE VIEW "P2P_EBAN" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_EBAN"
        );

DROP VIEW IF EXISTS "P2P_EKPO";
CREATE VIEW "P2P_EKPO" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_EKPO"
        );

DROP VIEW IF EXISTS "P2P_EKKO";
CREATE VIEW "P2P_EKKO" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_EKKO"
        );

DROP VIEW IF EXISTS "P2P_EKBE";
CREATE VIEW "P2P_EKBE" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_EKBE"
        );

DROP VIEW IF EXISTS "P2P_EKET";
CREATE VIEW "P2P_EKET" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_EKET"
        );

DROP VIEW IF EXISTS "P2P_EINE";
CREATE VIEW "P2P_EINE" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_EINE"
        );

DROP VIEW IF EXISTS "P2P_EKES";
CREATE VIEW "P2P_EKES" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_EKES"
        );

DROP VIEW IF EXISTS "P2P_MARA";
CREATE VIEW "P2P_MARA" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_MARA"
        );

DROP VIEW IF EXISTS "P2P_MARC";
CREATE VIEW "P2P_MARC" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_MARC"
        );

DROP VIEW IF EXISTS "P2P_MSEG";
CREATE VIEW "P2P_MSEG" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_MSEG"
        );

DROP VIEW IF EXISTS "P2P_NAST";
CREATE VIEW "P2P_NAST" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_NAST"
        );

DROP VIEW IF EXISTS "P2P_LFA1";
CREATE VIEW "P2P_LFA1" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_LFA1"
        );

DROP VIEW IF EXISTS "P2P_LFB1";
CREATE VIEW "P2P_LFB1" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_LFB1"
        );

DROP VIEW IF EXISTS "P2P_LFM1";
CREATE VIEW "P2P_LFM1" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_LFM1"
        );

DROP VIEW IF EXISTS "P2P_QALS";
CREATE VIEW "P2P_QALS" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_QALS"
        );

DROP VIEW IF EXISTS "P2P_QAVE";
CREATE VIEW "P2P_QAVE" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_QAVE"
        );

DROP VIEW IF EXISTS "P2P_RSEG";
CREATE VIEW "P2P_RSEG" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_RSEG"
        );

DROP VIEW IF EXISTS "P2P_RBKP";
CREATE VIEW "P2P_RBKP" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_RBKP"
        );

DROP VIEW IF EXISTS "P2P_CONTRACT_INFO";
CREATE VIEW "P2P_CONTRACT_INFO" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_CONTRACT_INFO"
        );

DROP VIEW IF EXISTS "P2P_CONTRACT_RECOMMENDATION";
CREATE VIEW "P2P_CONTRACT_RECOMMENDATION" AS (
            SELECT * , EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."P2P_CONTRACT_RECOMMENDATION"
        );

DROP VIEW IF EXISTS P2P_TCURF;
CREATE VIEW "P2P_TCURF" AS (
            SELECT *, EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."TCURF"
        );

DROP VIEW IF EXISTS P2P_TCURR;
CREATE VIEW "P2P_TCURR" AS (
            SELECT *, EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."TCURR"
        );

DROP VIEW IF EXISTS P2P_TCURX;
CREATE VIEW "P2P_TCURX" AS (
            SELECT *, EPOCH 
            FROM <%=DATASOURCE:SAP_ECC%>."TCURX"
        );
