INSERT INTO _CEL_O2C_VBAP_ACTIVITIES (
    _CASE_KEY,
    _ACTIVITY_DE,
    _ACTIVITY_EN,
    _EVENTTIME,
    _SORTING,
    USER_NAME,
    USER_TYPE,
    MANDT,
    VBELN,
    POSNR, 
    TRANSACTION_CODE,
    _ACTIVITY_KEY)

SELECT * FROM (

    SELECT 
        VBAP.MANDT || VBAP.VBELN || VBAP.POSNR AS _CASE_KEY
        ,'Lege Auftragsposition an' AS ACTIVITY_DE
        , 'Create Sales Order Item' AS ACTIVITY_EN
        , CAST(VBAP.ERDAT AS DATE) + CAST(VBAP.ERZET AS TIME) AS EVENTTIME
        , 20 AS _SORTING
        ,VBAP.ERNAM AS USER_NAME
        , USR02.USTYP AS USER_TYPE
        ,VBAP.MANDT AS MANDT
        ,VBAP.VBELN AS VBELN
        ,VBAP.POSNR AS POSNR
    ,V_CHANGES.TCODE AS TRANSACTION_CODE
    ,VBAP.MANDT || VBAP.VBELN || VBAP.POSNR AS _ACTIVITY_KEY
FROM
        _CELONIS_TMP_VBAP_TRANSFORM_DATA AS VBAP
    JOIN VBAK ON 1=1 
        AND VBAK.MANDT = VBAP.MANDT
        AND VBAK.VBELN = VBAP.VBELN
        AND VBAK.VBTYP ='<%=orderDocSalesOrders%>'
        LEFT JOIN USR02 AS USR02 ON
                VBAP.MANDT = USR02.MANDT AND
                VBAP.ERNAM = USR02.BNAME 
    LEFT JOIN TMP_SO_CDHDR_CDPOS AS V_CHANGES ON 1=1
            AND VBAP.MANDT || VBAP.VBELN || VBAP.POSNR = V_CHANGES.TABKEY 

) AS NEW_ACTIVITIES 
 WHERE NOT EXISTS (
                    SELECT 1 FROM _CEL_O2C_VBAP_ACTIVITIES AS OLD_ACTIVITIES
                    WHERE 
                        NEW_ACTIVITIES._ACTIVITY_KEY=OLD_ACTIVITIES._ACTIVITY_KEY
                        AND NEW_ACTIVITIES.ACTIVITY_EN=OLD_ACTIVITIES.ACTIVITY_EN
 )
;
