DROP VIEW IF EXISTS "BKPF_UNION";

CREATE VIEW "BKPF_UNION" AS(
SELECT * from "BKPF_BSAK"
UNION ALL
SELECT * from "BKPF_BSIK"
);

DROP TABLE IF EXISTS "BKPF" CASCADE;

CREATE TABLE "BKPF" AS(
SELECT
    ROW_NUMBER() 
        OVER(PARTITION BY "BKPF"."MANDT", "BKPF"."BUKRS", "BKPF"."BELNR", "BKPF"."GJAHR" 
            ORDER BY "BKPF"."MANDT", "BKPF"."BUKRS", "BKPF"."BELNR", "BKPF"."GJAHR", "_CELONIS_CHANGE_DATE" DESC) AS NUM
	,"BKPF".*
FROM 
    "BKPF_UNION" AS BKPF
     ORDER BY "BKPF"."MANDT", "BKPF"."BUKRS", "BKPF"."BELNR", "BKPF"."GJAHR"
)

;

DELETE FROM "BKPF" WHERE NUM > 1;

DROP VIEW IF EXISTS "BKPF_UNION";


SELECT ANALYZE_STATISTICS ('BKPF');
