
DROP TABLE IF EXISTS _CEL_PR_EBAN_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_PR_EKPO_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_PR_CDHDR_ACTIVITIES;


CREATE TABLE _CEL_PR_EBAN_ACTIVITIES (
  _CASE_KEY VARCHAR(30)
  ,ACTIVITY_EN VARCHAR (200)
  ,_ACTIVITY_KEY VARCHAR(50)
	,MANDT NCHAR(3)
	,BANFN VARCHAR(10)
	,BNFPO VARCHAR(5)
  ,ACTIVITY_DE VARCHAR (300)
	,EVENTTIME DATETIME
	,_SORTING INTEGER
	,USER_NAME VARCHAR(100)
	,USER_TYPE VARCHAR(10)
	,CHANGED_TABLE VARCHAR(20)
	,CHANGED_TABLE_TEXT_DE VARCHAR(200)
	,CHANGED_TABLE_TEXT_EN VARCHAR(200)
	,CHANGED_FIELD VARCHAR(20)
	,CHANGED_FIELD_TEXT_DE VARCHAR(200)
	,CHANGED_FIELD_TEXT_EN VARCHAR(200)
	,CHANGED_FROM VARCHAR(50)
	,CHANGED_TO VARCHAR(50)
	,CHANGED_FROM_FLOAT FLOAT
	,CHANGED_TO_FLOAT FLOAT
	,CHANGE_NUMBER VARCHAR(50)
	,TRANSACTION_CODE VARCHAR(20)
    ,_CELONIS_CHANGE_DATE DATETIME

)
ORDER BY 	
    _CASE_KEY 
  	,ACTIVITY_EN 
    ,_ACTIVITY_KEY
    ;


CREATE TABLE _CEL_PR_EKPO_ACTIVITIES LIKE _CEL_PR_EBAN_ACTIVITIES including projections;
CREATE TABLE _CEL_PR_CDHDR_ACTIVITIES LIKE _CEL_PR_EBAN_ACTIVITIES including projections;


DROP VIEW IF EXISTS _CEL_PR_ACTIVITIES;

CREATE VIEW _CEL_PR_ACTIVITIES AS(
    SELECT *,EPOCH FROM _CEL_PR_EBAN_ACTIVITIES
        UNION ALL
    SELECT *,EPOCH FROM _CEL_PR_EKPO_ACTIVITIES
        UNION ALL
    SELECT *,EPOCH FROM _CEL_PR_CDHDR_ACTIVITIES
)
;
