
DELETE FROM P2P_EKPO_STAGING
WHERE EXISTS (SELECT 1 FROM <$EKPO> as NEW_DATA 
              WHERE P2P_EKPO_STAGING.MANDT = NEW_DATA.MANDT 
              AND P2P_EKPO_STAGING.EBELN = NEW_DATA.EBELN
              AND P2P_EKPO_STAGING.EBELP = NEW_DATA.EBELP
              );


INSERT INTO P2P_EKPO_STAGING
SELECT 
    EKPO.MANDT,
    EKPO.EBELN,
    EKPO.EBELP,
    EKPO.KONNR, 
    EKPO.LMEIN, 
    EKPO.GEWEI, 
    EKPO.MATNR,
    EKPO.WERKS,
    EKPO.BUKRS,
    EKPO.KTPNR,
    EKPO.MANDT || EKPO.EBELN || EKPO.EBELP AS _CASE_KEY,
    EKPO.MANDT || EKPO.EBELN AS TABKEY_EKKO,
 	CAST(EKPO.ABDAT AS DATE) AS TS_ABDAT, 
    CAST(EKPO.AEDAT AS DATE) AS TS_AEDAT, 
    CAST(EKPO.AGDAT AS DATE) AS TS_AGDAT, 
    CAST(EKPO.DPDAT AS DATE) AS TS_DPDAT, 
    CAST(EKPO.DRDAT AS DATE) AS TS_DRDAT, 
    CAST(EKPO.EILDT AS DATE) AS TS_EILDT, 
    CAST(EKPO.J_1AIDATEP AS DATE) AS TS_J_1AIDATEP, 
    CAST(EKPO.LEWED AS DATE) AS TS_LEWED, 
    CAST(EKPO.NFABD AS DATE) AS TS_NFABD, 
    CAST(EKPO.NLABD AS DATE) AS TS_NLABD, 
    CAST(EKPO.PRDAT AS DATE) AS TS_PRDAT,
    IFNULL(T023T.WGBEZ,'') AS MATKL_TEXT,
	IFNULL(MAKT.MAKTX,'') AS MATNR_TEXT,
	IFNULL(T001.BUTXT,'') AS BUKRS_TEXT,
	IFNULL(T001W.NAME1,'') AS WERKS_TEXT,
    IFNULL(T001W.LAND1,'') AS WERKS_COUNTRY_KEY,
	IFNULL(T001L.LGOBE,'') AS LGORT_TEXT,
	IFNULL(PSTYP.PTEXT,'') AS PSTYP_TEXT,
	IFNULL(T163I.KNTTX,'') AS KNTTP_TEXT,
	EKPO_CURR_TMP.NETWR_CONVERTED AS NETWR_CONVERTED,
  	EKPO_CURR_TMP.NETPR_CONVERTED AS NETPR_CONVERTED,
    E.LIFNR,
    E.WAERS,
    E.EKORG,
    IFNULL(EKPO.WERKS,'_CEL_NULL_JOIN') AS "WERKS_JOIN"
  FROM 
    <$EKPO> AS EKPO
    JOIN TMP_P2P_EKKO_EKPO AS E ON 1=1
        AND EKPO.MANDT = E.MANDT
        AND EKPO.EBELN = E.EBELN
        AND EKPO.EBELP = E.EBELP
    LEFT JOIN EKPO_CURR_TMP AS EKPO_CURR_TMP ON 1=1
        AND EKPO.MANDT = EKPO_CURR_TMP.MANDT 
        AND EKPO.EBELN = EKPO_CURR_TMP.EBELN 
        AND EKPO.EBELP = EKPO_CURR_TMP.EBELP 
	LEFT JOIN MAKT AS MAKT ON 1=1
		AND EKPO.MANDT = MAKT.MANDT
		AND EKPO.MATNR = MAKT.MATNR
		AND MAKT.SPRAS = '<%=primaryLanguageKey%>' 
	LEFT JOIN T023T AS T023T ON 1=1
		AND EKPO.MANDT = T023T.MANDT
		AND EKPO.MATKL = T023T.MATKL
		AND T023T.SPRAS = '<%=primaryLanguageKey%>' 
	LEFT JOIN T001 AS T001 ON 1=1
		AND EKPO.MANDT = T001.MANDT
		AND EKPO.BUKRS = T001.BUKRS
	LEFT JOIN T001W AS T001W ON 1=1
		AND EKPO.MANDT = T001W.MANDT
		AND EKPO.WERKS = T001W.WERKS
	LEFT JOIN T001L AS T001L ON 1=1
		AND EKPO.MANDT = T001L.MANDT
		AND EKPO.WERKS = T001L.WERKS
		AND EKPO.LGORT = T001L.LGORT
	LEFT JOIN T163Y AS PSTYP ON 1=1
		AND PSTYP.MANDT = EKPO.MANDT
		AND PSTYP.PSTYP = EKPO.PSTYP
		AND PSTYP.SPRAS = '<%=primaryLanguageKey%>'
	LEFT JOIN T163I AS T163I ON 1=1
	    AND T163I.MANDT = EKPO.MANDT
		AND T163I.KNTTP = EKPO.KNTTP	 
		AND T163I.SPRAS = '<%=primaryLanguageKey%>'
;

SELECT ANALYZE_STATISTICS ('P2P_EKPO_STAGING'); 

