DELETE FROM P2P_BSIK_STAGING
WHERE EXISTS (SELECT 1 FROM <$BSIK> as NEW_DATA 
              WHERE P2P_BSIK_STAGING.MANDT = NEW_DATA.MANDT 
              AND P2P_BSIK_STAGING.BUKRS= NEW_DATA.BUKRS
              AND P2P_BSIK_STAGING.BELNR = NEW_DATA.BELNR
               AND P2P_BSIK_STAGING.GJAHR = NEW_DATA.GJAHR 
               AND P2P_BSIK_STAGING.BUZEI = NEW_DATA.BUZEI 
              );


INSERT INTO P2P_BSIK_STAGING
SELECT 
    BSIK.MANDT,
    BSIK.BUKRS,
    BSIK.GJAHR,
    BSIK.BELNR,
    BSIK.BUZEI,
    BKPF.AWKEY,
    CAST(BSIK.AUGDT AS DATE) AS TS_AUGDT, 
    CAST(BKPF.CPUDT AS DATE) AS TS_AUGCP
FROM 
    <$BSIK> AS BSIK
	INNER JOIN BKPF AS BKPF ON 1=1
        AND BKPF.MANDT = BSIK.MANDT
        AND BKPF.BUKRS = BSIK.BUKRS
        AND BKPF.BELNR = BSIK.BELNR
        AND BKPF.GJAHR = BSIK.GJAHR
    WHERE EXISTS(
        SELECT * 
        FROM P2P_RSEG_STAGING AS RE 
        WHERE 1=1
        AND BKPF.MANDT = RE.MANDT
		AND SUBSTRING(BKPF.AWKEY,1,14) = RE.BELNR || CAST(RE.GJAHR AS VARCHAR(4)))
        ;

--------------------------
DELETE FROM P2P_BSAK_STAGING
WHERE EXISTS (SELECT 1 FROM <$BSAK> as NEW_DATA 
            WHERE P2P_BSAK_STAGING.MANDT = NEW_DATA.MANDT 
              AND P2P_BSAK_STAGING.BUKRS= NEW_DATA.BUKRS
              AND P2P_BSAK_STAGING.BELNR = NEW_DATA.BELNR
               AND P2P_BSAK_STAGING.GJAHR = NEW_DATA.GJAHR 
               AND P2P_BSAK_STAGING.BUZEI = NEW_DATA.BUZEI
              );


INSERT INTO P2P_BSAK_STAGING
SELECT 
    BSAK.MANDT,
    BSAK.BUKRS,
    BSAK.GJAHR,
    BSAK.BELNR,
    BSAK.BUZEI,
    BKPF.AWKEY,
    CAST(BSAK.AUGDT AS DATE) AS TS_AUGDT, 
    CAST(BKPF.CPUDT AS DATE) AS TS_AUGCP
FROM 
    <$BSAK> AS BSAK
	INNER JOIN BKPF AS BKPF ON 1=1
        AND BKPF.MANDT = BSAK.MANDT
        AND BKPF.BUKRS = BSAK.BUKRS
        AND BKPF.BELNR = BSAK.BELNR
        AND BKPF.GJAHR = BSAK.GJAHR
    WHERE EXISTS(
        SELECT * 
        FROM P2P_RSEG_STAGING AS RE 
        WHERE 1=1
        AND BKPF.MANDT = RE.MANDT
		AND SUBSTRING(BKPF.AWKEY,1,14) = RE.BELNR || CAST(RE.GJAHR AS VARCHAR(4)))
        ;

SELECT ANALYZE_STATISTICS ('P2P_BSIK_STAGING'); 
SELECT ANALYZE_STATISTICS ('P2P_BSAK_STAGING'); 



