INSERT INTO _CEL_P2P_EKPO_ACTIVITIES_DELTA(
    _CASE_KEY
    ,MANDT
	,EBELN
	,EBELP
    ,ACTIVITY_DE
    ,ACTIVITY_EN
    ,EVENTTIME
    ,_SORTING
    ,USER_NAME
    ,USER_TYPE
    ,CHANGED_TABLE
    ,CHANGED_FIELD
    ,CHANGED_FROM
    ,CHANGED_TO
    ,CHANGE_NUMBER
    ,TRANSACTION_CODE
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY)
SELECT 
    E._CASE_KEY AS _CASE_KEY
    ,E.MANDT AS MANDT
	,E.EBELN AS EBELN
	,E.EBELP AS EBELP
    ,CASE 
        WHEN CHANGES.VALUE_NEW IN <%=blockPrIndicators%> THEN 'Lehne BANF ab'
        WHEN CHANGES.VALUE_NEW IN <%=releasePrIndicators%> THEN 'Gebe BANF frei' 
    END AS ACTIVITY_DE
    ,CASE 
        WHEN CHANGES.VALUE_NEW IN <%=blockPrIndicators%> THEN 'Refuse Purchase Requisition'
        WHEN CHANGES.VALUE_NEW IN <%=releasePrIndicators%>  THEN 'Release Purchase Requisition' 
    END AS ACTIVITY_EN
    ,CHANGES.EVENTTIME AS EVENTTIME
    ,CASE 
		WHEN CHANGES.VALUE_NEW IN <%=blockPrIndicators%> THEN 300
        WHEN CHANGES.VALUE_NEW IN <%=releasePrIndicators%> THEN 400	
	END AS _SORTING
    ,CHANGES.USERNAME AS USER_NAME
    ,USR02.USTYP AS USER_TYPE
    ,CHANGES.TABNAME AS CHANGED_TABLE
    ,CHANGES.FNAME AS CHANGED_FIELD
    ,CHANGES.VALUE_OLD AS CHANGED_FROM
    ,CHANGES.VALUE_NEW AS CHANGED_TO
    ,CHANGES.CHANGENR AS CHANGE_NUMBER
    ,CHANGES.TCODE AS TRANSACTION_CODE
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,CHANGES.MANDANT || CHANGES.OBJECTCLAS || CHANGES.OBJECTID || CHANGES.CHANGENR AS _ACTIVITY_KEY
FROM 
    TMP_P2P_EKKO_EKPO AS E
    JOIN P2P_CDHDR_CDPOS AS CHANGES ON 1=1
        AND E.MANDT = CHANGES.MANDANT
        AND E.TABKEY_EBAN = CHANGES.TABKEY
        AND TABNAME = 'EBAN'
        AND OBJECTCLAS = 'BANF'
        AND FNAME = 'FRGKZ'
        AND (VALUE_NEW IN <%=blockPrIndicators%> OR VALUE_NEW IN <%=releasePrIndicators%>)
    INNER JOIN P2P_EBAN_STAGING AS EBAN ON 1=1
        AND EBAN.MANDT = E.MANDT 
        AND EBAN.BANFN = E.BANFN 
        AND EBAN.BNFPO = E.BNFPO
        AND EBAN.EBELN IS NOT NULL
    LEFT JOIN USR02 AS USR02 ON 1=1
        AND EBAN.MANDT = USR02.MANDT 
        AND EBAN.ERNAM = USR02.BNAME 
;

