INSERT INTO _CEL_P2P_CDHDR_ACTIVITIES_DELTA (
	_CASE_KEY
	,MANDT
	,EBELN
	,EBELP
	,ACTIVITY_DE
	,ACTIVITY_EN
	,EVENTTIME
	,_SORTING
	,USER_NAME
	,USER_TYPE
	,CHANGED_TABLE
	,CHANGED_FIELD
	,CHANGED_FROM
	,CHANGED_TO
	,CHANGED_FROM_FLOAT
	,CHANGED_TO_FLOAT
	,CHANGE_NUMBER
	,TRANSACTION_CODE
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY)

SELECT 
	E._CASE_KEY AS _CASE_KEY
	,E.MANDT AS MANDT
	,E.EBELN AS EBELN
	,E.EBELP AS EBELP
	,CASE
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_NEW ='S' THEN 'Sperre Bestellposition'
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_OLD ='S' AND CHANGES.VALUE_NEW IS NULL THEN 'Reaktiviere Bestellposition'
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_NEW ='L' THEN 'Lösche Bestellposition'
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_OLD ='L' AND CHANGES.VALUE_NEW IS NULL THEN 'Reaktiviere Bestellposition'
		WHEN CHANGES.FNAME = 'LOEKZ' THEN 'Ändere Löschkennzeichen für Bestellposition'
		WHEN CHANGES.FNAME = 'NETPR' THEN 'Ändere Preis'
		WHEN CHANGES.FNAME = 'MENGE' THEN 'Ändere Menge'
		WHEN CHANGES.FNAME = 'LGORT' THEN 'Ändere Lagerort'
		WHEN CHANGES.FNAME = 'LABNR' AND CHANGES.VALUE_OLD IS NULL THEN 'Erhalte Auftragsbestätigung'
		WHEN CHANGES.FNAME = 'LABNR' THEN 'Ändere Auftragsbestätigung'
		WHEN CHANGES.FNAME = 'ELIKZ' THEN 'Ändere Endlieferungskennzeichen'
		WHEN CHANGES.FNAME = 'EREKZ' THEN 'Ändere Endrechnungskennzeichen'
		WHEN CHANGES.FNAME = 'EGLKZ' THEN 'Ändere Endauslieferungskennzeichen'
		WHEN CHANGES.FNAME = 'ABSKZ' THEN 'Ändere Absagekennzeichen'
        WHEN CHANGES.FNAME = 'KONNR' THEN 'Ändere Vertrag'
		WHEN CHANGES.FNAME = 'KTPNR' THEN 'Ändere Vertrag'
        WHEN CHANGES.FNAME = 'TXZ01' THEN 'Ändere Textbeschreibung'
        WHEN CHANGES.FNAME = 'MATNR' THEN 'Ändere Materialnummer'
        WHEN CHANGES.FNAME = 'MATKL' THEN 'Ändere Materialgruppe'
	END AS ACTIVITY_DE
	,CASE 
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_NEW ='S' THEN 'Block Purchase Order Item'
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_OLD ='S' AND CHANGES.VALUE_NEW IS NULL THEN 'Reactivate Purchase Order Item'
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_NEW ='L' THEN 'Delete Purchase Order Item'
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_OLD ='L' AND CHANGES.VALUE_NEW IS NULL THEN 'Reactivate Purchase Order Item'
		WHEN CHANGES.FNAME = 'LOEKZ' THEN 'Change Deletion Flag for Purchase Order Item'
		WHEN CHANGES.FNAME = 'NETPR' THEN 'Change Price'
		WHEN CHANGES.FNAME = 'MENGE' THEN 'Change Quantity'
		WHEN CHANGES.FNAME = 'LGORT' THEN 'Change Storage Location'
		WHEN CHANGES.FNAME = 'LABNR' AND CHANGES.VALUE_OLD IS NULL THEN 'Receive Order Confirmation'
		WHEN CHANGES.FNAME = 'LABNR' THEN 'Update Order Confirmation'
		WHEN CHANGES.FNAME = 'ELIKZ' THEN 'Change Delivery Indicator'
		WHEN CHANGES.FNAME = 'EREKZ' THEN 'Change Final Invoice Indicator'
		WHEN CHANGES.FNAME = 'EGLKZ' THEN 'Change Outward Delivery Indicator'
		WHEN CHANGES.FNAME = 'ABSKZ' THEN 'Change Rejection Indicator'
        WHEN CHANGES.FNAME = 'KONNR' THEN 'Change Contract'
		WHEN CHANGES.FNAME = 'KTPNR' THEN 'Change Contract'
        WHEN CHANGES.FNAME = 'TXZ01' THEN 'Change Short Text Description'
        WHEN CHANGES.FNAME = 'MATNR' THEN 'Change Material Number'
        WHEN CHANGES.FNAME = 'MATKL' THEN 'Change Material Group'
	END AS ACTIVITY_EN
	,CHANGES.EVENTTIME AS EVENTTIME
	,CASE 
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_NEW ='S' THEN 610
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_OLD ='S' AND CHANGES.VALUE_NEW IS NULL THEN 620
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_NEW ='L' THEN 630
		WHEN CHANGES.FNAME = 'LOEKZ' AND CHANGES.VALUE_OLD ='L' AND CHANGES.VALUE_NEW IS NULL THEN 640
		WHEN CHANGES.FNAME = 'LOEKZ' THEN 650
		WHEN CHANGES.FNAME = 'NETPR' THEN 660
		WHEN CHANGES.FNAME = 'MENGE' THEN 670
		WHEN CHANGES.FNAME = 'LGORT' THEN 680
		WHEN CHANGES.FNAME = 'LABNR' AND COALESCE(CHANGES.VALUE_OLD, '') = '' THEN 690
		WHEN CHANGES.FNAME = 'LABNR' THEN 700
		WHEN CHANGES.FNAME = 'ELIKZ' THEN 710
		WHEN CHANGES.FNAME = 'EREKZ' THEN 720
		WHEN CHANGES.FNAME = 'EGLKZ' THEN 730
		WHEN CHANGES.FNAME = 'ABSKZ' THEN 740
        WHEN CHANGES.FNAME = 'KONNR' THEN 750
		WHEN CHANGES.FNAME = 'KTPNR' THEN 760
        WHEN CHANGES.FNAME = 'TXZ01' THEN 770
		WHEN CHANGES.FNAME = 'MATNR' THEN 780
        WHEN CHANGES.FNAME = 'MATKL' THEN 790
	END AS _SORTING
	,CHANGES.USERNAME AS USER_NAME
	,USR02.USTYP AS USER_TYPE
	,CHANGES.TABNAME AS CHANGED_TABLE
	,CHANGES.FNAME AS CHANGED_FIELD
	,CHANGES.VALUE_OLD AS CHANGED_FROM
	,CHANGES.VALUE_NEW AS CHANGED_TO
	,CASE
		WHEN CHANGES.FNAME = 'NETPR' THEN
		(CASE 
			WHEN E.WAERS = '<%=currency%>' THEN CHANGES.VALUE_OLD*ISNULL(TCURX.TDEC,1) 
         	WHEN TCURR_CC.UKURS < 0 THEN (CHANGES.VALUE_OLD*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
			WHEN TCURR_CC.UKURS > 0 THEN (CHANGES.VALUE_OLD*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
        END)
		ELSE CAST(NULL AS FLOAT)
	END AS CHANGED_FROM_FLOAT
	,CASE
		WHEN CHANGES.FNAME = 'NETPR' THEN
		(CASE 
			WHEN E.WAERS = '<%=currency%>' THEN CHANGES.VALUE_NEW*ISNULL(TCURX.TDEC,1) 
         	WHEN TCURR_CC.UKURS < 0 THEN (CHANGES.VALUE_NEW*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
			WHEN TCURR_CC.UKURS > 0 THEN (CHANGES.VALUE_NEW*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		END)
		ELSE CAST(NULL AS FLOAT)
	END AS CHANGED_TO_FLOAT
	,CHANGES.CHANGENR AS CHANGE_NUMBER
	,CHANGES.TCODE AS TRANSACTION_CODE
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,CHANGES.MANDANT || CHANGES.OBJECTCLAS || CHANGES.OBJECTID ||CHANGES.CHANGENR AS _ACTIVITY_KEY
FROM
    P2P_EKPO_STAGING AS E
    INNER JOIN TMP_P2P_CDHDR_CDPOS AS CHANGES ON 1=1
        AND CHANGES.OBJECTID = E.EBELN
        AND E.MANDT = CHANGES.MANDANT
        AND E._CASE_KEY = CHANGES.TABKEY
        AND CHANGES.TABNAME IN ('EKPO')
	    AND CHANGES.FNAME IN ('LOEKZ', 'NETPR', 'MENGE', 'LABNR','LGORT','ELIKZ', 'EREKZ','EGLKZ','ABSKZ','KONNR','KTPNR')
	LEFT JOIN USR02  AS USR02 ON 1=1
		AND CHANGES.MANDANT = USR02.MANDT
		AND CHANGES.USERNAME = USR02.BNAME
	LEFT JOIN P2P_TCURR_CC AS TCURR_CC ON 1=1
		AND TCURR_CC.MANDT = E.MANDT
		AND TCURR_CC.TCURR = '<%=currency%>'
		AND TCURR_CC.FCURR = E.WAERS
		AND TCURR_CC.KURST = '<%=exchangeRateType%>'
		AND E.TS_AEDAT >= TCURR_CC.VALID_START 
		AND E.TS_AEDAT < TCURR_CC.VALID_END
	LEFT JOIN P2P_TCURF_CC AS TCURF_CC ON 1=1
		AND TCURR_CC.MANDT = TCURF_CC.MANDT
		AND TCURR_CC.TCURR = TCURF_CC.TCURR
		AND TCURR_CC.FCURR = TCURF_CC.FCURR
		AND TCURR_CC.KURST = TCURF_CC.KURST
		AND E.TS_AEDAT >= TCURF_CC.VALID_START	
		AND E.TS_AEDAT < TCURF_CC.VALID_END
	LEFT JOIN T001 AS T001 ON 1=1
		AND E.MANDT = T001.MANDT
		AND E.BUKRS = T001.BUKRS
	LEFT JOIN (
		SELECT 
			TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
			TCURX) AS TCURX ON 1=1
		AND E.WAERS  = TCURX.CURRKEY
;
