INSERT INTO _CEL_P2P_CDHDR_ACTIVITIES_DELTA (
	_CASE_KEY
	,MANDT
	,EBELN
	,EBELP
	,ACTIVITY_DE
	,ACTIVITY_EN
	,EVENTTIME
	,_SORTING
	,USER_NAME
	,USER_TYPE
	,CHANGED_TABLE
	,CHANGED_FIELD
	,CHANGED_FROM
	,CHANGED_TO
	,CHANGED_FROM_FLOAT
	,CHANGED_TO_FLOAT
	,CHANGE_NUMBER
	,TRANSACTION_CODE
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY)
SELECT 
	 E._CASE_KEY AS _CASE_KEY
	,E.MANDT AS MANDT
	,E.EBELN AS EBELN
	,E.EBELP AS EBELP
   -- ,E.KONNR AS KONNR
  --  ,E.KTPNR AS KTPNR
	,CASE
        WHEN CHANGES.FNAME = 'KTMNG' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 'Erhöhe Vertrags Zielmenge'
        WHEN CHANGES.FNAME = 'KTMNG' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 'Senke Vertrags Zielmenge'
        WHEN CHANGES.FNAME = 'ZWERT' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 'Erhöhe Vertrags Zielwert'
        WHEN CHANGES.FNAME = 'ZWERT' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 'Senke Vertrags Zielwert'
        WHEN CHANGES.FNAME = 'NETPR' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 'Erhöhe Vertrags Preis'
        WHEN CHANGES.FNAME = 'NETPR' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 'Senke Vertrags Preis'
        WHEN CHANGES.FNAME = 'EFFWR' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 'Erhöhe effektiven Vertrags Bestellwert'
        WHEN CHANGES.FNAME = 'EFFWR' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 'Senke effektiven Vertrags Bestellwert'
	END AS ACTIVITY_DE
	,CASE 
        WHEN CHANGES.FNAME = 'KTMNG' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 'Increase Contract Target Quantity'
        WHEN CHANGES.FNAME = 'KTMNG' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 'Decrease Contract Target Quantity'
        WHEN CHANGES.FNAME = 'ZWERT' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 'Increase Contract Target Value'
        WHEN CHANGES.FNAME = 'ZWERT' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 'Decrease Contract Target Value'
        WHEN CHANGES.FNAME = 'NETPR' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 'Increase Contract Net Price'
        WHEN CHANGES.FNAME = 'NETPR' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 'Decrease Contract Net Price'
        WHEN CHANGES.FNAME = 'EFFWR' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 'Increase Effective Contract Item Value'
        WHEN CHANGES.FNAME = 'EFFWR' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 'Decrease Effective Contract Item Value'
	END AS ACTIVITY_EN
	,CHANGES.EVENTTIME AS EVENTTIME
	,CASE 
        WHEN CHANGES.FNAME = 'KTMNG' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 1110
        WHEN CHANGES.FNAME = 'KTMNG' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 1120
        WHEN CHANGES.FNAME = 'ZWERT' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 1130
        WHEN CHANGES.FNAME = 'ZWERT' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 1140
        WHEN CHANGES.FNAME = 'NETPR' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 1150
        WHEN CHANGES.FNAME = 'NETPR' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 1160
        WHEN CHANGES.FNAME = 'EFFWR' AND CHANGES.VALUE_NEW > CHANGES.VALUE_OLD THEN 1170
        WHEN CHANGES.FNAME = 'EFFWR' AND CHANGES.VALUE_NEW < CHANGES.VALUE_OLD THEN 1180
	END AS _SORTING
	,CHANGES.USERNAME AS USER_NAME
	,USR02.USTYP AS USER_TYPE
	,CHANGES.TABNAME AS CHANGED_TABLE
	,CHANGES.FNAME AS CHANGED_FIELD
	,CHANGES.VALUE_OLD AS CHANGED_FROM
	,CHANGES.VALUE_NEW AS CHANGED_TO
	,CASE
		WHEN CHANGES.FNAME = 'NETPR' THEN
		(CASE 
			WHEN CONTRACTS.WAERS = '<%=currency%>' THEN CHANGES.VALUE_OLD*IFNULL(TCURX.TDEC,1) 
         	WHEN TCURR_CC.UKURS < 0 THEN (CHANGES.VALUE_OLD*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
			WHEN TCURR_CC.UKURS > 0 THEN (CHANGES.VALUE_OLD*IFNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		END)
		ELSE CAST(NULL AS FLOAT)
	END AS CHANGED_FROM_FLOAT
	,CASE
		WHEN CHANGES.FNAME = 'NETPR' THEN
		(CASE 
			WHEN CONTRACTS.WAERS = '<%=currency%>' THEN CHANGES.VALUE_NEW*IFNULL(TCURX.TDEC,1) 
         	WHEN TCURR_CC.UKURS < 0 THEN (CHANGES.VALUE_OLD*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
			WHEN TCURR_CC.UKURS > 0 THEN (CHANGES.VALUE_NEW*IFNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		END)
		ELSE CAST(NULL AS FLOAT)
	END AS CHANGED_TO_FLOAT
	,CHANGES.CHANGENR AS CHANGE_NUMBER
	,CHANGES.TCODE AS TRANSACTION_CODE
    , NOW() AS _CELONIS_CHANGE_DATE
    ,CHANGES.MANDANT || CHANGES.OBJECTCLAS || CHANGES.OBJECTID || CHANGES.CHANGENR AS _ACTIVITY_KEY
FROM
    P2P_CONTRACT_INFO AS CONTRACTS
    INNER JOIN  TMP_P2P_CDHDR_CDPOS AS CHANGES ON 1=1
        AND CONTRACTS.MANDT = CHANGES.MANDANT
        AND CONTRACTS.EBELN = CHANGES.OBJECTID
        AND CONTRACTS.CONTRACT_CASEKEY = CHANGES.TABKEY
        AND CHANGES.TABNAME = 'EKPO'
        AND CHANGES.FNAME IN ('NETPR', 'KTMNG', 'ZWERT', 'EFFWR')
    INNER JOIN P2P_EKPO_STAGING AS E ON 1=1
    	AND E.MANDT = CONTRACTS.MANDT 
        AND E.KONNR = CONTRACTS.EBELN
        AND E.KTPNR = CONTRACTS.EBELP
	LEFT JOIN USR02  AS USR02 ON 1=1
		AND CHANGES.MANDANT = USR02.MANDT
		AND CHANGES.USERNAME = USR02.BNAME
	LEFT JOIN P2P_TCURR_CC AS TCURR_CC ON 1=1
		AND TCURR_CC.MANDT = E.MANDT
		AND TCURR_CC.TCURR = '<%=currency%>'
		AND TCURR_CC.FCURR = E.WAERS
		AND TCURR_CC.KURST = '<%=exchangeRateType%>'
		AND CONTRACTS.TS_AEDAT >= TCURR_CC.VALID_START 
		AND CONTRACTS.TS_AEDAT < TCURR_CC.VALID_END
	LEFT JOIN P2P_TCURF_CC AS TCURF_CC ON 1=1
		AND TCURR_CC.MANDT = TCURF_CC.MANDT
		AND TCURR_CC.TCURR = TCURF_CC.TCURR
		AND TCURR_CC.FCURR = TCURF_CC.FCURR
		AND TCURR_CC.KURST = TCURF_CC.KURST
		AND CONTRACTS.TS_AEDAT >= TCURF_CC.VALID_START	
		AND CONTRACTS.TS_AEDAT < TCURF_CC.VALID_END
	LEFT JOIN T001 AS T001 ON 1=1
		AND CONTRACTS.MANDT = T001.MANDT
		AND CONTRACTS.BUKRS = T001.BUKRS
	LEFT JOIN (
		SELECT 
			TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
			TCURX) AS TCURX ON 1=1
		AND CONTRACTS.WAERS  = TCURX.CURRKEY
;
