INSERT INTO _CEL_P2P_EKES_ACTIVITIES_DELTA(
  _CASE_KEY
  ,MANDT
	,EBELN
	,EBELP
  ,ACTIVITY_DE
  ,ACTIVITY_EN
  ,EVENTTIME
  ,_SORTING
  ,_CELONIS_CHANGE_DATE
  ,_ACTIVITY_KEY)
SELECT
	E._CASE_KEY AS _CASE_KEY
	,E.MANDT AS MANDT
	,E.EBELN AS EBELN
	,E.EBELP AS EBELP
	,'Erhalte Lieferavis' AS ACTIVITY_DE
	,'Receive advanced shipment notice (ASN)' AS ACTIVITY_EN
	,CAST(EKES.ERDAT AS DATE) + CAST(EKES.EZEIT AS TIME) AS EVENTTIME
	,1700 AS _SORTING
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,E.MANDT || E.EBELN || E.EBELP || EKES.ETENS AS _ACTIVITY_KEY
FROM
	P2P_EKPO_STAGING AS E
	INNER JOIN <$EKES>  AS EKES ON
		 EKES.MANDT = E.MANDT
        AND EKES.EBELN = E.EBELN
        AND EKES.EBELP = E.EBELP
        AND EKES.EBTYP LIKE 'L%'
;



--Cleanup

DELETE FROM
    _CEL_P2P_EKES_ACTIVITIES_DELTA
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_EKES_ACTIVITIES_DELTA
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_EKES_ACTIVITIES_DELTA
WHERE
    YEAR(EVENTTIME) > 5000 
;

-- Statistics
SELECT ANALYZE_STATISTICS('_CEL_P2P_EKES_ACTIVITIES_DELTA');


-- Merge
INSERT INTO _CEL_P2P_EKES_ACTIVITIES_DELTA
SELECT *
FROM _CEL_P2P_EKES_ACTIVITIES_DELTA AS NEW_ACTIVITIES
 WHERE NOT EXISTS (
                    SELECT 1 FROM _CEL_P2P_EKES_ACTIVITIES_DELTA AS OLD_ACTIVITIES
                    WHERE NEW_ACTIVITIES._CASE_KEY=OLD_ACTIVITIES._CASE_KEY
                      AND NEW_ACTIVITIES.ACTIVITY_EN=OLD_ACTIVITIES.ACTIVITY_EN
                        AND NEW_ACTIVITIES._ACTIVITY_KEY=OLD_ACTIVITIES._ACTIVITY_KEY 
                    );
