
-- Query 1
DROP TABLE IF EXISTS TMP_P2P_CDHDR_CDPOS_BSEG;

-- Query 2
CREATE TABLE TMP_P2P_CDHDR_CDPOS_BSEG AS (
	SELECT
	CDPOS.MANDANT
	,CDPOS.FNAME
	,CDPOS.TABNAME
	,CDPOS.TABKEY
	,CDPOS.VALUE_OLD
	,CDPOS.VALUE_NEW
	,CAST(CDHDR.UDATE AS DATE) + CAST(CDHDR.UTIME AS TIME) AS EVENTTIME
	,CDHDR.CHANGENR
    ,CDPOS.CHNGIND
	,CDHDR.TCODE
	,CDPOS.OBJECTCLAS
	,CDPOS.OBJECTID
	,CDHDR.USERNAME
	FROM CDHDR AS CDHDR
	    JOIN CDPOS AS CDPOS ON
		    CDPOS.MANDANT = CDHDR.MANDANT AND
		    CDPOS.OBJECTCLAS = CDHDR.OBJECTCLAS AND
		    CDPOS.OBJECTID = CDHDR.OBJECTID AND
		    CDPOS.CHANGENR = CDHDR.CHANGENR
        AND CDPOS.CHNGIND IN ('U', 'I')
        AND CDPOS.TABNAME = 'BSEG'
        AND CDPOS.FNAME = 'ZLSPR') ;

 SELECT ANALYZE_STATISTICS ('TMP_P2P_CDHDR_CDPOS_BSEG'); 

