DROP VIEW IF EXISTS BSEG_UNION;

CREATE VIEW BSEG_UNION AS (
SELECT
     BSAK.MANDT
    ,BSAK.BUKRS
    ,BSAK.UMSKS
    ,BSAK.UMSKZ
    ,BSAK.AUGDT
    ,BSAK.AUGBL
    ,BSAK.ZUONR
    ,BSAK.GJAHR
    ,BSAK.BELNR
    ,BSAK.BUZEI
    ,BSAK.BUDAT
    ,BSAK.BLDAT
    ,BSAK.CPUDT
    ,BSAK.WAERS
    ,BSAK.XBLNR
    ,BSAK.BLART
    ,BSAK.MONAT
    ,BSAK.BSCHL
    ,BSAK.ZUMSK
    ,BSAK.SHKZG
    ,BSAK.GSBER
    ,BSAK.MWSKZ
    ,BSAK.DMBTR
    ,BSAK.WRBTR
    ,BSAK.MWSTS
    ,BSAK.WMWST
    ,BSAK.BDIFF
    ,BSAK.BDIF2
    ,BSAK.SGTXT
    ,BSAK.PROJN
    ,BSAK.AUFNR
    ,BSAK.ANLN1
    ,BSAK.ANLN2
    ,BSAK.SAKNR
    ,BSAK.HKONT
    ,BSAK.FKONT
    ,BSAK.FILKD
    ,BSAK.ZFBDT
    ,BSAK.ZTERM
    ,BSAK.ZBD1T
    ,BSAK.ZBD2T
    ,BSAK.ZBD3T
    ,BSAK.ZBD1P
    ,BSAK.ZBD2P
    ,BSAK.SKFBT
    ,BSAK.SKNTO
    ,BSAK.WSKTO
    ,BSAK.ZLSCH
    ,BSAK.ZLSPR
    ,BSAK.ZBFIX
    ,BSAK.HBKID
    ,BSAK.BVTYP
    ,BSAK.REBZG
    ,BSAK.REBZJ
    ,BSAK.REBZZ
    ,BSAK.SAMNR
    ,BSAK.ANFBN
    ,BSAK.ANFBJ
    ,BSAK.ANFBU
    ,BSAK.MANSP
    ,BSAK.MSCHL
    ,BSAK.MADAT
    ,BSAK.MANST
    ,BSAK.MABER
    ,BSAK.XNETB
    ,BSAK.XANET
    ,BSAK.XCPDD
    ,BSAK.XINVE
    ,BSAK.XZAHL
    ,BSAK.MWSK1
    ,BSAK.DMBT1
    ,BSAK.WRBT1
    ,BSAK.MWSK2
    ,BSAK.DMBT2
    ,BSAK.WRBT2
    ,BSAK.MWSK3
    ,BSAK.DMBT3
    ,BSAK.WRBT3
    ,BSAK.BSTAT
    ,BSAK.VBUND
    ,BSAK.REBZT
    ,BSAK.STCEG
    ,BSAK.EGBLD
    ,BSAK.EGLLD
    ,BSAK.RSTGR
    ,BSAK.VERTT
    ,BSAK.VERTN
    ,BSAK.VBEWA
    ,BSAK.PROJK
    ,BSAK.FIPOS
    ,BSAK.NPLNR
    ,BSAK.AUFPL
    ,BSAK.APLZL
    ,BSAK.XEGDR
    ,BSAK.DMBE2
    ,BSAK.DMBE3
    ,BSAK.DMB21
    ,BSAK.DMB22
    ,BSAK.DMB23
    ,BSAK.DMB31
    ,BSAK.DMB32
    ,BSAK.DMB33
    ,BSAK.BDIF3
    ,BSAK.XRAGL
    ,BSAK.UZAWE
    ,BSAK.XSTOV
    ,BSAK.MWST2
    ,BSAK.MWST3
    ,BSAK.SKNT2
    ,BSAK.SKNT3
    ,BSAK.XREF1
    ,BSAK.XREF2
    ,BSAK.XARCH
    ,BSAK.PSWSL
    ,BSAK.PSWBT
    ,BSAK.LZBKZ
    ,BSAK.LANDL
    ,BSAK.IMKEY
    ,BSAK.FISTL
    ,BSAK.GEBER
    ,BSAK.DABRZ
    ,BSAK.XNEGP
    ,BSAK.KOSTL
    ,BSAK.EMPFB
    ,BSAK.PRCTR
    ,BSAK.XREF3
    ,BSAK.QSSKZ
    ,BSAK.ZINKZ
    ,BSAK.DTWS1
    ,BSAK.DTWS2
    ,BSAK.DTWS3
    ,BSAK.DTWS4
    ,BSAK.XPYPR
    ,BSAK.KIDNO
    ,BSAK.PYCUR
    ,BSAK.PYAMT
    ,BSAK.BUPLA
    ,BSAK.SECCO
    ,BSAK.PPDIFF
    ,BSAK.PPDIF2
    ,BSAK.PPDIF3
    ,BSAK.KBLNR
    ,BSAK.KBLPOS
    ,BSAK.GRANT_NBR
    ,BSAK.GMVKZ
    ,BSAK.SRTYPE
    ,BSAK.LOTKZ
    ,BSAK.FKBER
    ,BSAK.INTRENO
    ,BSAK.PPRCT
    ,BSAK.BUZID
    ,BSAK.AUGGJ
    ,BSAK.HKTID
    ,BSAK.BUDGET_PD
    ,BSAK.KONTT
    ,BSAK.KONTL
    ,BSAK.UEBGDAT
    ,BSAK.VNAME
    ,BSAK.EGRUP
    ,BSAK.BTYPE
    --  ,BSAK.OIEXGNUM
    --  ,BSAK.OINETCYC
    --  ,BSAK.OIEXGTYP
    ,BSAK.PROPMANO
    ,NULL AS KUNNR
    ,NULL AS ANFAE
    ,NULL AS VBELN
    ,NULL AS INFAE
    ,NULL AS XNOZA
    ,NULL AS WVERW
    ,NULL AS VBEL2
    ,NULL AS VPOS2
    ,NULL AS POSN2
    ,NULL AS ETEN2
    ,NULL AS RFZEI
    ,NULL AS KKBER
    ,NULL AS ABSBT
    ,NULL AS CCBTC
    ,NULL AS CESSION_KZ
    ,NULL AS PAYS_PROV
    ,NULL AS PAYS_TRAN
    ,NULL AS MNDID
    ,BSAK.LIFNR
    ,BSAK.EBELN
    ,BSAK.EBELP
    ,BSAK.ZOLLT
    ,BSAK.ZOLLD
    ,BSAK.DIEKZ
    ,BSAK.XESRD
    ,BSAK.QSSHB
    ,BSAK.QBSHB
    ,BSAK.QSZNR
    ,BSAK.QSFBT
    ,BSAK.LNRAN
    ,BSAK.KZBTR
    ,BSAK.ZEKKN
    ,BSAK.PENLC1
    ,BSAK.PENLC2
    ,BSAK.PENLC3
    ,BSAK.PENFC
    ,BSAK.PENDAYS
    ,BSAK.PENRC
    ,_CELONIS_CHANGE_DATE AS _CELONIS_CHANGE_DATE
FROM BSAK
 
UNION ALL
 
SELECT
    BSIK.MANDT
    ,BSIK.BUKRS
    ,BSIK.UMSKS
    ,BSIK.UMSKZ
    ,BSIK.AUGDT
    ,BSIK.AUGBL
    ,BSIK.ZUONR
    ,BSIK.GJAHR
    ,BSIK.BELNR
    ,BSIK.BUZEI
    ,BSIK.BUDAT
    ,BSIK.BLDAT
    ,BSIK.CPUDT
    ,BSIK.WAERS
    ,BSIK.XBLNR
    ,BSIK.BLART
    ,BSIK.MONAT
    ,BSIK.BSCHL
    ,BSIK.ZUMSK
    ,BSIK.SHKZG
    ,BSIK.GSBER
    ,BSIK.MWSKZ
    ,BSIK.DMBTR
    ,BSIK.WRBTR
    ,BSIK.MWSTS
    ,BSIK.WMWST
    ,BSIK.BDIFF
    ,BSIK.BDIF2
    ,BSIK.SGTXT
    ,BSIK.PROJN
    ,BSIK.AUFNR
    ,BSIK.ANLN1
    ,BSIK.ANLN2
    ,BSIK.SAKNR
    ,BSIK.HKONT
    ,BSIK.FKONT
    ,BSIK.FILKD
    ,BSIK.ZFBDT
    ,BSIK.ZTERM
    ,BSIK.ZBD1T
    ,BSIK.ZBD2T
    ,BSIK.ZBD3T
    ,BSIK.ZBD1P
    ,BSIK.ZBD2P
    ,BSIK.SKFBT
    ,BSIK.SKNTO
    ,BSIK.WSKTO
    ,BSIK.ZLSCH
    ,BSIK.ZLSPR
    ,BSIK.ZBFIX
    ,BSIK.HBKID
    ,BSIK.BVTYP
    ,BSIK.REBZG
    ,BSIK.REBZJ
    ,BSIK.REBZZ
    ,BSIK.SAMNR
    ,BSIK.ANFBN
    ,BSIK.ANFBJ
    ,BSIK.ANFBU
    ,BSIK.MANSP
    ,BSIK.MSCHL
    ,BSIK.MADAT
    ,BSIK.MANST
    ,BSIK.MABER
    ,BSIK.XNETB
    ,BSIK.XANET
    ,BSIK.XCPDD
    ,BSIK.XINVE
    ,BSIK.XZAHL
    ,BSIK.MWSK1
    ,BSIK.DMBT1
    ,BSIK.WRBT1
    ,BSIK.MWSK2
    ,BSIK.DMBT2
    ,BSIK.WRBT2
    ,BSIK.MWSK3
    ,BSIK.DMBT3
    ,BSIK.WRBT3
    ,BSIK.BSTAT
    ,BSIK.VBUND
    ,BSIK.REBZT
    ,BSIK.STCEG
    ,BSIK.EGBLD
    ,BSIK.EGLLD
    ,BSIK.RSTGR
    ,BSIK.VERTT
    ,BSIK.VERTN
    ,BSIK.VBEWA
    ,BSIK.PROJK
    ,BSIK.FIPOS
    ,BSIK.NPLNR
    ,BSIK.AUFPL
    ,BSIK.APLZL
    ,BSIK.XEGDR
    ,BSIK.DMBE2
    ,BSIK.DMBE3
    ,BSIK.DMB21
    ,BSIK.DMB22
    ,BSIK.DMB23
    ,BSIK.DMB31
    ,BSIK.DMB32
    ,BSIK.DMB33
    ,BSIK.BDIF3
    ,BSIK.XRAGL
    ,BSIK.UZAWE
    ,BSIK.XSTOV
    ,BSIK.MWST2
    ,BSIK.MWST3
    ,BSIK.SKNT2
    ,BSIK.SKNT3
    ,BSIK.XREF1
    ,BSIK.XREF2
    ,BSIK.XARCH
    ,BSIK.PSWSL
    ,BSIK.PSWBT
    ,BSIK.LZBKZ
    ,BSIK.LANDL
    ,BSIK.IMKEY
    ,BSIK.FISTL
    ,BSIK.GEBER
    ,BSIK.DABRZ
    ,BSIK.XNEGP
    ,BSIK.KOSTL
    ,BSIK.EMPFB
    ,BSIK.PRCTR
    ,BSIK.XREF3
    ,BSIK.QSSKZ
    ,BSIK.ZINKZ
    ,BSIK.DTWS1
    ,BSIK.DTWS2
    ,BSIK.DTWS3
    ,BSIK.DTWS4
    ,BSIK.XPYPR
    ,BSIK.KIDNO
    ,BSIK.PYCUR
    ,BSIK.PYAMT
    ,BSIK.BUPLA
    ,BSIK.SECCO
    ,BSIK.PPDIFF
    ,BSIK.PPDIF2
    ,BSIK.PPDIF3
    ,BSIK.KBLNR
    ,BSIK.KBLPOS
    ,BSIK.GRANT_NBR
    ,BSIK.GMVKZ
    ,BSIK.SRTYPE
    ,BSIK.LOTKZ
    ,BSIK.FKBER
    ,BSIK.INTRENO
    ,BSIK.PPRCT
    ,BSIK.BUZID
    ,BSIK.AUGGJ
    ,BSIK.HKTID
    ,BSIK.BUDGET_PD
    ,BSIK.KONTT
    ,BSIK.KONTL
    ,BSIK.UEBGDAT
    ,BSIK.VNAME
    ,BSIK.EGRUP
    ,BSIK.BTYPE
    --  ,BSIK.OIEXGNUM
    --  ,BSIK.OINETCYC
    --  ,BSIK.OIEXGTYP
    ,BSIK.PROPMANO
    ,NULL AS KUNNR
    ,NULL AS ANFAE
    ,NULL AS VBELN
    ,NULL AS INFAE
    ,NULL AS XNOZA
    ,NULL AS WVERW
    ,NULL AS VBEL2
    ,NULL AS VPOS2
    ,NULL AS POSN2
    ,NULL AS ETEN2
    ,NULL AS RFZEI
    ,NULL AS KKBER
    ,NULL AS ABSBT
    ,NULL AS CCBTC
    ,NULL AS CESSION_KZ
    ,NULL AS PAYS_PROV
    ,NULL AS PAYS_TRAN
    ,NULL AS MNDID
    ,BSIK.LIFNR
    ,BSIK.EBELN
    ,BSIK.EBELP
    ,BSIK.ZOLLT
    ,BSIK.ZOLLD
    ,BSIK.DIEKZ
    ,BSIK.XESRD
    ,BSIK.QSSHB
    ,BSIK.QBSHB
    ,BSIK.QSZNR
    ,BSIK.QSFBT
    ,BSIK.LNRAN
    ,BSIK.KZBTR
    ,BSIK.ZEKKN
    ,BSIK.PENLC1
    ,BSIK.PENLC2
    ,BSIK.PENLC3
    ,BSIK.PENFC
    ,BSIK.PENDAYS
    ,BSIK.PENRC
    ,_CELONIS_CHANGE_DATE AS _CELONIS_CHANGE_DATE
FROM BSIK
);

DROP TABLE IF EXISTS BSEG;
 
CREATE TABLE BSEG AS(
SELECT
    BSEG.*,
    ROW_NUMBER()
        OVER(PARTITION BY BSEG.MANDT, BSEG.BUKRS, BSEG.BELNR, BSEG.GJAHR, BSEG.BUZEI
            ORDER BY BSEG.MANDT, BSEG.BUKRS, BSEG.BELNR, BSEG.GJAHR, BSEG.BUZEI, _CELONIS_CHANGE_DATE DESC) AS NUM
FROM
    BSEG_UNION AS BSEG
);
 
DELETE FROM BSEG WHERE NUM > 1;
ALTER TABLE BSEG DROP COLUMN NUM;
 
DROP VIEW IF EXISTS BSEG_UNION;

SELECT ANALYZE_STATISTICS ('BSEG'); 
