DROP TABLE IF EXISTS TMP_P2P_BKPF_BSEG;

CREATE TABLE TMP_P2P_BKPF_BSEG AS (
SELECT
    BSEG.MANDT
    ,BSEG.BUKRS
    ,BSEG.BELNR
  	,CAST(BSEG.BLDAT AS DATE) AS BLDAT
  	,CAST(BSEG.BUDAT AS DATE) AS BUDAT
  	,BSEG.ZLSCH
  	,BSEG.ZLSPR
  	,BSEG.ZBD1T
 	,BSEG.ZBD2T
  	,BSEG.ZFBDT
  	,BSEG.ZBD3T
    ,BSEG.GJAHR
  	,BSEG.BUZEI
    ,BKPF.AWKEY
    ,BSEG.AUGBL
    ,BSEG.AUGDT
    ,CAST(BSEG.CPUDT AS DATE) AS CPUDT
	,CAST(BKPF.CPUTM AS TIME) AS CPUTM
    ,BKPF.TCODE
    ,BKPF.USNAM
    ,BSEG.MANDT || BSEG.BUKRS || BSEG.BELNR || BSEG.GJAHR || BSEG.BUZEI AS TABKEY_BSEG
    ,BSEG.MANDT || BSEG.BUKRS || BSEG.BELNR || BSEG.GJAHR AS TABKEY_BKPF
  	,BSEG.ZTERM
  	,BSEG.AUGGJ
FROM 
    BKPF AS BKPF
    JOIN BSEG AS BSEG ON 1=1
    	AND BKPF.MANDT = BSEG.MANDT
    	AND BKPF.BUKRS = BSEG.BUKRS
    	AND BKPF.GJAHR = BSEG.GJAHR 
    	AND BKPF.BELNR = BSEG.BELNR
WHERE 1=1
     AND BSEG.BSCHL = '<%=postingKeyInvoice%>' -- data pool parameter, standard is 31 for vendor invoice
);

SELECT ANALYZE_STATISTICS ('TMP_P2P_BKPF_BSEG'); 
