DROP TABLE IF EXISTS TMP_EBAN;

CREATE TABLE TMP_EBAN AS (
    SELECT
        EBAN.MANDT
        ,EBAN.BANFN
        ,EBAN.BNFPO
        ,EBAN.BADAT
        ,EBAN.ERNAM
        ,EBAN.MANDT || EBAN.BANFN || EBAN.BNFPO AS TABKEY_EBAN
    FROM EBAN
    WHERE EXISTS(SELECT * FROM TMP_P2P_EKKO_EKPO AS E
        WHERE 1=1
        AND EBAN.MANDT = E.MANDT 
        AND EBAN.BANFN = E.BANFN 
        AND EBAN.BNFPO = E.BNFPO)
    AND EBAN.EBELN IS NOT NULL
);

SELECT ANALYZE_STATISTICS ('TMP_EBAN'); 
