-- Query 1
DROP TABLE IF EXISTS TMP_P2P_RSEG_EKKO_EKPO;

-- Query 2
CREATE TABLE TMP_P2P_RSEG_EKKO_EKPO AS 
SELECT 
   E._CASE_KEY
   ,E.MANDT 
   ,E.EBELN
   ,E.EBELP 
   ,R.BELNR 
   ,R.GJAHR 
FROM 
    RSEG AS R
    INNER JOIN TMP_P2P_EKKO_EKPO AS E ON 1=1
        AND R.MANDT = E.MANDT
        AND R.EBELN = E.EBELN
        AND R.EBELP = E.EBELP
        ;

SELECT ANALYZE_STATISTICS ('TMP_P2P_RSEG_EKKO_EKPO'); 

