INSERT INTO _CEL_P2P_EKES_ACTIVITIES(
    _CASE_KEY
    ,MANDT
	,EBELN
	,EBELP
    ,ACTIVITY_DE
    ,ACTIVITY_EN
    ,EVENTTIME
    ,_SORTING
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY) 

SELECT
	E._CASE_KEY AS _CASE_KEY
	,E.MANDT AS MANDT
	,E.EBELN AS EBELN
	,E.EBELP AS EBELP
	,'Erhalte Lieferavis' AS ACTIVITY_DE
	,'Receive advanced shipment notice (ASN)' AS ACTIVITY_EN
	,CAST(EKES.ERDAT AS DATE) + CAST(EKES.EZEIT AS TIME) AS EVENTTIME
	,1700 AS _SORTING
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,E.MANDT || E.EBELN || E.EBELP || EKES.ETENS AS _ACTIVITY_KEY
FROM
	TMP_P2P_EKKO_EKPO AS E
	INNER JOIN EKES AS EKES ON
		 EKES.MANDT = E.MANDT
        AND EKES.EBELN = E.EBELN
        AND EKES.EBELP = E.EBELP
        AND EKES.EBTYP LIKE 'L%'
;

