DROP TABLE IF EXISTS P2P_BKPF_STAGING;

CREATE TABLE P2P_BKPF_STAGING AS 
SELECT DISTINCT
    BKPF.MANDT,
    BKPF.BUKRS,
    BKPF.BELNR,
    BKPF.GJAHR,
    CAST(BKPF.BLDAT AS DATE) AS TS_BLDAT, 
    CAST(BKPF.BUDAT AS DATE) AS TS_BUDAT, 
    CAST(BKPF.CPUDT AS DATE) AS TS_CPUDT,
    CAST(BKPF.CPUDT AS DATE) + CAST(BKPF.CPUTM AS TIME) AS TS_CPUDT_CPUTM,
    CAST(BKPF.AEDAT AS DATE) AS TS_AEDAT, 
    CAST(BKPF.UPDDT AS DATE) AS TS_UPDDT, 
    CAST(BKPF.WWERT AS DATE) AS TS_WWERT, 
    CAST(BKPF.STODT AS DATE) AS TS_STODT, 
    CAST(BKPF.REINDAT AS DATE) AS TS_REINDAT, 
    CAST(BKPF.VATDATE AS DATE) AS TS_VATDATE, 
    CAST(BKPF.INTDATE AS DATE) AS TS_INTDATE, 
    CAST(BKPF.PSOBT AS DATE) AS TS_PSOBT, 
    CAST(BKPF.PSODT AS DATE) AS TS_PSODT, 
    CAST(BKPF.PSODT AS DATE) + CAST(BKPF.PSOTM AS TIME) AS TS_PSODT_PSOTM,
    CAST(BKPF.OFFSET_REFER_DAT AS DATE) AS TS_OFFSET_REFER_DAT, 
    SUBSTRING(BKPF.AWKEY,1,14) AS RBKPKEY -- Join to MM (RBKP)
FROM    
	BKPF AS BKPF
    INNER JOIN TMP_P2P_RSEG_EKKO_EKPO AS RE ON 1=1
        AND BKPF.MANDT = RE.MANDT
		AND SUBSTRING(BKPF.AWKEY,1,14) = RE.BELNR || CAST(RE.GJAHR AS VARCHAR(4))
;

SELECT ANALYZE_STATISTICS ('P2P_BKPF_STAGING'); 

