DROP TABLE IF EXISTS P2P_EBAN_STAGING;


CREATE TABLE P2P_EBAN_STAGING AS (
SELECT 
    EBAN.MANDT
    ,EBAN.BANFN
    ,EBAN.BNFPO
    ,EBAN.BADAT
    ,EBAN.ERNAM
    ,EBAN.EBELN
    ,EBAN.LIFNR
    ,EBAN.EKORG
    ,EBAN.WAERS
    ,EBAN.WERKS
    ,EBAN.MATNR
    ,EBAN.KONNR
    ,EBAN.MANDT || EBAN.BANFN || EBAN.BNFPO AS TABKEY_EBAN
	,CAST(EBAN.BADAT AS DATE) AS TS_BADAT
    ,CAST(EBAN.BEDAT AS DATE) AS TS_BEDAT
    ,CAST(EBAN.BVDAT AS DATE) AS TS_BVDAT
    ,CAST(EBAN.DAT01 AS DATE) AS TS_DAT01
    ,EBAN.ERDAT AS TS_ERDAT
    ,CAST(EBAN.FRGDT AS DATE) AS TS_FRGDT
    ,CAST(EBAN.LFDAT AS DATE) AS TS_LFDAT
    ,IFNULL(DD07T.DDTEXT,'') AS ESTKZ_TEXT
    ,IFNULL(DD07T_EBAN_STATU.DDTEXT,'') AS STATU_TEXT
    ,COALESCE(T161T.BATXT,DD07T_EBAN_BSTYP.DDTEXT) AS BSTYP_TEXT
    ,IFNULL(T161T.BATXT,'') AS BSTYP_TEXT1
    ,IFNULL(T163Y.EPSTP,'') AS PSTYP_TEXT2
    ,IFNULL(T163Y.PTEXT,'') AS PSTYP_TEXT
    ,IFNULL(T163Y.PTEXT,'') AS PSTYP_TEXT3
    ,T024E.EKOTX AS EKORG_TEXT
    ,T024.EKNAM AS EKGRP_TEXT
    ,T001W.NAME1 AS WERKS_TEXT
    ,MAKT.MAKTX AS MATNR_TEXT
    ,T023T.WGBEZ AS MATKL_TEXT
	,CASE 
	    WHEN EBAN.WAERS = '<%=currency%>' THEN EBAN.PREIS*EBAN.MENGE*ISNULL(TCURX_NETWR.TDEC,1) 
		WHEN TCURR_CC_NETWR.UKURS < 0 THEN (EBAN.PREIS*EBAN.MENGE*ISNULL(TCURX_NETWR.TDEC,1))*(1/ABS(TCURR_CC_NETWR.UKURS)/(CASE WHEN COALESCE(TCURF_CC_NETWR.FFACT, TCURR_CC_NETWR.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_NETWR.FFACT, TCURR_CC_NETWR.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC_NETWR.TFACT, TCURR_CC_NETWR.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_NETWR.TFACT, TCURR_CC_NETWR.TFACT) END)
  		WHEN TCURR_CC_NETWR.UKURS > 0 THEN (EBAN.PREIS*EBAN.MENGE*ISNULL(TCURX_NETWR.TDEC,1))*(TCURR_CC_NETWR.UKURS/CASE WHEN COALESCE(TCURF_CC_NETWR.FFACT, TCURR_CC_NETWR.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_NETWR.FFACT, TCURR_CC_NETWR.FFACT) END*CASE WHEN COALESCE(TCURF_CC_NETWR.TFACT, TCURR_CC_NETWR.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_NETWR.TFACT, TCURR_CC_NETWR.TFACT) END)
	END AS NETWR_CONVERTED 
    ,EBAN.MANDT || EBAN.BANFN || EBAN.BNFPO AS CONCATKEY
    , ADR6.SMTP_ADDR AS SMTP_ADDR_ERNAM
    , T16FT.FRGXT AS FRGGR_TEXT
    , COALESCE(ADRP.NAME_TEXT, EBAN.ERNAM) AS REQUISITIONER_NAME
    , T16FS.FRGC1
    , (CASE WHEN T16FW_1.OTYPE != 'US' THEN HRP1000_1.STEXT WHEN T16FW_1.OTYPE = 'US' THEN T16FW_1.OBJID WHEN T16FS.FRGC1 IS NULL THEN NULL ELSE T16FT.FRGXT END) AS FRGC1_APPROVER  
    , T16FS.FRGC2
    , (CASE WHEN T16FW_2.OTYPE != 'US' THEN HRP1000_2.STEXT WHEN T16FW_2.OTYPE = 'US' THEN T16FW_2.OBJID WHEN T16FS.FRGC2 IS NULL THEN NULL ELSE T16FT.FRGXT END) AS FRGC2_APPROVER  
    , T16FS.FRGC3
    , (CASE WHEN T16FW_3.OTYPE != 'US' THEN HRP1000_3.STEXT WHEN T16FW_3.OTYPE = 'US' THEN T16FW_3.OBJID WHEN T16FS.FRGC3 IS NULL THEN NULL ELSE T16FT.FRGXT END) AS FRGC3_APPROVER  
    , T16FS.FRGC4
    , (CASE WHEN T16FW_4.OTYPE != 'US' THEN HRP1000_4.STEXT WHEN T16FW_4.OTYPE = 'US' THEN T16FW_4.OBJID WHEN T16FS.FRGC4 IS NULL THEN NULL ELSE T16FT.FRGXT END) AS FRGC4_APPROVER  
    , T16FS.FRGC5
    , (CASE WHEN T16FW_5.OTYPE != 'US' THEN HRP1000_5.STEXT WHEN T16FW_5.OTYPE = 'US' THEN T16FW_5.OBJID WHEN T16FS.FRGC5 IS NULL THEN NULL ELSE T16FT.FRGXT END) AS FRGC5_APPROVER  
    , T16FS.FRGC6
    , (CASE WHEN T16FW_6.OTYPE != 'US' THEN HRP1000_6.STEXT WHEN T16FW_6.OTYPE = 'US' THEN T16FW_6.OBJID WHEN T16FS.FRGC6 IS NULL THEN NULL ELSE T16FT.FRGXT END) AS FRGC6_APPROVER  
    , T16FS.FRGC7
    , (CASE WHEN T16FW_7.OTYPE != 'US' THEN HRP1000_7.STEXT WHEN T16FW_7.OTYPE = 'US' THEN T16FW_7.OBJID WHEN T16FS.FRGC7 IS NULL THEN NULL ELSE T16FT.FRGXT END) AS FRGC7_APPROVER  
    , T16FS.FRGC8
    , (CASE WHEN T16FW_8.OTYPE != 'US' THEN HRP1000_8.STEXT WHEN T16FW_8.OTYPE = 'US' THEN T16FW_8.OBJID WHEN T16FS.FRGC8 IS NULL THEN NULL ELSE T16FT.FRGXT END) AS FRGC8_APPROVER  
    , EBAN.MANDT || ISNULL(EBAN.EKORG, '-') ||  ISNULL(EBAN.WAERS, '-')  AS P2P_CONTRACT_RECOMMENDATION_KEY
FROM 
    EBAN AS EBAN
    LEFT JOIN T024E AS T024E ON 1=1 
        AND EBAN.MANDT = T024E.MANDT
		AND EBAN.EKORG = T024E.EKORG
	LEFT JOIN T024 AS T024 ON 1=1 
		AND EBAN.MANDT = T024.MANDT
		AND EBAN.EKGRP = T024.EKGRP
	LEFT JOIN T001W AS T001W ON 1=1
		AND EBAN.MANDT = T001W.MANDT
		AND EBAN.WERKS = T001W.WERKS
	LEFT JOIN MAKT AS MAKT ON 1=1 
		AND EBAN.MANDT = MAKT.MANDT
		AND EBAN.MATNR = MAKT.MATNR
		AND MAKT.SPRAS = '<%=primaryLanguageKey%>' 
	LEFT JOIN T023T AS T023T ON 1=1 
		AND EBAN.MANDT = T023T.MANDT
		AND EBAN.MATKL = T023T.MATKL
		AND T023T.SPRAS = '<%=primaryLanguageKey%>' 
	LEFT JOIN T161T AS T161T ON 1=1 
        AND EBAN.MANDT = T161T.MANDT
        AND EBAN.BSART = T161T.BSART
        AND EBAN.BSTYP = T161T.BSTYP
        AND T161T.SPRAS = '<%=primaryLanguageKey%>' 
    LEFT JOIN DD07T AS DD07T_EBAN_BSTYP ON 1=1 
        AND EBAN.BSTYP = DD07T_EBAN_BSTYP.DOMVALUE_L
        AND DD07T_EBAN_BSTYP.DOMNAME = 'EBSTYP'
        AND DD07T_EBAN_BSTYP.DDLANGUAGE = '<%=primaryLanguageKey%>' 
    LEFT JOIN T163Y AS T163Y ON 1=1 
        AND EBAN.MANDT = T163Y.MANDT
        AND EBAN.PSTYP = T163Y.PSTYP
        AND T163Y.SPRAS = '<%=primaryLanguageKey%>' 
    LEFT JOIN DD07T  AS DD07T ON 1=1 
        AND EBAN.ESTKZ = DD07T.DOMVALUE_L
        AND DD07T.DOMNAME = 'ESTKZ'
        AND DD07T.DDLANGUAGE = '<%=primaryLanguageKey%>' 
    LEFT JOIN DD07T AS DD07T_EBAN_STATU ON 1=1
        AND DD07T_EBAN_STATU.DOMVALUE_L = EBAN.STATU
        AND DD07T_EBAN_STATU.DDLANGUAGE = '<%=primaryLanguageKey%>'
        AND DD07T_EBAN_STATU.DOMNAME = 'ASTAT'
    LEFT JOIN USR02 ON 1=1
        and EBAN.MANDT = USR02.MANDT
        and EBAN.ERNAM = USR02.BNAME
    LEFT JOIN USR21 AS USR21 ON 1=1  
        AND EBAN.MANDT = USR21.MANDT
        AND EBAN.ERNAM = USR21.BNAME   
    LEFT JOIN ADR6 AS ADR6 ON 1=1
        AND USR21.MANDT = ADR6.CLIENT
        AND USR21.PERSNUMBER = ADR6.PERSNUMBER
    LEFT JOIN T16FT ON 1=1
        AND EBAN.MANDT = T16FT.MANDT
        AND EBAN.FRGGR = T16FT.FRGGR
        AND EBAN.FRGST = T16FT.FRGSX
        AND T16FT.SPRAS = '<%=primaryLanguageKey%>'
    LEFT JOIN ADRP AS ADRP ON 1=1
        AND USR21.PERSNUMBER = ADRP.PERSNUMBER
        AND USR21.MANDT = ADRP.CLIENT
    LEFT JOIN T16FS ON 1=1 
        AND EBAN.MANDT = T16FS.MANDT
        AND EBAN.FRGGR = T16FS.FRGGR 
        AND EBAN.FRGST = T16FS.FRGSX
    LEFT JOIN T16FW AS T16FW_1 ON 1=1
        AND T16FS.MANDT = T16FW_1.MANDT
        AND T16FS.FRGGR = T16FW_1.FRGGR
        AND T16FS.FRGC1 = T16FW_1.FRGCO
        AND EBAN.WERKS = T16FW_1.WERKS
    LEFT JOIN T16FW AS T16FW_2 ON 1=1
        AND T16FS.MANDT = T16FW_2.MANDT
        AND T16FS.FRGGR = T16FW_2.FRGGR
        AND T16FS.FRGC2 = T16FW_2.FRGCO
        AND EBAN.WERKS = T16FW_2.WERKS
    LEFT JOIN T16FW AS T16FW_3 ON 1=1
        AND T16FS.MANDT = T16FW_3.MANDT
        AND T16FS.FRGGR = T16FW_3.FRGGR
        AND T16FS.FRGC3 = T16FW_3.FRGCO
        AND EBAN.WERKS = T16FW_3.WERKS
    LEFT JOIN T16FW AS T16FW_4 ON 1=1
        AND T16FS.MANDT = T16FW_4.MANDT
        AND T16FS.FRGGR = T16FW_4.FRGGR
        AND T16FS.FRGC4 = T16FW_4.FRGCO
        AND EBAN.WERKS = T16FW_4.WERKS
    LEFT JOIN T16FW AS T16FW_5 ON 1=1
        AND T16FS.MANDT = T16FW_5.MANDT
        AND T16FS.FRGGR = T16FW_5.FRGGR
        AND T16FS.FRGC5 = T16FW_5.FRGCO
        AND EBAN.WERKS = T16FW_5.WERKS
    LEFT JOIN T16FW AS T16FW_6 ON 1=1
        AND T16FS.MANDT = T16FW_6.MANDT
        AND T16FS.FRGGR = T16FW_6.FRGGR
        AND T16FS.FRGC6 = T16FW_6.FRGCO
        AND EBAN.WERKS = T16FW_6.WERKS
    LEFT JOIN T16FW AS T16FW_7 ON 1=1
        AND T16FS.MANDT = T16FW_7.MANDT
        AND T16FS.FRGGR = T16FW_7.FRGGR
        AND T16FS.FRGC7 = T16FW_7.FRGCO
        AND EBAN.WERKS = T16FW_7.WERKS
    LEFT JOIN T16FW AS T16FW_8 ON 1=1
        AND T16FS.MANDT = T16FW_8.MANDT
        AND T16FS.FRGGR = T16FW_8.FRGGR
        AND T16FS.FRGC8 = T16FW_8.FRGCO
        AND EBAN.WERKS = T16FW_8.WERKS
    LEFT JOIN HRP1000 AS HRP1000_1 ON 1=1
        AND T16FW_1.MANDT = HRP1000_1.MANDT
        AND T16FW_1.OBJID = HRP1000_1.OBJID
        AND T16FW_1.OTYPE = HRP1000_1.OTYPE
        AND HRP1000_1.LANGU = '<%=primaryLanguageKey%>'
        AND HRP1000_1.PLVAR = '01'
    LEFT JOIN HRP1000 AS HRP1000_2 ON 1=1
        AND T16FW_2.MANDT = HRP1000_2.MANDT
        AND T16FW_2.OBJID = HRP1000_2.OBJID
        AND T16FW_2.OTYPE = HRP1000_2.OTYPE
        AND HRP1000_2.LANGU = '<%=primaryLanguageKey%>'
        AND HRP1000_2.PLVAR = '01'
    LEFT JOIN HRP1000 AS HRP1000_3 ON 1=1
        AND T16FW_3.MANDT = HRP1000_3.MANDT
        AND T16FW_3.OBJID = HRP1000_3.OBJID
        AND T16FW_3.OTYPE = HRP1000_3.OTYPE
        AND HRP1000_3.LANGU = '<%=primaryLanguageKey%>'
        AND HRP1000_3.PLVAR = '01'
    LEFT JOIN HRP1000 AS HRP1000_4 ON 1=1
        AND T16FW_4.MANDT = HRP1000_4.MANDT
        AND T16FW_4.OBJID = HRP1000_4.OBJID
        AND T16FW_4.OTYPE = HRP1000_4.OTYPE
        AND HRP1000_4.LANGU = '<%=primaryLanguageKey%>'
        AND HRP1000_4.PLVAR = '01'
    LEFT JOIN HRP1000 AS HRP1000_5 ON 1=1
        AND T16FW_5.MANDT = HRP1000_5.MANDT
        AND T16FW_5.OBJID = HRP1000_5.OBJID
        AND T16FW_5.OTYPE = HRP1000_5.OTYPE
        AND HRP1000_5.LANGU = '<%=primaryLanguageKey%>'
        AND HRP1000_5.PLVAR = '01'
    LEFT JOIN HRP1000 AS HRP1000_6 ON 1=1
        AND T16FW_6.MANDT = HRP1000_6.MANDT
        AND T16FW_6.OBJID = HRP1000_6.OBJID
        AND T16FW_6.OTYPE = HRP1000_6.OTYPE
        AND HRP1000_6.LANGU = '<%=primaryLanguageKey%>'
        AND HRP1000_6.PLVAR = '01'
    LEFT JOIN HRP1000 AS HRP1000_7 ON 1=1
        AND T16FW_7.MANDT = HRP1000_7.MANDT
        AND T16FW_7.OBJID = HRP1000_7.OBJID
        AND T16FW_7.OTYPE = HRP1000_7.OTYPE
        AND HRP1000_7.LANGU = '<%=primaryLanguageKey%>'
        AND HRP1000_7.PLVAR = '01'
    LEFT JOIN HRP1000 AS HRP1000_8 ON 1=1
        AND T16FW_8.MANDT = HRP1000_8.MANDT
        AND T16FW_8.OBJID = HRP1000_8.OBJID
        AND T16FW_8.OTYPE = HRP1000_8.OTYPE
        AND HRP1000_8.LANGU = '<%=primaryLanguageKey%>'
        AND HRP1000_8.PLVAR = '01'
    LEFT JOIN P2P_TCURR_CC AS TCURR_CC_NETWR ON 1=1 -- NETWR in EBAN
	    AND TCURR_CC_NETWR.MANDT = EBAN.MANDT
	    AND TCURR_CC_NETWR.TCURR = '<%=currency%>'
		AND TCURR_CC_NETWR.FCURR = EBAN.WAERS
		AND TCURR_CC_NETWR.KURST = '<%=exchangeRateType%>'
		AND EBAN.ERDAT >= TCURR_CC_NETWR.VALID_START AND EBAN.ERDAT < TCURR_CC_NETWR.VALID_END
	LEFT JOIN P2P_TCURF_CC AS TCURF_CC_NETWR ON 1=1
	    AND TCURR_CC_NETWR.MANDT = TCURF_CC_NETWR.MANDT
		AND TCURR_CC_NETWR.TCURR = TCURF_CC_NETWR.TCURR
		AND TCURR_CC_NETWR.FCURR = TCURF_CC_NETWR.FCURR
		AND TCURR_CC_NETWR.KURST = TCURF_CC_NETWR.KURST
        AND EBAN.ERDAT  >= TCURF_CC_NETWR.VALID_START AND EBAN.ERDAT < TCURF_CC_NETWR.VALID_END
	LEFT JOIN (
		SELECT 
		    TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
		    TCURX) AS TCURX_NETWR ON 1=1
		AND TCURR_CC_NETWR.FCURR = TCURX_NETWR.CURRKEY
        ) ;

SELECT ANALYZE_STATISTICS ('P2P_EBAN_STAGING'); 

