DROP VIEW IF EXISTS P2P_EBAN;

CREATE VIEW P2P_EBAN AS (
SELECT 
    EBAN.*,
	P2P_EBAN_STAGING.TS_BADAT,
    P2P_EBAN_STAGING.TS_BEDAT,
    P2P_EBAN_STAGING.TS_BVDAT,
    P2P_EBAN_STAGING.TS_DAT01,
    P2P_EBAN_STAGING.TS_ERDAT,
    P2P_EBAN_STAGING.TS_FRGDT,
    P2P_EBAN_STAGING.TS_LFDAT,
    P2P_EBAN_STAGING.ESTKZ_TEXT,
    P2P_EBAN_STAGING.STATU_TEXT,
    P2P_EBAN_STAGING.BSTYP_TEXT,
    P2P_EBAN_STAGING.BSTYP_TEXT1,
    P2P_EBAN_STAGING.PSTYP_TEXT,
    P2P_EBAN_STAGING.PSTYP_TEXT2,
    P2P_EBAN_STAGING.PSTYP_TEXT3,
    P2P_EBAN_STAGING.EKORG_TEXT,
    P2P_EBAN_STAGING.EKGRP_TEXT,
    P2P_EBAN_STAGING.WERKS_TEXT,
    P2P_EBAN_STAGING.MATNR_TEXT,
    P2P_EBAN_STAGING.MATKL_TEXT,
    P2P_EBAN_STAGING.NETWR_CONVERTED,
    P2P_EBAN_STAGING.CONCATKEY,
    P2P_EBAN_STAGING.SMTP_ADDR_ERNAM,
    P2P_EBAN_STAGING.FRGGR_TEXT,
    P2P_EBAN_STAGING.REQUISITIONER_NAME,
    P2P_EBAN_STAGING.FRGC1,
    P2P_EBAN_STAGING.FRGC1_APPROVER  ,
    P2P_EBAN_STAGING.FRGC2,
    P2P_EBAN_STAGING.FRGC2_APPROVER  ,
    P2P_EBAN_STAGING.FRGC3,
    P2P_EBAN_STAGING.FRGC3_APPROVER  ,
    P2P_EBAN_STAGING.FRGC4,
    P2P_EBAN_STAGING.FRGC4_APPROVER  ,
    P2P_EBAN_STAGING.FRGC5,
    P2P_EBAN_STAGING.FRGC5_APPROVER  ,
    P2P_EBAN_STAGING.FRGC6,
    P2P_EBAN_STAGING.FRGC6_APPROVER ,
    P2P_EBAN_STAGING.FRGC7,
    P2P_EBAN_STAGING.FRGC7_APPROVER,
    P2P_EBAN_STAGING.FRGC8,
    P2P_EBAN_STAGING.FRGC8_APPROVER  ,
    P2P_EBAN_STAGING.P2P_CONTRACT_RECOMMENDATION_KEY,
    P2P_EBAN_STAGING.EPOCH
FROM 
    EBAN AS EBAN JOIN 
    P2P_EBAN_STAGING ON 1=1
     AND EBAN.MANDT = P2P_EBAN_STAGING.MANDT
     AND EBAN.BANFN = P2P_EBAN_STAGING.BANFN
      AND EBAN.BNFPO = P2P_EBAN_STAGING.BNFPO
) ;
