DROP TABLE IF EXISTS P2P_EKBE_STAGING;

CREATE TABLE P2P_EKBE_STAGING AS (
SELECT 
    EKBE.MANDT,
    EKBE.EBELN,
    EKBE.EBELP,
    EKBE.ZEKKN,
    EKBE.VGABE,
    EKBE.GJAHR,
    EKBE.BELNR,
    EKBE.BUZEI,
    CAST(EKBE.BLDAT AS DATE) AS TS_BLDAT,
    CAST(EKBE.BUDAT AS DATE) AS TS_BUDAT,
    CAST(EKBE.CPUDT AS DATE) AS TS_CPUDT,
    CAST(EKBE.CPUTM AS DATETIME) AS TS_CPUTM
FROM 
    EKBE
WHERE EXISTS(
    SELECT * 
    FROM TMP_P2P_EKKO_EKPO AS C
    WHERE 1=1
        AND EKBE.MANDT = C.MANDT
        AND EKBE.EBELN = C.EBELN
        AND EKBE.EBELP = C.EBELP)
);

SELECT ANALYZE_STATISTICS ('P2P_EKBE_STAGING'); 

