DROP VIEW IF EXISTS P2P_EKBE;

CREATE VIEW P2P_EKBE AS (
SELECT 
    EKBE.*,
    P2P_EKBE_STAGING.TS_BLDAT,
    P2P_EKBE_STAGING.TS_BUDAT,
    P2P_EKBE_STAGING.TS_CPUDT,
    P2P_EKBE_STAGING.TS_CPUTM,
    P2P_EKBE_STAGING.EPOCH
FROM 
    EKBE JOIN 
    P2P_EKBE_STAGING ON 1=1
        AND EKBE.MANDT=P2P_EKBE_STAGING.MANDT
        AND EKBE.EBELN=P2P_EKBE_STAGING.EBELN
        AND EKBE.EBELP=P2P_EKBE_STAGING.EBELP
        AND EKBE.ZEKKN=P2P_EKBE_STAGING.ZEKKN
        AND EKBE.VGABE=P2P_EKBE_STAGING.VGABE
        AND EKBE.GJAHR=P2P_EKBE_STAGING.GJAHR
        AND EKBE.BELNR=P2P_EKBE_STAGING.BELNR
        AND EKBE.BUZEI=P2P_EKBE_STAGING.BUZEI
);
