DROP VIEW IF EXISTS P2P_EINE;

CREATE VIEW P2P_EINE AS (
SELECT 
    EINE.*
    ,P2P_EINE_STAGING.UMREN
    ,P2P_EINE_STAGING.UMREZ
    ,P2P_EINE_STAGING.LIFNR
    ,P2P_EINE_STAGING.MATNR
    ,P2P_EINE_STAGING.MATNR_TEXT
    ,P2P_EINE_STAGING.MATKL
    ,P2P_EINE_STAGING.MATKL_TEXT
    ,P2P_EINE_STAGING.EINA_LOEKZ
    ,P2P_EINE_STAGING.MEINS
    ,P2P_EINE_STAGING.TS_ERDAT
    ,P2P_EINE_STAGING.TS_ANGDT
    ,P2P_EINE_STAGING.TS_AMODV
    ,P2P_EINE_STAGING.TS_AMODB
    ,P2P_EINE_STAGING.TS_DATLB
    ,P2P_EINE_STAGING.TS_PRDAT
    ,P2P_EINE_STAGING.EKORG_TEXT
    ,P2P_EINE_STAGING.WERKS_TEXT
    ,P2P_EINE_STAGING.EKGRP_TEXT
    ,P2P_EINE_STAGING.NETPR_CONVERTED
    ,P2P_EINE_STAGING.EPOCH

FROM 
    EINE AS EINE
    INNER JOIN P2P_EINE_STAGING  ON 1=1
	    AND EINE.MANDT = P2P_EINE_STAGING.MANDT
    	AND EINE.INFNR = P2P_EINE_STAGING.INFNR
        AND EINE.EKORG = P2P_EINE_STAGING.EKORG
        AND EINE.ESOKZ = P2P_EINE_STAGING.ESOKZ
        AND EINE.WERKS  <=> P2P_EINE_STAGING.WERKS 
)
;
