DROP VIEW IF EXISTS P2P_MARA;

CREATE VIEW P2P_MARA AS(
SELECT 
	MARA.*,
    CAST(MARA.ERSDA AS DATE) AS TS_ERSDA,
    CAST(MARA.LAEDA AS DATE) AS TS_LAEDA, 
    CAST(MARA.DATAB AS DATE) AS TS_DATAB, 
    CAST(MARA.LIQDT AS DATE) AS TS_LIQDT, 
    CAST(MARA.MSTDE AS DATE) AS TS_MSTDE, 
    CAST(MARA.MSTDV AS DATE) AS TS_MSTDV,
    MARA.EPOCH
FROM
	MARA
    LEFT JOIN T179T AS T179T on 1=1
	    AND T179T.MANDT = MARA.MANDT
	    AND T179T.SPRAS = '<%=primaryLanguageKey%>'
	    AND T179T.PRODH = MARA.PRDHA
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKPO_STAGING AS C 
    WHERE 1=1
     AND MARA.MANDT = C.MANDT 
     AND MARA.MATNR = C.MATNR)
);

