DROP VIEW IF EXISTS P2P_MARC;

CREATE VIEW P2P_MARC AS
SELECT
	MARC.*,
    EPOCH
FROM 
	MARC AS MARC
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKPO_STAGING AS C
    WHERE 1=1
    AND MARC.MANDT = C.MANDT 
    AND MARC.MATNR = C.MATNR 
    AND MARC.WERKS = C.WERKS)
;
