DROP TABLE IF EXISTS P2P_MSEG_STAGING;

CREATE TABLE P2P_MSEG_STAGING AS
SELECT 
	MSEG.MANDT,
    MSEG.MBLNR,
    MSEG.MJAHR,
    MSEG.ZEILE,
    CAST(MSEG.VFDAT AS DATE) AS TS_VFDAT,
    CAST(MSEG.DABRBZ AS DATE) AS TS_DABRBZ,
    CAST(MSEG.DABRZ AS DATE) AS TS_DABRZ,
    CAST(MSEG.HSDAT AS DATE) AS TS_HSDAT,
    CAST(MSEG.BUDAT_MKPF AS DATE) AS TS_BUDAT_MKPF,
    CAST(MSEG.CPUDT_MKPF AS DATE) AS TS_CPUDT_MKPF
FROM 
	MSEG AS MSEG
WHERE EXISTS(
    SELECT * 
    FROM EKPO AS C
    WHERE 1=1 
        AND MSEG.MANDT = C.MANDT
        AND MSEG.EBELN = C.EBELN
        AND MSEG.EBELP = C.EBELP)
;

SELECT ANALYZE_STATISTICS ('P2P_MSEG_STAGING'); 

