DROP VIEW IF EXISTS P2P_MSEG;

CREATE VIEW P2P_MSEG AS
SELECT 
	MSEG.*,
    CAST(MSEG.VFDAT AS DATE) AS TS_VFDAT,
    CAST(MSEG.DABRBZ AS DATE) AS TS_DABRBZ,
    CAST(MSEG.DABRZ AS DATE) AS TS_DABRZ,
    CAST(MSEG.HSDAT AS DATE) AS TS_HSDAT,
    CAST(MSEG.BUDAT_MKPF AS DATE) AS TS_BUDAT_MKPF,
    CAST(MSEG.CPUDT_MKPF AS DATE) AS TS_CPUDT_MKPF,
    P2P_MSEG_STAGING.EPOCH
FROM 
	MSEG AS MSEG
    JOIN P2P_MSEG_STAGING ON 1=1
        AND MSEG.MANDT=P2P_MSEG_STAGING.MANDT
        AND MSEG.MBLNR=P2P_MSEG_STAGING.MBLNR
        AND MSEG.MJAHR=P2P_MSEG_STAGING.MJAHR
        AND MSEG.ZEILE=P2P_MSEG_STAGING.ZEILE
;
