DROP VIEW IF EXISTS P2P_NAST;

CREATE VIEW P2P_NAST AS(
SELECT 
    NAST.*
    ,P2P_NAST_STAGING.NACHA_TEXT,
    P2P_NAST_STAGING.TS_ERDAT,
    P2P_NAST_STAGING.TS_VSDAT,
    P2P_NAST_STAGING.TS_DATVR,
    P2P_NAST_STAGING.TS_DATRE,
    P2P_NAST_STAGING.EPOCH
FROM 
    NAST JOIN 
    P2P_NAST_STAGING ON 1=1
        AND NAST.MANDT =P2P_NAST_STAGING.MANDT
        AND NAST.KAPPL =P2P_NAST_STAGING.KAPPL
        AND NAST.OBJKY =P2P_NAST_STAGING.OBJKY
        AND NAST.KSCHL =P2P_NAST_STAGING.KSCHL
        AND NAST.SPRAS =P2P_NAST_STAGING.SPRAS
        AND NAST.PARNR <=> P2P_NAST_STAGING.PARNR
        AND NAST.PARVW <=> P2P_NAST_STAGING.PARVW
        AND NAST.ERDAT =P2P_NAST_STAGING.ERDAT
        AND NAST.ERUHR =P2P_NAST_STAGING.ERUHR
);
