DROP VIEW IF EXISTS P2P_LFB1;

CREATE VIEW P2P_LFB1 AS(
SELECT 
	LFB1.*,
    CAST(LFB1.ERDAT AS DATE) AS TS_ERDAT,
    CAST(LFB1.ZINDT AS DATE) AS TS_ZINDT,
    CAST(LFB1.DATLZ AS DATE) AS TS_DATLZ,
    CAST(LFB1.QSZDT AS DATE) AS TS_QSZDT,
    CAST(LFB1.CERDT AS DATE) AS TS_CERDT,
    CAST(LFB1.UPDAT AS DATE) AS TS_UPDAT,
    EPOCH
FROM 
    LFB1
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKKO_STAGING AS C 
    WHERE 1=1
    AND LFB1.MANDT = C.MANDT 
    AND LFB1.LIFNR = C.LIFNR
    AND LFB1.BUKRS = C.BUKRS)
);

