DROP TABLE IF EXISTS P2P_QALS_STAGING;

CREATE TABLE P2P_QALS_STAGING AS (
SELECT 
    QALS.MANDANT,
    QALS.PRUEFLOS,
    CAST(QALS.ENSTEHDAT AS DATE) AS TS_ENSTEHDAT,
    CAST(QALS.ERSTELDAT AS DATE) AS TS_ERSTELDAT,
    CAST(QALS.AENDERDAT AS DATE) AS TS_AENDERDAT,
    CAST(QALS.PASTRTERM AS DATE) AS TS_PASTRTERM,
    CAST(QALS.PAENDTERM AS DATE) AS TS_PAENDTERM,
    CAST(QALS.GUELTIGAB AS DATE) AS TS_GUELTIGAB,
    CAST(QALS.ZEUGNISBIS AS DATE) AS TS_ZEUGNISBIS,
    CAST(QALS.VFDAT AS DATE) AS TS_VFDAT,
    CAST(QALS.BUDAT AS DATE) AS TS_BUDAT,
    CAST(QALS.DABRZ AS DATE) AS TS_DABRZ
FROM QALS
WHERE EXISTS (
    SELECT * 
    FROM TMP_P2P_EKKO_EKPO AS C 
    WHERE 1=1
		AND QALS.MANDANT = C.MANDT
		AND QALS.EBELN = C.EBELN
		AND QALS.EBELP = C.EBELP)
);

SELECT ANALYZE_STATISTICS ('P2P_QALS_STAGING'); 

