DROP TABLE IF EXISTS P2P_QAVE_STAGING;

CREATE TABLE P2P_QAVE_STAGING AS (
SELECT 
    QAVE.MANDANT,
    QAVE.PRUEFLOS,
    QAVE.KZART,
    QAVE.ZAEHLER,
    CAST(QAVE.VDATUM AS DATE) AS TS_VDATUM,
    CAST(QAVE.VAEDATUM AS DATE) AS TS_VAEDATUM
FROM QAVE
	JOIN QALS AS QALS ON 1=1
		AND QAVE.MANDANT = QALS.MANDANT
		AND QAVE.PRUEFLOS = QALS.PRUEFLOS
WHERE EXISTS(
    SELECT * 
    FROM TMP_P2P_EKKO_EKPO AS C 
    WHERE 1=1 
		AND QALS.MANDANT = C.MANDT
		AND QALS.EBELN = C.EBELN
		AND QALS.EBELP = C.EBELP)
);

SELECT ANALYZE_STATISTICS ('P2P_QAVE_STAGING'); 


