DROP VIEW IF EXISTS P2P_QAVE;

CREATE VIEW P2P_QAVE AS (
SELECT 
    QAVE.*,
    P2P_QAVE_STAGING.TS_VDATUM,
    P2P_QAVE_STAGING.TS_VAEDATUM,
    P2P_QAVE_STAGING.EPOCH
FROM QAVE JOIN 
    P2P_QAVE_STAGING ON 1=1
        AND QAVE.MANDANT = P2P_QAVE_STAGING.MANDANT
        AND QAVE.PRUEFLOS = P2P_QAVE_STAGING.PRUEFLOS
        AND QAVE.KZART = P2P_QAVE_STAGING.KZART
        AND QAVE.ZAEHLER <=> P2P_QAVE_STAGING.ZAEHLER
);

