DROP VIEW IF EXISTS P2P_RSEG;

CREATE VIEW P2P_RSEG AS(
SELECT 
	RSEG.*,
    P2P_RSEG_STAGING.TS_RETDUEDT,
    P2P_RSEG_STAGING.EPOCH
FROM 
    RSEG JOIN 
    P2P_RSEG_STAGING ON 1=1
        AND RSEG.MANDT = P2P_RSEG_STAGING.MANDT
        AND RSEG.BELNR = P2P_RSEG_STAGING.BELNR
        AND RSEG.GJAHR = P2P_RSEG_STAGING.GJAHR
        AND RSEG.BUZEI = P2P_RSEG_STAGING.BUZEI
);

