DROP VIEW IF EXISTS P2P_RBKP;

CREATE VIEW P2P_RBKP AS(
SELECT  
	RBKP.*,
    P2P_RBKP_STAGING.TS_BLDAT,
    P2P_RBKP_STAGING.TS_BUDAT,
    P2P_RBKP_STAGING.TS_CPUDT,
    P2P_RBKP_STAGING.TS_ZFBDT,
    P2P_RBKP_STAGING.TS_VATDATE,
    P2P_RBKP_STAGING.TS_REINDAT,
    P2P_RBKP_STAGING.TS_FDTAG,
    P2P_RBKP_STAGING.TS_ASSIGN_NEXT_DATE,
    P2P_RBKP_STAGING.TS_ASSIGN_END_DATE,
    P2P_RBKP_STAGING.TS_WWERT,
    P2P_RBKP_STAGING.BKPFKEY, -- to join with FI (BKPF)
    P2P_RBKP_STAGING.EPOCH 
FROM 
    RBKP JOIN 
    P2P_RBKP_STAGING ON 1=1 
        AND RBKP.MANDT=P2P_RBKP_STAGING.MANDT
        AND RBKP.BELNR=P2P_RBKP_STAGING.BELNR
        AND RBKP.GJAHR=P2P_RBKP_STAGING.GJAHR  
);
