DROP VIEW IF EXISTS P2P_NAME_MAPPING_TABLES;

CREATE VIEW P2P_NAME_MAPPING_TABLES AS
SELECT
	DD02T.TABNAME AS TABLE_NAME,
	DD02T.DDLANGUAGE AS LANGUAGE,
	DD02T.DDTEXT AS PRETTY_NAME
FROM
	DD02T
	
UNION
 
SELECT
	'_CEL_P2P_ACTIVITIES',
	'D',
	'Aktivitäten'
	
UNION

SELECT
	'_CEL_P2P_ACTIVITIES',
	'E',
	'Activities'
;

----------------------------------
UPDATE _CEL_P2P_EKPO_ACTIVITIES AS ACT
SET CHANGED_TABLE_TEXT_EN = NM.PRETTY_NAME
FROM P2P_NAME_MAPPING_TABLES AS NM
WHERE 1=1
   AND ACT.CHANGED_TABLE = NM.TABLE_NAME
   AND NM."LANGUAGE" = 'E';

UPDATE _CEL_P2P_EKPO_ACTIVITIES AS ACT
SET CHANGED_TABLE_TEXT_DE = NM.PRETTY_NAME
FROM P2P_NAME_MAPPING_TABLES AS NM
WHERE 1=1
   AND ACT.CHANGED_TABLE = NM.TABLE_NAME
   AND NM."LANGUAGE" = 'D';
----------------------------------
UPDATE _CEL_P2P_CDHDR_ACTIVITIES AS ACT
SET CHANGED_TABLE_TEXT_EN = NM.PRETTY_NAME
FROM P2P_NAME_MAPPING_TABLES AS NM
WHERE 1=1
   AND ACT.CHANGED_TABLE = NM.TABLE_NAME
   AND NM."LANGUAGE" = 'E';

UPDATE _CEL_P2P_CDHDR_ACTIVITIES AS ACT
SET CHANGED_TABLE_TEXT_DE = NM.PRETTY_NAME
FROM P2P_NAME_MAPPING_TABLES AS NM
WHERE 1=1
   AND ACT.CHANGED_TABLE = NM.TABLE_NAME
   AND NM."LANGUAGE" = 'D';
