Description
Total Cycle Time for cases without at least 1 occurrence of selected undesired or at least 2 occurrence of a identical repeated activity
Unit ${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}

${UNIVERSAL_Variable_INPUT__TIMEAGGREGATION_RUNTIME} (
case
  when

                  PU_COUNT_DISTINCT(CASE_TABLE( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
                            ACTIVITY_COLUMN( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
                            ACTIVITY_COLUMN( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}) IN (  ${UNIVERSAL_Variable_INPUT__UNDESIREDACTIVITIES_RUNTIME})) = 0

            AND
          PU_COUNT (
    CASE_TABLE ( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME} ) ,
    FILTER_TO_NULL ( ACTIVITY_COLUMN ( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME} )) ,
    ACTIVITY_COLUMN ( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME} )
    in (
        ${UNIVERSAL_Variable_INPUT__REPEATEDACTIVITIES_RUNTIME}
    )
    AND INDEX_ACTIVITY_TYPE ( ACTIVITY_COLUMN ( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME} ) ) > 1
  )=0

  then
    CALC_THROUGHPUT
    (ALL_OCCURRENCE['Process Start'] TO ALL_OCCURRENCE['Process End'],
      REMAP_TIMESTAMPS(TIMESTAMP_COLUMN( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}) ,  MINUTES,       WEEKDAY_CALENDAR (${UNIVERSAL_Variable_INPUT__CALENDARWEEK_RUNTIME})))
      / (CASE WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'DAYS' THEN 1440 WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'HOURS' THEN 60 ELSE 1 END )
  else NULL
end )
