Description
Cycle Time between selected activities
Unit ${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}
Format ,.1f
Desired direction NONE

  CODE :

${UNIVERSAL_Variable_INPUT__TIMEAGGREGATION_RUNTIME} (
            REMAP_TIMESTAMPS (
      PU_${UNIVERSAL_Variable_INPUT__TOOCCURRENCESUBPROCESS_RUNTIME}(
  CASE_TABLE(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
  TIMESTAMP_COLUMN(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
  ACTIVITY_COLUMN(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}) = '${UNIVERSAL_Variable_INPUT__TOACTIVITYSUBPROCESS_RUNTIME}'
  ) , MINUTES,       WEEKDAY_CALENDAR (${UNIVERSAL_Variable_INPUT__CALENDARWEEK_RUNTIME}))
      / (CASE WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'DAYS' THEN 1440 WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'HOURS' THEN 60 ELSE 1 END )

  -

REMAP_TIMESTAMPS (
      PU_${UNIVERSAL_Variable_INPUT__FROMOCCURRENCESUBPROCESS_RUNTIME}(
  CASE_TABLE(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
  TIMESTAMP_COLUMN(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
  ACTIVITY_COLUMN(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}) = '${UNIVERSAL_Variable_INPUT__FROMACTIVITYSUBPROCESS_RUNTIME}'
  ) ,MINUTES,       WEEKDAY_CALENDAR (${UNIVERSAL_Variable_INPUT__CALENDARWEEK_RUNTIME}))
      / (CASE WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'DAYS' THEN 1440 WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'HOURS' THEN 60 ELSE 1 END )
    )
