Description
Cycle Time between 1st Activity and 1st occurrence of selected conversion activity
Unit ${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}
Format ,.1f
Desired direction NONE

${UNIVERSAL_Variable_INPUT__TIMEAGGREGATION_RUNTIME}(CASE


WHEN PU_COUNT ( CASE_TABLE ( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME} ) , ACTIVITY_COLUMN ( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME} ) , ACTIVITY_COLUMN ( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME} ) IN (${UNIVERSAL_Variable_INPUT__CONVERSIONACTIVITIES_RUNTIME} )) > 0 THEN
 REMAP_TIMESTAMPS (
PU_FIRST(
CASE_TABLE(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
TIMESTAMP_COLUMN(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
ACTIVITY_COLUMN(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME})  IN (${UNIVERSAL_Variable_INPUT__CONVERSIONACTIVITIES_RUNTIME} )
) , MINUTES,       WEEKDAY_CALENDAR (${UNIVERSAL_Variable_INPUT__CALENDARWEEK_RUNTIME})) / (CASE WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'DAYS' THEN 1440 WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'HOURS' THEN 60 ELSE 1 END )
-


REMAP_TIMESTAMPS (
PU_FIRST(
CASE_TABLE(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
 TIMESTAMP_COLUMN(${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME})
) ,MINUTES,       WEEKDAY_CALENDAR (${UNIVERSAL_Variable_INPUT__CALENDARWEEK_RUNTIME})) / (CASE WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'DAYS' THEN 1440 WHEN '${UNIVERSAL_Variable_INPUT__TIMESCALE_RUNTIME}' = 'HOURS' THEN 60 ELSE 1 END )
ELSE NULL
END)
