AVG(
  CASE
    WHEN
      PU_COUNT_DISTINCT(CASE_TABLE( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
                            ACTIVITY_COLUMN( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}),
                            ACTIVITY_COLUMN( ${UNIVERSAL_Variable_INPUT__ACTIVITYTABLE_RUNTIME}) IN (  ${UNIVERSAL_Variable_INPUT__UNDESIREDACTIVITIES_RUNTIME})) > 0
    THEN 1.0
    ELSE 0.0
    END
  )
