DROP VIEW IF EXISTS BKPF_UNION;

CREATE VIEW  BKPF_UNION AS(
SELECT * from BKPF_BSIK
UNION ALL
SELECT * from BKPF_BSAK
);

DROP TABLE IF EXISTS BKPF_TEST;
 
CREATE TABLE BKPF_TEST AS(
SELECT
    BKPF.*,
    ROW_NUMBER()
        OVER(PARTITION BY BKPF.MANDT, BKPF.BUKRS, BKPF.BELNR, BKPF.GJAHR
            ORDER BY BKPF.MANDT, BKPF.BUKRS, BKPF.BELNR, BKPF.GJAHR, _CELONIS_CHANGE_DATE DESC) AS NUM
FROM
    BKPF_UNION AS BKPF
)
UNSEGMENTED ALL NODES
;
 
DELETE FROM BKPF_TEST WHERE NUM > 1;
ALTER TABLE BKPF_TEST DROP COLUMN NUM;
 
DROP VIEW IF EXISTS BKPF_UNION;
