DROP TABLE IF EXISTS _CEL_P2P_EKPO_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_P2P_CDHDR_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_P2P_NAST_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_P2P_EKES_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_P2P_EKBE_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_P2P_QALS_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_P2P_QAVE_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_P2P_BSIK_ACTIVITIES;
DROP TABLE IF EXISTS _CEL_P2P_BSAK_ACTIVITIES;


CREATE TABLE _CEL_P2P_EKPO_ACTIVITIES (
    _CASE_KEY VARCHAR(50)
    ,ACTIVITY_EN VARCHAR(200)
    ,_ACTIVITY_KEY VARCHAR(50)
    ,MANDT VARCHAR(3)
    ,EBELN VARCHAR(10)
    ,EBELP VARCHAR(5)
    ,ACTIVITY_DE VARCHAR (300)
    ,EVENTTIME DATETIME
    ,_SORTING INT
    ,USER_NAME VARCHAR(100)
    ,USER_TYPE VARCHAR(10)
    ,CHANGED_TABLE VARCHAR(20)
    ,CHANGED_TABLE_TEXT_DE VARCHAR(200)
    ,CHANGED_TABLE_TEXT_EN VARCHAR(200)
    ,CHANGED_FIELD VARCHAR(20)
    ,CHANGED_FIELD_TEXT_DE VARCHAR(200)
    ,CHANGED_FIELD_TEXT_EN VARCHAR(200)
    ,CHANGED_FROM VARCHAR (50)
    ,CHANGED_TO VARCHAR(50)
    ,CHANGED_FROM_FLOAT FLOAT
    ,CHANGED_TO_FLOAT FLOAT
    ,CHANGE_NUMBER VARCHAR(50)
    ,TRANSACTION_CODE VARCHAR(20)
    ,_CELONIS_CHANGE_DATE DATETIME

)
ORDER BY 	
    _CASE_KEY 
 	,ACTIVITY_EN 
    ,_ACTIVITY_KEY
    ;


CREATE TABLE _CEL_P2P_CDHDR_ACTIVITIES LIKE _CEL_P2P_EKPO_ACTIVITIES including projections;
CREATE TABLE _CEL_P2P_NAST_ACTIVITIES LIKE _CEL_P2P_EKPO_ACTIVITIES including projections;
CREATE TABLE _CEL_P2P_EKES_ACTIVITIES LIKE _CEL_P2P_EKPO_ACTIVITIES including projections;
CREATE TABLE _CEL_P2P_EKBE_ACTIVITIES LIKE _CEL_P2P_EKPO_ACTIVITIES including projections;
CREATE TABLE _CEL_P2P_QALS_ACTIVITIES LIKE _CEL_P2P_EKPO_ACTIVITIES including projections;
CREATE TABLE _CEL_P2P_QAVE_ACTIVITIES LIKE _CEL_P2P_EKPO_ACTIVITIES including projections;
CREATE TABLE _CEL_P2P_BSIK_ACTIVITIES LIKE _CEL_P2P_EKPO_ACTIVITIES including projections;
CREATE TABLE _CEL_P2P_BSAK_ACTIVITIES LIKE _CEL_P2P_EKPO_ACTIVITIES including projections;



DROP VIEW IF EXISTS _CEL_P2P_BSEG_ACTIVITIES_UNION;

CREATE VIEW _CEL_P2P_BSEG_ACTIVITIES_UNION AS 
    SELECT *,EPOCH FROM _CEL_P2P_BSIK_ACTIVITIES
    UNION ALL 
    SELECT *,EPOCH FROM _CEL_P2P_BSAK_ACTIVITIES;


DROP VIEW IF EXISTS _CEL_P2P_BSEG_ACTIVITIES;
 
CREATE VIEW _CEL_P2P_BSEG_ACTIVITIES AS(
SELECT 
    _CASE_KEY 
    ,ACTIVITY_EN 
    ,_ACTIVITY_KEY
    ,MANDT 
    ,EBELN
    ,EBELP 
    ,ACTIVITY_DE 
    ,EVENTTIME 
    ,_SORTING 
    ,USER_NAME 
    ,USER_TYPE 
    ,CHANGED_TABLE 
    ,CHANGED_TABLE_TEXT_DE 
    ,CHANGED_TABLE_TEXT_EN 
    ,CHANGED_FIELD 
    ,CHANGED_FIELD_TEXT_DE 
    ,CHANGED_FIELD_TEXT_EN 
    ,CHANGED_FROM 
    ,CHANGED_TO 
    ,CHANGED_FROM_FLOAT
    ,CHANGED_TO_FLOAT 
    ,CHANGE_NUMBER 
    ,TRANSACTION_CODE 
    ,_CELONIS_CHANGE_DATE,
    EPOCH
FROM (
SELECT
    _CEL_P2P_BSEG_ACTIVITIES.*, _CEL_P2P_BSEG_ACTIVITIES.EPOCH,   ROW_NUMBER()
        OVER(PARTITION BY  _CASE_KEY,ACTIVITY_EN,EVENTTIME,TRANSACTION_CODE,_ACTIVITY_KEY
            ORDER BY _CASE_KEY,ACTIVITY_EN,EVENTTIME,TRANSACTION_CODE,_ACTIVITY_KEY,_CELONIS_CHANGE_DATE DESC) AS NUM
FROM
    _CEL_P2P_BSEG_ACTIVITIES_UNION AS _CEL_P2P_BSEG_ACTIVITIES) NUMBERED_ACTIVITIES WHERE NUM=1
);


DROP VIEW IF EXISTS _CEL_P2P_ACTIVITIES;

CREATE VIEW _CEL_P2P_ACTIVITIES AS(
    SELECT *,EPOCH FROM _CEL_P2P_EKPO_ACTIVITIES
        UNION ALL
    SELECT *,EPOCH FROM _CEL_P2P_CDHDR_ACTIVITIES
        UNION ALL
    SELECT *,EPOCH FROM _CEL_P2P_NAST_ACTIVITIES
        UNION ALL
    SELECT *,EPOCH FROM _CEL_P2P_EKES_ACTIVITIES
        UNION ALL
    SELECT *,EPOCH FROM _CEL_P2P_EKBE_ACTIVITIES
         UNION ALL
    SELECT *,EPOCH FROM _CEL_P2P_QALS_ACTIVITIES
         UNION ALL
    SELECT *,EPOCH FROM _CEL_P2P_QAVE_ACTIVITIES 
        UNION ALL
    SELECT  _CASE_KEY 
    ,ACTIVITY_EN 
    ,_ACTIVITY_KEY 
    ,MANDT 
    ,EBELN
    ,EBELP 
    ,ACTIVITY_DE 
  
    ,EVENTTIME 
    ,_SORTING 
    ,USER_NAME 
    ,USER_TYPE 
    ,CHANGED_TABLE 
    ,CHANGED_TABLE_TEXT_DE 
    ,CHANGED_TABLE_TEXT_EN 
    ,CHANGED_FIELD 
    ,CHANGED_FIELD_TEXT_DE 
    ,CHANGED_FIELD_TEXT_EN 
    ,CHANGED_FROM 
    ,CHANGED_TO 
    ,CHANGED_FROM_FLOAT
    ,CHANGED_TO_FLOAT 
    ,CHANGE_NUMBER 
    ,TRANSACTION_CODE 
    ,_CELONIS_CHANGE_DATE
    ,EPOCH
    FROM _CEL_P2P_BSEG_ACTIVITIES
);
