<%=purchaseDoc%>DROP TABLE IF EXISTS TMP_P2P_EKKO_EKPO;

CREATE TABLE TMP_P2P_EKKO_EKPO AS(
	SELECT
    	EKKO.MANDT
	    ,EKKO.EBELN
    	,EKPO.EBELP
	    ,CAST(EKKO.AEDAT AS DATE) AS "AEDAT"
    	,EKKO.ERNAM
        ,EKKO.EKORG
        ,EKPO.KONNR
    	,EKPO.KTPNR
    	,EKKO.BSTYP
    	,EKPO.BANFN
    	,EKPO.BNFPO
    	,EKKO.WAERS
    	,EKKO.LIFNR
    	,EKKO.BUKRS
    	,EKPO.NETWR
        ,EKPO.NETPR
    	,EKKO.WKURS
        ,EKPO.MATNR
        ,EKPO.WERKS
    	,EKKO.MANDT || EKKO.EBELN AS "TABKEY_EKKO"
    	,EKKO.MANDT || EKKO.EBELN || EKPO.EBELP AS "_CASE_KEY"
        ,EKPO.MANDT || EKPO.BANFN || EKPO.BNFPO AS "TABKEY_EBAN"
        ,CAST(EKPO.AEDAT AS DATE) AS "EKPO_AEDAT"
    FROM 
        EKKO AS EKKO
    	JOIN EKPO AS EKPO ON
    		EKKO.MANDT = EKPO.MANDT
    		AND EKKO.EBELN = EKPO.EBELN
    WHERE 
        EKKO.BSTYP = '<%=purchaseDoc%>'
);

SELECT ANALYZE_STATISTICS ('TMP_P2P_EKKO_EKPO'); 
