DROP TABLE IF EXISTS TMP_P2P_EKKO_EKPO_C;

CREATE TABLE TMP_P2P_EKKO_EKPO_C AS(
	SELECT
    	EKKO.MANDT
	    ,EKKO.EBELN
    	,EKPO.EBELP
        ,EKKO.BUKRS
	    ,CAST(EKKO.AEDAT AS DATE) AS AEDAT
    	,EKKO.ERNAM
        ,EKKO.WAERS
    	,EKKO.MANDT || EKKO.EBELN || EKPO.EBELP AS _CASE_KEY
    FROM 
        EKKO AS EKKO
    	JOIN EKPO AS EKPO ON
    		EKKO.MANDT = EKPO.MANDT
    		AND EKKO.EBELN = EKPO.EBELN
    WHERE 
        EKKO.BSTYP = '<%=contractDoc%>'
);

SELECT ANALYZE_STATISTICS ('TMP_P2P_EKKO_EKPO_C'); 
