
INSERT INTO _CEL_P2P_EKPO_ACTIVITIES (
	_CASE_KEY
	,MANDT
	,EBELN
	,EBELP
	,ACTIVITY_DE
	,ACTIVITY_EN
	,EVENTTIME
	,_SORTING
	,USER_NAME
	,USER_TYPE
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY)

SELECT 
	E._CASE_KEY AS _CASE_KEY
	,E.MANDT AS MANDT
	,E.EBELN AS EBELN
	,E.EBELP AS EBELP
	,'Vertrag erstellt' AS ACTIVITY_DE
	,'Create Contract' AS ACTIVITY_EN
	,CASE
        WHEN CHANGES.EVENTTIME IS NOT NULL THEN CHANGES.EVENTTIME
        ELSE CAST(E_CONTRACT.AEDAT AS DATE) + CAST('00:00:01' AS TIME)
    END AS EVENTTIME
    ,100 AS _SORTING
    ,COALESCE(CHANGES.USERNAME, E_CONTRACT.ERNAM) As USER_NAME
    ,USR02.USTYP AS USER_TYPE
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,E_CONTRACT.MANDT || E_CONTRACT.EBELN AS _ACTIVITY_KEY
FROM 
    TMP_P2P_EKKO_EKPO_C AS E_CONTRACT 
   JOIN TMP_P2P_EKKO_EKPO AS E
   ON 1=1
	AND E.MANDT = E_CONTRACT.MANDT 
	AND E.KONNR = E_CONTRACT.EBELN
	AND E.KTPNR = E_CONTRACT.EBELP
    LEFT JOIN (SELECT 
                MANDANT,
                TABKEY,
                EVENTTIME,
                TCODE,
                USERNAME
                FROM P2P_CDHDR_CDPOS
                WHERE TABNAME = 'EKKO'
                AND CHNGIND = 'I'
                AND FNAME = 'KEY') AS CHANGES ON 1=1
            AND E_CONTRACT.MANDT || E_CONTRACT.EBELN  = CHANGES.TABKEY
    LEFT JOIN USR02 AS USR02 ON 1=1
	AND CHANGES.MANDANT = USR02.MANDT
	AND CHANGES.USERNAME = USR02.BNAME
;

