INSERT INTO _CEL_P2P_EKPO_ACTIVITIES (
    _CASE_KEY
    ,MANDT
    ,EBELN
    ,EBELP
    ,ACTIVITY_DE
    ,ACTIVITY_EN
    ,EVENTTIME
    ,_SORTING
    ,USER_NAME 
    ,USER_TYPE
	,TRANSACTION_CODE
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY)
SELECT 
    E._CASE_KEY AS _CASE_KEY 
    , E.MANDT AS MANDT
	, E.EBELN AS EBELN
	, E.EBELP AS EBELP
    ,'Lege BANF Position an' AS ACTIVITY_DE 
    ,'Create Purchase Requisition Item' AS ACTIVITY_EN 
    ,CASE
        WHEN CHANGES.EVENTTIME IS NOT NULL THEN CHANGES.EVENTTIME
        ELSE CAST(EBAN.BADAT AS DATE) + CAST('00:00:01' AS TIME)
    END AS EVENTTIME
    ,200 AS _SORTING
    ,EBAN.ERNAM AS USER_NAME
    ,USR02.USTYP AS USER_TYPE
    ,CHANGES.TCODE AS TRANSACTION_CODE
    , NOW() AS _CELONIS_CHANGE_DATE
    ,EBAN.MANDT || EBAN.BANFN || EBAN.BNFPO AS _ACTIVITY_KEY
FROM 
    TMP_P2P_EKKO_EKPO AS E
    INNER JOIN TMP_EBAN AS EBAN ON 1=1
        AND EBAN.MANDT = E.MANDT 
        AND EBAN.BANFN = E.BANFN 
        AND EBAN.BNFPO = E.BNFPO
    LEFT JOIN USR02 AS USR02 ON 1=1
        AND EBAN.MANDT = USR02.MANDT 
        AND EBAN.ERNAM = USR02.BNAME 
    LEFT JOIN (SELECT 
                TABKEY,
                EVENTTIME,
                TCODE
                FROM P2P_CDHDR_CDPOS
                WHERE TABNAME = 'EBAN'
                AND CHNGIND = 'I'
                AND OBJECTCLAS = 'BANF') AS CHANGES ON 1=1
            AND EBAN.TABKEY_EBAN = CHANGES.TABKEY
;
