INSERT INTO _CEL_P2P_BSIK_ACTIVITIES(
    _CASE_KEY
    ,MANDT
    ,EBELN
    ,EBELP
    ,ACTIVITY_DE
    ,ACTIVITY_EN
    ,EVENTTIME
    ,_SORTING
    , _CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY)

SELECT DISTINCT
    RE._CASE_KEY  AS _CASE_KEY
    ,RE.MANDT AS MANDT
    ,RE.EBELN AS EBELN
    ,RE.EBELP AS EBELP
    ,'Lieferant erstellt Rechnung' AS ACTIVITY_DE
    ,'Vendor Creates Invoice' AS ACTIVITY_EN
    ,CAST(B.BLDAT as DATE) + CAST('00:00:01' AS TIME) AS EVENTTIME
    ,2300 AS _SORTING
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,B.MANDT || B.BUKRS || B.BELNR || B.GJAHR AS _ACTIVITY_KEY
FROM 
    TMP_P2P_RSEG_EKKO_EKPO AS RE 
    INNER JOIN TMP_P2P_BKPF_BSEG AS B ON 1=1
        AND B.MANDT = RE.MANDT
        AND SUBSTRING(B.AWKEY,1,14) = RE.BELNR || CAST(RE.GJAHR AS VARCHAR(4)) 
        AND B.BLDAT IS NOT NULL;
