INSERT INTO _CEL_P2P_CDHDR_ACTIVITIES(
    _CASE_KEY
    ,MANDT
	,EBELN
	,EBELP
    ,ACTIVITY_DE
    ,ACTIVITY_EN
    ,EVENTTIME
    ,_SORTING
    ,USER_NAME
    ,USER_TYPE
    ,CHANGED_TABLE
    ,CHANGED_FIELD
    ,CHANGED_FROM
    ,CHANGED_TO
    ,CHANGE_NUMBER
    ,TRANSACTION_CODE
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY) 
SELECT DISTINCT
    RE._CASE_KEY AS _CASE_KEY 
    ,RE.MANDT AS MANDT
	,RE.EBELN AS EBELN
	,RE.EBELP AS EBELP
    ,CASE
        WHEN CHANGES.VALUE_NEW IS NULL THEN 'Entferne Zahlsperre'
        WHEN CHANGES.VALUE_OLD IS NULL THEN 'Setze Zahlsperre'
    END AS ACTIVITY_DE
    ,CASE
        WHEN CHANGES.VALUE_NEW IS NULL THEN 'Remove Payment Block'
        WHEN CHANGES.VALUE_OLD IS NULL THEN 'Set Payment Block'
    END AS ACTIVITY_EN
    ,CHANGES.EVENTTIME AS EVENTTIME
    ,CASE
        WHEN CHANGES.VALUE_NEW IS NULL THEN 2410
        WHEN CHANGES.VALUE_OLD IS NULL THEN 2420
    END AS _SORTING
    ,CHANGES.USERNAME AS USER_NAME
    ,USR02.USTYP AS USER_TYPE
    ,CHANGES.TABNAME AS CHANGED_TABLE
    ,CHANGES.FNAME AS CHANGED_FIELD
    ,CHANGES.VALUE_OLD AS CHANGED_FROM
    ,CHANGES.VALUE_NEW AS CHANGED_TO
    ,CHANGES.CHANGENR AS CHANGE_NUMBER
    ,CHANGES.TCODE AS TRANSACTION_CODE
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,CHANGES.MANDANT || CHANGES.OBJECTCLAS || CHANGES.OBJECTID || CHANGES.CHANGENR AS _ACTIVITY_KEY
FROM 
	TMP_P2P_RSEG_EKKO_EKPO AS RE 
    LEFT JOIN TMP_P2P_BKPF_BSEG AS B ON 1=1
        AND B.MANDT = RE.MANDT 
        AND SUBSTRING(B.AWKEY,1,14) = RE.BELNR || CAST(RE.GJAHR AS VARCHAR(4))
    JOIN TMP_P2P_CDHDR_CDPOS_BSEG as CHANGES ON 1=1
        AND CHANGES.MANDANT = B.MANDT 
        AND CAST(SUBSTRING(CHANGES.TABKEY,4,4) AS CHAR(4)) = CAST(B.BUKRS AS CHAR(4)) -- This is necessary in case BUKRS only has three digits but requires further validation. 
        AND SUBSTRING(CHANGES.TABKEY,8,10) = B.BELNR
        AND SUBSTRING(CHANGES.TABKEY,18,4) = B.GJAHR
        AND SUBSTRING(CHANGES.TABKEY,22,3) = B.BUZEI
        AND (CHANGES.VALUE_OLD IS NULL OR CHANGES.VALUE_NEW IS NULL)
    LEFT JOIN USR02 AS USR02 ON 1=1
        AND CHANGES.MANDANT = USR02.MANDT
        AND CHANGES.USERNAME = USR02.BNAME
;
