INSERT INTO _CEL_P2P_BSAK_ACTIVITIES(
    _CASE_KEY
    ,MANDT
    ,EBELN
    ,EBELP
    ,ACTIVITY_DE
    ,ACTIVITY_EN
    ,EVENTTIME
    ,_SORTING
    ,USER_NAME
    ,USER_TYPE
    ,TRANSACTION_CODE
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY )
SELECT DISTINCT
	RE._CASE_KEY AS _CASE_KEY
	,RE.MANDT AS MANDT
	,RE.EBELN AS EBELN
	,RE.EBELP AS EBELP
	,'Gleiche Rechnung aus' AS ACTIVITY_DE
	,'Clear Invoice' AS ACTIVITY_EN
	,CASE 
  		WHEN CAST(BKPF_Z.CPUDT AS DATE) = CAST(B.AUGDT AS DATE)
  		THEN CAST(BKPF_Z.CPUDT AS DATE) + CAST(BKPF_Z.CPUTM as TIME)
  		ELSE CAST(B.AUGDT AS DATE) + CAST('23:59:59' as TIME)
  	END AS EVENTTIME
	,2500 AS _SORTING
	,BKPF_Z.USNAM AS USER_NAME
	,USR02.USTYP AS USER_TYPE
	,BKPF_Z.TCODE AS TRANSACTION_CODE
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,B.MANDT || B.BUKRS || B.BELNR || B.GJAHR AS _ACTIVITY_KEY
FROM 
    TMP_P2P_RSEG_EKKO_EKPO AS RE 
	INNER JOIN TMP_P2P_BKPF_BSEG AS B ON 1=1
		AND B.MANDT = RE.MANDT
		AND SUBSTRING(B.AWKEY,1,14) = RE.BELNR || CAST(RE.GJAHR AS VARCHAR(4))
        AND B.AUGBL IS NOT NULL 
	LEFT JOIN BKPF AS BKPF_Z ON 1=1
		AND B.MANDT = BKPF_Z.MANDT
		AND B.BUKRS = BKPF_Z.BUKRS
		AND B.AUGBL = BKPF_Z.BELNR
		AND B.AUGGJ = BKPF_Z.GJAHR
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND BKPF_Z.MANDT = USR02.MANDT
		AND BKPF_Z.USNAM = USR02.BNAME
	    AND BKPF_Z.CPUDT IS NOT NULL
;
