DROP VIEW IF EXISTS P2P_BKPF;

CREATE VIEW P2P_BKPF AS 
SELECT 
    BKPF.*,
    P2P_BKPF_STAGING.TS_BLDAT, 
    P2P_BKPF_STAGING.TS_BUDAT, 
    P2P_BKPF_STAGING.TS_CPUDT,
    P2P_BKPF_STAGING.TS_CPUDT_CPUTM,
    P2P_BKPF_STAGING.TS_AEDAT, 
    P2P_BKPF_STAGING.TS_UPDDT, 
    P2P_BKPF_STAGING.TS_WWERT, 
    P2P_BKPF_STAGING.TS_STODT, 
    P2P_BKPF_STAGING.TS_REINDAT, 
    P2P_BKPF_STAGING.TS_VATDATE, 
    P2P_BKPF_STAGING.TS_INTDATE, 
    P2P_BKPF_STAGING.TS_PSOBT, 
    P2P_BKPF_STAGING.TS_PSODT, 
    P2P_BKPF_STAGING.TS_PSODT_PSOTM,
    P2P_BKPF_STAGING.TS_OFFSET_REFER_DAT, 
    P2P_BKPF_STAGING.RBKPKEY ,-- Join to MM (RBKP)
    P2P_BKPF_STAGING.EPOCH
FROM    
	BKPF AS BKPF
    JOIN P2P_BKPF_STAGING ON 1=1 
        AND BKPF.MANDT=P2P_BKPF_STAGING.MANDT
        AND BKPF.BUKRS=P2P_BKPF_STAGING.BUKRS
        AND BKPF.BELNR=P2P_BKPF_STAGING.BELNR
        AND BKPF.GJAHR=P2P_BKPF_STAGING.GJAHR
;

