DROP VIEW IF EXISTS P2P_BSIK;

CREATE VIEW P2P_BSIK AS 
SELECT 
    BSIK.*,
    P2P_BSIK_STAGING.TS_AUGDT, 
    P2P_BSIK_STAGING.TS_AUGCP,
    P2P_BSIK_STAGING.EPOCH
FROM 
    BSIK AS BSIK JOIN 
    P2P_BSIK_STAGING ON 1=1
        AND BSIK.MANDT= P2P_BSIK_STAGING.MANDT
        AND BSIK.BUKRS= P2P_BSIK_STAGING.BUKRS
        AND BSIK.GJAHR= P2P_BSIK_STAGING.GJAHR
        AND BSIK.BELNR= P2P_BSIK_STAGING.BELNR
        AND BSIK.BUZEI= P2P_BSIK_STAGING.BUZEI
;

--------------------------
DROP VIEW IF EXISTS P2P_BSAK;

CREATE VIEW P2P_BSAK AS 
SELECT 
    BSAK.*,
    P2P_BSAK_STAGING.TS_AUGDT, 
    P2P_BSAK_STAGING.TS_AUGCP,
    P2P_BSAK_STAGING.EPOCH
FROM
    BSAK AS BSAK JOIN
    P2P_BSAK_STAGING ON 1=1
        AND BSAK.MANDT= P2P_BSAK_STAGING.MANDT
        AND BSAK.BUKRS= P2P_BSAK_STAGING.BUKRS
        AND BSAK.GJAHR= P2P_BSAK_STAGING.GJAHR
        AND BSAK.BELNR= P2P_BSAK_STAGING.BELNR
        AND BSAK.BUZEI= P2P_BSAK_STAGING.BUZEI
;

---

DROP VIEW IF EXISTS P2P_BSEG_UNION;

CREATE VIEW P2P_BSEG_UNION AS 
SELECT *, EPOCH FROM P2P_BSAK
UNION ALL 
SELECT *,EPOCH FROM P2P_BSIK;

DROP VIEW IF EXISTS P2P_BSEG;
 
CREATE VIEW P2P_BSEG AS(
SELECT *,EPOCH FROM (
SELECT
    BSEG.*,    ROW_NUMBER()
        OVER(PARTITION BY BSEG.MANDT, BSEG.BUKRS, BSEG.BELNR, BSEG.GJAHR, BSEG.BUZEI
            ORDER BY BSEG.MANDT, BSEG.BUKRS, BSEG.BELNR, BSEG.GJAHR, BSEG.BUZEI, _CELONIS_CHANGE_DATE DESC) AS NUM,EPOCH
FROM
    P2P_BSEG_UNION AS BSEG) NUMBERED_BSEG WHERE NUM=1
);

