DROP VIEW IF EXISTS P2P_EKKO;

CREATE VIEW P2P_EKKO AS (
SELECT 
    EKKO.*,
    P2P_EKKO_STAGING.TS_AEDAT, 
    P2P_EKKO_STAGING.TS_ANGDT, 
    P2P_EKKO_STAGING.TS_BEDAT, 
    P2P_EKKO_STAGING.TS_BNDDT, 
    P2P_EKKO_STAGING.TS_BWBDT, 
    P2P_EKKO_STAGING.TS_DPDAT, 
    P2P_EKKO_STAGING.TS_EQ_EINDT, 
    P2P_EKKO_STAGING.TS_GWLDT, 
    P2P_EKKO_STAGING.TS_IHRAN, 
    P2P_EKKO_STAGING.TS_KDATB, 
    P2P_EKKO_STAGING.TS_KDATE, 
    P2P_EKKO_STAGING.TS_RELEASE_DATE, 
	P2P_EKKO_STAGING.BSTYP_TEXT,
	P2P_EKKO_STAGING.STATU_TEXT,
	P2P_EKKO_STAGING.BSART_TEXT,
    P2P_EKKO_STAGING.EKORG_TEXT,
	P2P_EKKO_STAGING.BUKRS_TEXT,
    P2P_EKKO_STAGING.BUKRS_TEXT2,
	P2P_EKKO_STAGING.BUKRS_TEXT3,
	P2P_EKKO_STAGING.EKGRP_TEXT,
    P2P_EKKO_STAGING.EPOCH
FROM 
    EKKO AS EKKO JOIN 
    P2P_EKKO_STAGING ON 1=1
        AND EKKO.MANDT=P2P_EKKO_STAGING.MANDT
        AND EKKO.EBELN=P2P_EKKO_STAGING.EBELN
);
