DROP VIEW IF EXISTS P2P_EKPO;

CREATE VIEW P2P_EKPO AS (
SELECT 
    EKPO.*,
 	P2P_EKPO_STAGING.TS_ABDAT, 
    P2P_EKPO_STAGING.TS_AEDAT, 
    P2P_EKPO_STAGING.TS_AGDAT, 
    P2P_EKPO_STAGING.TS_DPDAT, 
    P2P_EKPO_STAGING.TS_DRDAT, 
    P2P_EKPO_STAGING.TS_EILDT, 
    P2P_EKPO_STAGING.TS_J_1AIDATEP, 
    P2P_EKPO_STAGING.TS_LEWED, 
    P2P_EKPO_STAGING.TS_NFABD, 
    P2P_EKPO_STAGING.TS_NLABD, 
    P2P_EKPO_STAGING.TS_PRDAT,
    P2P_EKPO_STAGING.MATKL_TEXT,
	P2P_EKPO_STAGING.MATNR_TEXT,
	P2P_EKPO_STAGING.BUKRS_TEXT,
	P2P_EKPO_STAGING.WERKS_TEXT,
    P2P_EKPO_STAGING.WERKS_COUNTRY_KEY,
	P2P_EKPO_STAGING.LGORT_TEXT,
	P2P_EKPO_STAGING.PSTYP_TEXT,
	P2P_EKPO_STAGING.KNTTP_TEXT,
	P2P_EKPO_STAGING.NETWR_CONVERTED,
  	P2P_EKPO_STAGING.NETPR_CONVERTED,
    P2P_EKPO_STAGING.LIFNR,
    P2P_EKPO_STAGING.WAERS,
    P2P_EKPO_STAGING.EKORG,
    P2P_EKPO_STAGING.WERKS_JOIN,
    P2P_EKPO_STAGING.EPOCH
  FROM 
    EKPO AS EKPO
    JOIN P2P_EKPO_STAGING ON 1=1
      AND EKPO.MANDT=P2P_EKPO_STAGING.MANDT
      AND EKPO.EBELN=P2P_EKPO_STAGING.EBELN
      AND EKPO.EBELP=P2P_EKPO_STAGING.EBELP
);



