DROP TABLE IF EXISTS P2P_EKET_STAGING;

CREATE TABLE P2P_EKET_STAGING AS(
SELECT 
    EKET.MANDT,
    EKET.EBELN,
    EKET.EBELP,
    EKET.ETENR,
    CAST(EKET.ALTDT AS DATE) AS TS_ALTDT, 
    CAST(EKET.DAT01 AS DATE) AS TS_DAT01, 
    CAST(EKET.EINDT AS DATE) AS TS_EINDT, 
    CAST(EKET.ELDAT AS DATE) AS TS_ELDAT, 
    CAST(EKET.LDDAT AS DATE) AS TS_LDDAT, 
    CAST(EKET.MBDAT AS DATE) AS TS_MBDAT, 
    CAST(EKET.SLFDT AS DATE) AS TS_SLFDT
FROM 
    EKET
WHERE EXISTS(
    SELECT * 
    FROM TMP_P2P_EKKO_EKPO AS C
    WHERE 1=1 
        AND EKET.MANDT = C.MANDT
        AND EKET.EBELN = C.EBELN
        AND EKET.EBELP = C.EBELP)
);

SELECT ANALYZE_STATISTICS ('P2P_EKET_STAGING'); 


