DROP VIEW IF EXISTS P2P_EKET;

CREATE VIEW P2P_EKET AS(
SELECT 
    EKET.*,
    P2P_EKET_STAGING.TS_ALTDT, 
    P2P_EKET_STAGING.TS_DAT01, 
    P2P_EKET_STAGING.TS_EINDT, 
    P2P_EKET_STAGING.TS_ELDAT, 
    P2P_EKET_STAGING.TS_LDDAT, 
    P2P_EKET_STAGING.TS_MBDAT, 
    P2P_EKET_STAGING.TS_SLFDT,
    P2P_EKET_STAGING.EPOCH
FROM 
    EKET JOIN 
    P2P_EKET_STAGING ON 1=1
        AND P2P_EKET_STAGING.MANDT=EKET.MANDT
        AND P2P_EKET_STAGING.EBELN=EKET.EBELN
        AND P2P_EKET_STAGING.EBELP=EKET.EBELP
        AND P2P_EKET_STAGING.ETENR=EKET.ETENR
);
