DROP TABLE IF EXISTS P2P_EKES_STAGING;

CREATE TABLE P2P_EKES_STAGING AS(
SELECT 
    EKES.MANDT,
    EKES.EBELN,
    EKES.EBELP,
    EKES.ETENS,
    CAST(EKES.EINDT AS DATE) AS TS_EINDT, 
    CAST(EKES.ERDAT AS DATE) AS TS_ERDAT
FROM 
    EKES
WHERE EXISTS(
    SELECT * 
    FROM TMP_P2P_EKKO_EKPO AS C
    WHERE 1=1 
        AND EKES.MANDT = C.MANDT
        AND EKES.EBELN = C.EBELN
        AND EKES.EBELP = C.EBELP
    )
);

SELECT ANALYZE_STATISTICS ('P2P_EKES_STAGING'); 

