DROP VIEW IF EXISTS P2P_EKES;

CREATE VIEW P2P_EKES AS(
SELECT 
    EKES.*,
    P2P_EKES_STAGING.TS_EINDT, 
    P2P_EKES_STAGING.TS_ERDAT,
    P2P_EKES_STAGING.EPOCH
FROM 
    EKES JOIN 
    P2P_EKES_STAGING ON 1=1
        AND EKES.MANDT=P2P_EKES_STAGING.MANDT
        AND EKES.EBELN=P2P_EKES_STAGING.EBELN
        AND EKES.EBELP=P2P_EKES_STAGING.EBELP
        AND EKES.ETENS=P2P_EKES_STAGING.ETENS
);

