DROP TABLE IF EXISTS P2P_NAST_STAGING;

CREATE TABLE P2P_NAST_STAGING AS(
SELECT 
    NAST.MANDT,
    NAST.KAPPL,
    NAST.OBJKY,
    NAST.KSCHL,
    NAST.SPRAS,
    NAST.PARNR,
    NAST.PARVW,
    NAST.ERDAT,
    NAST.ERUHR,
    IFNULL(DD07T.DDTEXT,'') AS NACHA_TEXT,
    CAST(NAST.ERDAT AS DATE) AS TS_ERDAT,
    CAST(NAST.VSDAT AS DATE) AS TS_VSDAT,
    CAST(NAST.DATVR AS DATE) AS TS_DATVR,
    CAST(NAST.DATRE AS DATE) AS TS_DATRE
FROM 
    NAST
    LEFT JOIN DD07T AS DD07T ON 1=1
	    AND DD07T.DOMVALUE_L = NAST.NACHA 
	    AND DD07T.DOMNAME = 'NA_NACHA'
	    AND DD07T.DDLANGUAGE = '<%=primaryLanguageKey%>'
WHERE EXISTS(
    SELECT * 
    FROM TMP_P2P_EKKO_EKPO AS C
    WHERE 1=1
        AND NAST.MANDT = C.MANDT 
        AND NAST.OBJKY = C.EBELN)
);

SELECT ANALYZE_STATISTICS ('P2P_NAST_STAGING'); 

