DROP VIEW IF EXISTS P2P_QALS;

CREATE VIEW P2P_QALS AS (
SELECT 
    QALS.*,
    P2P_QALS_STAGING.TS_ENSTEHDAT,
    P2P_QALS_STAGING.TS_ERSTELDAT,
    P2P_QALS_STAGING.TS_AENDERDAT,
    P2P_QALS_STAGING.TS_PASTRTERM,
    P2P_QALS_STAGING.TS_PAENDTERM,
    P2P_QALS_STAGING.TS_GUELTIGAB,
    P2P_QALS_STAGING.TS_ZEUGNISBIS,
    P2P_QALS_STAGING.TS_VFDAT,
    P2P_QALS_STAGING.TS_BUDAT,
    P2P_QALS_STAGING.TS_DABRZ,
    P2P_QALS_STAGING.EPOCH
FROM QALS JOIN 
    P2P_QALS_STAGING ON 1=1
        AND  QALS.MANDANT=P2P_QALS_STAGING.MANDANT
        AND  QALS.PRUEFLOS=P2P_QALS_STAGING.PRUEFLOS
);
