DROP TABLE IF EXISTS P2P_RSEG_STAGING;

CREATE TABLE P2P_RSEG_STAGING AS(
SELECT 
	RSEG.MANDT,
    RSEG.BELNR,
    RSEG.GJAHR,
    RSEG.BUZEI,
    RSEG.EBELN,
    RSEG.EBELP,
    CAST(RSEG.RETDUEDT AS DATE) AS TS_RETDUEDT
FROM 
    RSEG
WHERE EXISTS(
    SELECT * 
    FROM TMP_P2P_EKKO_EKPO AS C 
    WHERE 1=1 
        AND RSEG.MANDT = C.MANDT
        AND RSEG.EBELN = C.EBELN
        AND RSEG.EBELP = C.EBELP)
);

SELECT ANALYZE_STATISTICS ('P2P_RSEG_STAGING'); 
