DROP TABLE IF EXISTS P2P_RBKP_STAGING;

CREATE TABLE P2P_RBKP_STAGING AS(
SELECT DISTINCT 
	RBKP.MANDT,
    RBKP.BELNR,
    RBKP.GJAHR,
    CAST(RBKP.BLDAT AS DATE) AS TS_BLDAT,
    CAST(RBKP.BUDAT AS DATE) AS TS_BUDAT,
    CAST(RBKP.CPUDT AS DATE) AS TS_CPUDT,
    CAST(RBKP.ZFBDT AS DATE) AS TS_ZFBDT,
    CAST(RBKP.VATDATE AS DATE) AS TS_VATDATE,
    CAST(RBKP.REINDAT AS DATE) AS TS_REINDAT,
    CAST(RBKP.FDTAG AS DATE) AS TS_FDTAG,
    CAST(RBKP.ASSIGN_NEXT_DATE AS DATE) AS TS_ASSIGN_NEXT_DATE,
    CAST(RBKP.ASSIGN_END_DATE AS DATE) AS TS_ASSIGN_END_DATE,
    CAST(RBKP.WWERT AS DATE) AS TS_WWERT
    ,RBKP.BELNR || CAST(RBKP.GJAHR AS VARCHAR(4)) AS BKPFKEY -- to join with FI (BKPF)
FROM 
    RBKP
    INNER JOIN RSEG AS RSEG ON 1=1
        AND RSEG.MANDT = RBKP.MANDT
        AND RSEG.BELNR = RBKP.BELNR
        AND RSEG.GJAHR = RBKP.GJAHR
WHERE EXISTS(
    SELECT * 
    FROM TMP_P2P_EKKO_EKPO AS C 
    WHERE 1=1 
        AND RSEG.MANDT = C.MANDT
        AND RSEG.EBELN = C.EBELN
        AND RSEG.EBELP = C.EBELP)
);

SELECT ANALYZE_STATISTICS ('P2P_RBKP_STAGING'); 

