DROP TABLE IF EXISTS TMP_P2P_BKPF_BSEG;
DROP TABLE IF EXISTS TMP_P2P_EKKO_EKPO;
DROP TABLE IF EXISTS TMP_P2P_RSEG_EKKO_EKPO;
DROP TABLE IF EXISTS TMP_EBAN;
DROP TABLE IF EXISTS TMP_P2P_EKKO_EKPO;
DROP TABLE IF EXISTS TMP_P2P_EKKO_EKPO_C;
DROP TABLE IF EXISTS TMP_P2P_CDHDR_CDPOS_BSEG;

DROP TABLE IF EXISTS P2P_TCURF_TMP;
DROP TABLE IF EXISTS P2P_TCURR_TMP;
DROP TABLE IF EXISTS EKPO_CURR_TMP; 

-----------------------------------------------------------
DELETE FROM
    _CEL_P2P_EKPO_ACTIVITIES
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_EKPO_ACTIVITIES
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_EKPO_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
-----------------------------------------------------------
DELETE FROM
    _CEL_P2P_CDHDR_ACTIVITIES
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_CDHDR_ACTIVITIES
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_CDHDR_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
-----------------------------------------------------------
DELETE FROM
    _CEL_P2P_NAST_ACTIVITIES
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_NAST_ACTIVITIES
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_NAST_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
-----------------------------------------------------------
DELETE FROM
    _CEL_P2P_EKES_ACTIVITIES
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_EKES_ACTIVITIES
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_EKES_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
-----------------------------------------------------------
DELETE FROM
    _CEL_P2P_EKBE_ACTIVITIES
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_EKBE_ACTIVITIES
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_EKBE_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
-----------------------------------------------------------
DELETE FROM
    _CEL_P2P_QALS_ACTIVITIES
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_QALS_ACTIVITIES
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_QALS_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
-----------------------------------------------------------
DELETE FROM
    _CEL_P2P_QAVE_ACTIVITIES
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_QAVE_ACTIVITIES
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_QAVE_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
-----------------------------------------------------------
DELETE FROM
    _CEL_P2P_BSIK_ACTIVITIES
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_BSIK_ACTIVITIES
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_BSIK_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;

-----------------------------------------------------------
DELETE FROM
    _CEL_P2P_BSAK_ACTIVITIES
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_BSAK_ACTIVITIES
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_BSAK_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;

-----------------------------------------------------------

SELECT ANALYZE_STATISTICS('_CEL_P2P_EKPO_ACTIVITIES'); 
SELECT ANALYZE_STATISTICS('_CEL_P2P_CDHDR_ACTIVITIES');
SELECT ANALYZE_STATISTICS('_CEL_P2P_NAST_ACTIVITIES');
SELECT ANALYZE_STATISTICS('_CEL_P2P_EKES_ACTIVITIES'); 
SELECT ANALYZE_STATISTICS('_CEL_P2P_EKBE_ACTIVITIES'); 
SELECT ANALYZE_STATISTICS('_CEL_P2P_QALS_ACTIVITIES'); 
SELECT ANALYZE_STATISTICS('_CEL_P2P_QAVE_ACTIVITIES');
SELECT ANALYZE_STATISTICS('_CEL_P2P_BSIK_ACTIVITIES');
SELECT ANALYZE_STATISTICS('_CEL_P2P_BSAK_ACTIVITIES');


