DROP VIEW IF EXISTS P2P_LFA1;

CREATE VIEW P2P_LFA1 AS(
SELECT
	LFA1.*,
    CAST(LFA1.ERDAT AS DATE) AS TS_ERDAT,
    CAST(LFA1.GBDAT AS DATE) AS TS_GBDAT,
    CAST(LFA1.REVDB AS DATE) AS TS_REVDB,
    CAST(LFA1.UPDAT AS DATE) AS TS_UPDAT,
    CAST(LFA1.QSSYSDAT AS DATE) AS TS_QSSYSDAT,
    CAST(LFA1.RGDATE AS DATE) AS TS_RGDATE,
    CAST(LFA1.RNEDATE AS DATE) AS TS_RNEDATE,
    EPOCH
FROM 
    LFA1 
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKKO_STAGING AS C
    WHERE 1=1 
    AND LFA1.MANDT = C.MANDT 
    AND LFA1.LIFNR = C.LIFNR)
);
