INSERT INTO _CEL_P2P_CDHDR_ACTIVITIES_DELTA (
	_CASE_KEY
	,MANDT
	,EBELN
	,EBELP
	,ACTIVITY_DE
	,ACTIVITY_EN
	,EVENTTIME
	,_SORTING
	,USER_NAME
	,USER_TYPE
	,CHANGED_TABLE
	,CHANGED_FIELD
	,CHANGED_FROM
	,CHANGED_TO
	,CHANGE_NUMBER
	,TRANSACTION_CODE
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY)
SELECT 
	E._CASE_KEY AS _CASE_KEY
	,E.MANDT AS MANDT
	,E.EBELN AS EBELN
	,E.EBELP AS EBELP
	,CASE
		WHEN CHANGES.FNAME = 'LIFNR' THEN 'Ändere Lieferant' 
		WHEN CHANGES.FNAME = 'FRGKE' AND CHANGES.VALUE_NEW IN <%=releasePoIndicators%> THEN 'Gebe Bestellung frei'
		WHEN CHANGES.FNAME = 'FRGKE' AND CHANGES.VALUE_NEW IN <%=blockPoIndicators%> THEN 'Lehne Bestellung ab'
		WHEN CHANGES.FNAME = 'FRGKE' THEN 'Ändere Freigabe für Bestellung'
		WHEN CHANGES.FNAME = 'WAERS' THEN 'Ändere Währung'
        WHEN CHANGES.FNAME = 'ZTERM' THEN 'Ändere Zahlungsbedingungen'
	END AS ACTIVITY_DE
	,CASE 
	    WHEN CHANGES.FNAME = 'LIFNR' THEN 'Change Vendor'
		WHEN CHANGES.FNAME = 'FRGKE' AND CHANGES.VALUE_NEW IN <%=releasePoIndicators%> THEN 'Release Purchase Order' 
		WHEN CHANGES.FNAME = 'FRGKE' AND  CHANGES.VALUE_NEW IN <%=blockPoIndicators%> THEN 'Refuse Purchase Order'
		WHEN CHANGES.FNAME = 'FRGKE' THEN 'Change Approval for Purchase Order' 
		WHEN CHANGES.FNAME = 'WAERS' THEN 'Change Currency'
        WHEN CHANGES.FNAME = 'ZTERM' THEN 'Change Payment Terms'
	END AS ACTIVITY_EN
	,CHANGES.EVENTTIME AS EVENTTIME
	,CASE 
	    WHEN CHANGES.FNAME = 'LIFNR' THEN 910
		WHEN CHANGES.FNAME = 'FRGKE' AND CHANGES.VALUE_NEW IN <%=releasePoIndicators%> THEN 920
		WHEN CHANGES.FNAME = 'FRGKE' AND  CHANGES.VALUE_NEW IN <%=blockPoIndicators%> THEN 930
		WHEN CHANGES.FNAME = 'FRGKE' THEN 940
		WHEN CHANGES.FNAME = 'WAERS' THEN 950
        WHEN CHANGES.FNAME = 'ZTERM' THEN 960
	END AS _SORTING
	,CHANGES.USERNAME AS USER_NAME
	,USR02.USTYP AS USER_TYPE
	,CHANGES.TABNAME AS CHANGED_TABLE
	,CHANGES.FNAME AS CHANGED_FIELD
	,CHANGES.VALUE_OLD AS CHANGED_FROM
	,CHANGES.VALUE_NEW AS CHANGED_TO
	,CHANGES.CHANGENR AS CHANGE_NUMBER
	,CHANGES.TCODE AS TRANSACTION_CODE
    , NOW() AS _CELONIS_CHANGE_DATE
    ,CHANGES.MANDANT || CHANGES.OBJECTCLAS || CHANGES.OBJECTID || CHANGES.CHANGENR AS _ACTIVITY_KEY
FROM
    P2P_EKPO_STAGING AS E
    INNER JOIN  TMP_P2P_CDHDR_CDPOS AS CHANGES ON 1=1
        AND CHANGES.OBJECTID = E.EBELN
        AND E.MANDT = CHANGES.MANDANT
        AND E.TABKEY_EKKO = CHANGES.TABKEY
        AND CHANGES.FNAME IN ('LIFNR', 'WAERS', 'FRGKE','ZTERM') 
        AND CHANGES.TABNAME = 'EKKO'
	LEFT JOIN USR02  AS USR02 ON 1=1
		AND CHANGES.MANDANT = USR02.MANDT
		AND CHANGES.USERNAME = USR02.BNAME
;
