DELETE FROM P2P_CDHDR_CDPOS
WHERE EXISTS (SELECT 1 FROM <$CDPOS> as NEW_DATA 
              WHERE P2P_CDHDR_CDPOS.MANDANT = NEW_DATA.MANDANT 
              AND P2P_CDHDR_CDPOS.OBJECTCLAS = NEW_DATA.OBJECTCLAS
              AND P2P_CDHDR_CDPOS.OBJECTID = NEW_DATA.OBJECTID
              AND P2P_CDHDR_CDPOS.CHANGENR = NEW_DATA.CHANGENR
              AND P2P_CDHDR_CDPOS.TABNAME = NEW_DATA.TABNAME
              AND P2P_CDHDR_CDPOS.TABKEY = NEW_DATA.TABKEY
              AND P2P_CDHDR_CDPOS.FNAME = NEW_DATA.FNAME
               AND P2P_CDHDR_CDPOS.CHNGIND = NEW_DATA.CHNGIND
              );


-- Query 2
INSERT INTO P2P_CDHDR_CDPOS
	SELECT
	CHANGES.MANDANT
	,CHANGES.FNAME
	,CHANGES.TABNAME
	,CHANGES.TABKEY
	,CHANGES.VALUE_OLD
	,CHANGES.VALUE_NEW
	,CHANGES.EVENTTIME
	,CHANGES.CHANGENR
    ,CHANGES.CHNGIND
	,CHANGES.TCODE
	,CHANGES.OBJECTCLAS
	,CHANGES.OBJECTID
	,CHANGES.USERNAME
	FROM TMP_P2P_CDHDR_CDPOS AS CHANGES 
;
    SELECT ANALYZE_STATISTICS ('P2P_CDHDR_CDPOS'); 

