
DELETE FROM P2P_CONTRACT_INFO
WHERE EXISTS (SELECT 1 FROM <$EKPO> as NEW_DATA 
              WHERE P2P_CONTRACT_INFO.MANDT = NEW_DATA.MANDT 
              AND P2P_CONTRACT_INFO.EBELN = NEW_DATA.EBELN
              AND P2P_CONTRACT_INFO.EBELP = NEW_DATA.EBELP
              );


INSERT INTO P2P_CONTRACT_INFO
SELECT 
     EKPO_CONTRACT.MANDT
	,EKPO_CONTRACT.EBELN
	,EKPO_CONTRACT.EBELP
	,EKPO_CONTRACT.KTMNG
	,EKPO_CONTRACT.ZWERT
    ,EKPO_CONTRACT.WERKS
    ,EKKO_CONTRACT.LIFNR
    ,LFA1.NAME1
    ,EKPO_CONTRACT.PEINH
    ,EKPO_CONTRACT.MENGE
    ,EKPO_CONTRACT.LMEIN 
    ,EKPO_CONTRACT.GEWEI 
    ,EKPO_CONTRACT.NETPR
    ,CASE 
		WHEN EKKO_CONTRACT.WAERS = '<%=currency%>' THEN EKPO_CONTRACT.NETPR*ISNULL(TCURX.TDEC,1) 
  		WHEN TCURR_CC.UKURS < 0 THEN (EKPO_CONTRACT.NETPR*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		WHEN TCURR_CC.UKURS > 0 THEN (EKPO_CONTRACT.NETPR*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
	END AS NETPR_CONVERTED
    ,CAST(EKKO_CONTRACT.KDATB AS DATE) AS TS_KDATB
    ,CAST(EKKO_CONTRACT.KDATE AS DATE) AS TS_KDATE
	,CAST(EKKO_CONTRACT.AEDAT AS DATE) AS TS_AEDAT
	,EKPO_CONTRACT.MEINS
    ,EKPO_CONTRACT.MATKL
    ,IFNULL(T023T.WGBEZ,'') AS MATKL_TEXT
    ,EKPO_CONTRACT.MATNR
    ,IFNULL(MAKT.MAKTX,'') AS MATNR_TEXT
	,EKPO_CONTRACT.TXZ01
  	,EKPO_CONTRACT.BUKRS
	,EKKO_CONTRACT.BSART
    ,EKKO_CONTRACT.WAERS
   ,EKKO_CONTRACT.EKORG
   ,IFNULL(T024E.EKOTX,'') AS EKORG_TEXT
  ,EKKO_CONTRACT.ZTERM
   ,IFNULL(T052U.TEXT1,'') AS ZTERM_TEXT
   ,EKKO_CONTRACT.ZBD1T
   ,EKKO_CONTRACT.ZBD2T
   ,EKKO_CONTRACT.ZBD3T
   ,EKKO_CONTRACT.ZBD1P
   ,EKKO_CONTRACT.ZBD2P
   ,EKKO_CONTRACT.DESCRIPTION
   ,EKPO_CONTRACT.KONNR
   ,EKPO_CONTRACT.KTPNR
   ,EKKO_CONTRACT.ERNAM
   ,EKPO_CONTRACT.MANDT || EKPO_CONTRACT.EBELN || EKPO_CONTRACT.EBELP AS 'CONTRACT_CASEKEY'
   ,EKPO_CONTRACT.MANDT || ISNULL(EKKO_CONTRACT.EKORG, '-') || ISNULL(EKPO_CONTRACT.WERKS, '-') ||  ISNULL(EKKO_CONTRACT.WAERS, '-')  AS TAB_KEY
FROM 
	<$EKPO> AS EKPO_CONTRACT
	INNER JOIN EKKO AS EKKO_CONTRACT ON 1=1
  		AND EKPO_CONTRACT.MANDT = EKKO_CONTRACT.MANDT
  		AND EKPO_CONTRACT.EBELN = EKKO_CONTRACT.EBELN
    LEFT JOIN P2P_TCURR_CC AS TCURR_CC ON 1=1
		AND TCURR_CC.MANDT = EKKO_CONTRACT.MANDT
		AND TCURR_CC.TCURR = '<%=currency%>'
		AND TCURR_CC.FCURR = EKKO_CONTRACT.WAERS                                             
		AND EKPO_CONTRACT.AEDAT >= TCURR_CC.VALID_START AND EKPO_CONTRACT.AEDAT < TCURR_CC.VALID_END
        AND TCURR_CC.KURST = '<%=exchangeRateType%>' 
    LEFT JOIN P2P_TCURF_CC AS TCURF_CC ON 1=1
		AND TCURR_CC.MANDT = TCURF_CC.MANDT
		AND TCURR_CC.TCURR = TCURF_CC.TCURR
		AND TCURR_CC.FCURR = TCURF_CC.FCURR
		AND TCURR_CC.KURST = TCURF_CC.KURST
        AND EKPO_CONTRACT.AEDAT>= TCURF_CC.VALID_START	
		AND EKPO_CONTRACT.AEDAT < TCURF_CC.VALID_END
	LEFT JOIN (
		SELECT 
			TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
			TCURX) AS TCURX ON 1=1
		AND EKKO_CONTRACT.WAERS  = TCURX.CURRKEY
  LEFT JOIN LFA1 ON 1=1
       AND LFA1.MANDT = EKKO_CONTRACT.MANDT
       AND LFA1.LIFNR = EKKO_CONTRACT.LIFNR
    LEFT JOIN MAKT AS MAKT ON 1=1
       AND EKPO_CONTRACT.MANDT = MAKT.MANDT
       AND EKPO_CONTRACT.MATNR = MAKT.MATNR
       AND MAKT.SPRAS = '<%=primaryLanguageKey%>'
    LEFT JOIN T023T AS T023T ON 1=1
       AND EKPO_CONTRACT.MANDT = T023T.MANDT
       AND EKPO_CONTRACT.MATKL = T023T.MATKL
       AND T023T.SPRAS = '<%=primaryLanguageKey%>'
    LEFT JOIN T052U AS T052U ON 1=1
       AND EKKO_CONTRACT.MANDT = T052U.MANDT
       AND EKKO_CONTRACT.ZTERM = T052U.ZTERM
       AND T052U.SPRAS = '<%=primaryLanguageKey%>'
    LEFT JOIN T024E AS T024E ON 1=1
       AND EKKO_CONTRACT.MANDT = T024E.MANDT
       AND EKKO_CONTRACT.EKORG = T024E.EKORG   
WHERE EKPO_CONTRACT.BSTYP = 'K';

SELECT ANALYZE_STATISTICS ('P2P_CONTRACT_INFO'); 
