
DELETE FROM P2P_QAVE_STAGING
WHERE EXISTS (SELECT 1 FROM <$QAVE> as NEW_DATA 
              WHERE P2P_QAVE_STAGING.MANDANT=NEW_DATA.MANDANT 
              AND P2P_QAVE_STAGING.PRUEFLOS=NEW_DATA.PRUEFLOS 
                AND P2P_QAVE_STAGING.KZART=NEW_DATA.KZART
                  AND P2P_QAVE_STAGING.ZAEHLER<=>NEW_DATA.ZAEHLER);


INSERT INTO P2P_QAVE_STAGING 
SELECT 
    QAVE.MANDANT,
    QAVE.PRUEFLOS,
    QAVE.KZART,
    QAVE.ZAEHLER,
    CAST(QAVE.VDATUM AS DATE) AS TS_VDATUM,
    CAST(QAVE.VAEDATUM AS DATE) AS TS_VAEDATUM
FROM <$QAVE> AS QAVE
	JOIN QALS AS QALS ON 1=1
		AND QAVE.MANDANT = QALS.MANDANT
		AND QAVE.PRUEFLOS = QALS.PRUEFLOS
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKPO_STAGING AS C 
    WHERE 1=1 
		AND QALS.MANDANT = C.MANDT
		AND QALS.EBELN = C.EBELN
		AND QALS.EBELP = C.EBELP)
;

SELECT ANALYZE_STATISTICS ('P2P_QAVE_STAGING'); 


