
DELETE FROM P2P_NAST_STAGING
WHERE EXISTS (SELECT 1 FROM <$NAST> AS NEW_DATA 
              WHERE P2P_NAST_STAGING.MANDT=NEW_DATA.MANDT AND P2P_NAST_STAGING.KAPPL=NEW_DATA.KAPPL AND P2P_NAST_STAGING.OBJKY=NEW_DATA.OBJKY
              AND P2P_NAST_STAGING.KSCHL=NEW_DATA.KSCHL AND P2P_NAST_STAGING.SPRAS=NEW_DATA.SPRAS AND  P2P_NAST_STAGING.PARVW<=>NEW_DATA.PARVW 
              AND P2P_NAST_STAGING.PARNR<=>NEW_DATA.PARNR AND P2P_NAST_STAGING.ERDAT=NEW_DATA.ERDAT AND P2P_NAST_STAGING.ERUHR=NEW_DATA.ERUHR);
          
INSERT INTO P2P_NAST_STAGING 
SELECT 
    NAST.MANDT,
    NAST.KAPPL,
    NAST.OBJKY,
    NAST.KSCHL,
    NAST.SPRAS,
    NAST.PARNR,
    NAST.PARVW,
    NAST.ERDAT,
    NAST.ERUHR,
    IFNULL(DD07T.DDTEXT,'') AS NACHA_TEXT,
    CAST(NAST.ERDAT AS DATE) AS TS_ERDAT,
    CAST(NAST.VSDAT AS DATE) AS TS_VSDAT,
    CAST(NAST.DATVR AS DATE) AS TS_DATVR,
    CAST(NAST.DATRE AS DATE) AS TS_DATRE
FROM 
    <$NAST> AS NAST
    LEFT JOIN DD07T AS DD07T ON 1=1
	    AND DD07T.DOMVALUE_L = NAST.NACHA 
	    AND DD07T.DOMNAME = 'NA_NACHA'
	    AND DD07T.DDLANGUAGE = '<%=primaryLanguageKey%>'
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKPO_STAGING AS C
    WHERE 1=1
        AND NAST.MANDT = C.MANDT 
        AND NAST.OBJKY = C.EBELN)
;

SELECT ANALYZE_STATISTICS ('P2P_NAST_STAGING'); 

