INSERT INTO _CEL_P2P_BSIK_ACTIVITIES_DELTA(
    _CASE_KEY
    ,MANDT
    ,EBELN
    ,EBELP
    ,ACTIVITY_DE
    ,ACTIVITY_EN
    ,EVENTTIME
    ,_SORTING
    , _CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY)
SELECT DISTINCT
      EKPO.MANDT || EKPO.EBELN || EKPO.EBELP AS _CASE_KEY
	,EKPO.MANDT AS MANDT
	,EKPO.EBELN AS EBELN
	,EKPO.EBELP AS EBELP
    ,'Lieferant erstellt Rechnung' AS ACTIVITY_DE
    ,'Vendor Creates Invoice' AS ACTIVITY_EN
    ,CAST(BKPF.BLDAT as DATE) + CAST('00:00:01' AS TIME) AS EVENTTIME
    ,2300 AS _SORTING
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,BKPF.MANDT || BKPF.BUKRS || BKPF.BELNR || BKPF.GJAHR AS _ACTIVITY_KEY
FROM 
    BSEG_DELTA AS BSEG
    JOIN BKPF ON 1=1
    	AND BKPF.MANDT = BSEG.MANDT
    	AND BKPF.BUKRS = BSEG.BUKRS
    	AND BKPF.GJAHR = BSEG.GJAHR 
    	AND BKPF.BELNR = BSEG.BELNR
        AND BSEG.BSCHL = '<%=postingKeyInvoice%>' -- data pool parameter, standard is 31 for vendor invoice
    JOIN RSEG ON 1=1 
        AND RSEG.MANDT=BKPF.MANDT
        AND SUBSTRING(BKPF.AWKEY,1,14) = RSEG.BELNR || CAST(RSEG.GJAHR AS VARCHAR(4)) 
        AND BKPF.BLDAT IS NOT NULL
     JOIN EKPO  ON 1=1
        AND RSEG.MANDT = EKPO.MANDT
        AND RSEG.EBELN = EKPO.EBELN
        AND RSEG.EBELP = EKPO.EBELP
     JOIN EKKO  ON 1=1
    	AND EKKO.MANDT = EKPO.MANDT
    	AND EKKO.EBELN = EKPO.EBELN
        AND EKKO.BSTYP = '<%=purchaseDoc%>'     
;


--Cleanup

DELETE FROM
    _CEL_P2P_BSIK_ACTIVITIES_DELTA
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_BSIK_ACTIVITIES_DELTA
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_BSIK_ACTIVITIES_DELTA
WHERE
    YEAR(EVENTTIME) > 5000 
;

-- Statistics
SELECT ANALYZE_STATISTICS('_CEL_P2P_BSIK_ACTIVITIES_DELTA');


-- Merge
INSERT INTO _CEL_P2P_BSIK_ACTIVITIES_DELTA
SELECT *
FROM _CEL_P2P_BSIK_ACTIVITIES_DELTA AS NEW_ACTIVITIES
 WHERE NOT EXISTS (
                    SELECT 1 FROM _CEL_P2P_BSIK_ACTIVITIES_DELTA AS OLD_ACTIVITIES
                    WHERE NEW_ACTIVITIES._CASE_KEY=OLD_ACTIVITIES._CASE_KEY
                      AND NEW_ACTIVITIES.ACTIVITY_EN=OLD_ACTIVITIES.ACTIVITY_EN
                        AND NEW_ACTIVITIES._ACTIVITY_KEY=OLD_ACTIVITIES._ACTIVITY_KEY 
                    );

