
INSERT INTO _CEL_P2P_BSAK_ACTIVITIES_DELTA(
    _CASE_KEY 
    ,MANDT
    ,EBELN
    ,EBELP
    , ACTIVITY_DE 
    , ACTIVITY_EN 
    , EVENTTIME 
    , _SORTING 
    , USER_NAME 
    , USER_TYPE 
    , TRANSACTION_CODE 
    , _CELONIS_CHANGE_DATE
    , _ACTIVITY_KEY )
SELECT  DISTINCT
	EKPO.MANDT || EKPO.EBELN || EKPO.EBELP AS  _CASE_KEY 
	,EKPO.MANDT AS  MANDT 
	,EKPO.EBELN AS  EBELN 
	,EKPO.EBELP AS  EBELP 
	,'Gleiche Rechnung aus' AS  ACTIVITY_DE 
	,'Clear Invoice' AS  ACTIVITY_EN 
	,CASE 
  		WHEN CAST(BKPF_Z. CPUDT  AS DATE) = CAST(BSEG. AUGDT  AS DATE)
  		THEN CAST(BKPF_Z. CPUDT  AS DATE) + CAST(BKPF_Z. CPUTM  as TIME)
  		ELSE CAST(BSEG. AUGDT  AS DATE) + CAST('23:59:59' as TIME)
  	END AS  EVENTTIME 
	,2500 AS  _SORTING 
	,BKPF_Z.USNAM AS  USER_NAME 
	,USR02.USTYP AS  USER_TYPE 
	,BKPF_Z.TCODE AS  TRANSACTION_CODE 
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,BKPF. MANDT  || BKPF. BUKRS  || BKPF. BELNR  || BKPF. GJAHR  AS  _ACTIVITY_KEY 
FROM 
    BSEG_DELTA AS BSEG
    JOIN BKPF 
    ON 1=1
    	AND BKPF.MANDT = BSEG.MANDT
    	AND BKPF.BUKRS = BSEG.BUKRS
    	AND BKPF.GJAHR = BSEG.GJAHR 
    	AND BKPF.BELNR = BSEG.BELNR
        AND BSEG.BSCHL = '<%=postingKeyInvoice%>' -- data pool parameter, standard is 31 for vendor invoice
    JOIN RSEG ON 1=1
        AND RSEG.MANDT=BKPF.MANDT
        AND SUBSTRING(BKPF.AWKEY,1,14) = RSEG.BELNR || CAST(RSEG.GJAHR AS VARCHAR(4)) 
        AND BSEG.AUGBL IS NOT NULL
    JOIN EKPO  ON 1=1
        AND RSEG.MANDT = EKPO.MANDT
        AND RSEG.EBELN = EKPO.EBELN
        AND RSEG.EBELP = EKPO.EBELP
    JOIN EKKO  ON 1=1
    	AND EKKO.MANDT = EKPO.MANDT
    	AND EKKO.EBELN = EKPO.EBELN
        AND EKKO.BSTYP = '<%=purchaseDoc%>'
    LEFT JOIN BKPF AS BKPF_Z ON 1=1
		AND BSEG.MANDT = BKPF_Z.MANDT
		AND BSEG.BUKRS = BKPF_Z.BUKRS
		AND BSEG.AUGBL = BKPF_Z.BELNR
		AND BSEG.AUGGJ = BKPF_Z.GJAHR
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND BKPF_Z.MANDT = USR02.MANDT
		AND BKPF_Z.USNAM = USR02.BNAME
	    AND BKPF_Z.CPUDT IS NOT NULL
;




--Cleanup

DELETE FROM
    _CEL_P2P_BSIK_ACTIVITIES_DELTA
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_BSIK_ACTIVITIES_DELTA
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_BSIK_ACTIVITIES_DELTA
WHERE
    YEAR(EVENTTIME) > 5000 
;

-- Statistics
SELECT ANALYZE_STATISTICS('_CEL_P2P_BSIK_ACTIVITIES_DELTA');


-- Merge
INSERT INTO _CEL_P2P_BSIK_ACTIVITIES_DELTA
SELECT *
FROM _CEL_P2P_BSIK_ACTIVITIES_DELTA AS NEW_ACTIVITIES
 WHERE NOT EXISTS (
                    SELECT 1 FROM _CEL_P2P_BSIK_ACTIVITIES_DELTA AS OLD_ACTIVITIES
                    WHERE NEW_ACTIVITIES._CASE_KEY=OLD_ACTIVITIES._CASE_KEY
                      AND NEW_ACTIVITIES.ACTIVITY_EN=OLD_ACTIVITIES.ACTIVITY_EN
                        AND NEW_ACTIVITIES._ACTIVITY_KEY=OLD_ACTIVITIES._ACTIVITY_KEY 
                           AND NEW_ACTIVITIES.EVENTTIME=OLD_ACTIVITIES.EVENTTIME
                     AND  NEW_ACTIVITIES.TRANSACTION_CODE <=> OLD_ACTIVITIES.TRANSACTION_CODE
                    );

