-- Includes the following activities

--        Changes PO Item
--        Changes PO 
--        Changes to Contract
--        Change Requested Delivery Date 
--        Change Confirmed Delivery Date 
--        Set/Remove Payment Block


--Cleanup

DELETE FROM
    _CEL_P2P_CDHDR_ACTIVITIES_DELTA
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_CDHDR_ACTIVITIES_DELTA
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_CDHDR_ACTIVITIES_DELTA
WHERE
    YEAR(EVENTTIME) > 5000 
;

-- Statistics
SELECT ANALYZE_STATISTICS('_CEL_P2P_CDHDR_ACTIVITIES_DELTA');


-- Merge
INSERT INTO _CEL_P2P_CDHDR_ACTIVITIES
SELECT *
FROM _CEL_P2P_CDHDR_ACTIVITIES_DELTA AS NEW_ACTIVITIES
 WHERE NOT EXISTS (
                    SELECT 1 FROM _CEL_P2P_CDHDR_ACTIVITIES AS OLD_ACTIVITIES
                    WHERE NEW_ACTIVITIES._CASE_KEY=OLD_ACTIVITIES._CASE_KEY
                      AND NEW_ACTIVITIES.ACTIVITY_EN=OLD_ACTIVITIES.ACTIVITY_EN
                        AND NEW_ACTIVITIES._ACTIVITY_KEY=OLD_ACTIVITIES._ACTIVITY_KEY 
                    );
