DELETE FROM PR_CDHDR_CDPOS
WHERE EXISTS (SELECT 1 FROM <$CDPOS> as NEW_DATA 
              WHERE PR_CDHDR_CDPOS.MANDANT = NEW_DATA.MANDANT 
              AND PR_CDHDR_CDPOS.OBJECTCLAS = NEW_DATA.OBJECTCLAS
              AND PR_CDHDR_CDPOS.OBJECTID = NEW_DATA.OBJECTID
              AND PR_CDHDR_CDPOS.CHANGENR = NEW_DATA.CHANGENR
              AND PR_CDHDR_CDPOS.TABNAME = NEW_DATA.TABNAME
              AND PR_CDHDR_CDPOS.TABKEY = NEW_DATA.TABKEY
              AND PR_CDHDR_CDPOS.FNAME = NEW_DATA.FNAME
               AND PR_CDHDR_CDPOS.CHNGIND = NEW_DATA.CHNGIND
              );


INSERT INTO PR_CDHDR_CDPOS
	SELECT
		CHANGES.MANDANT
	,CHANGES.FNAME
	,CHANGES.TABNAME
	,CHANGES.TABKEY
	,CHANGES.VALUE_OLD
	,CHANGES.VALUE_NEW
	,CHANGES.UDATE  
  ,CHANGES.UTIME 
	,CHANGES.CHANGENR
  ,CHANGES.CHNGIND
	,CHANGES.TCODE
	,CHANGES.OBJECTCLAS
	,CHANGES.OBJECTID
	,CHANGES.USERNAME
	FROM TMP_PR_CDHDR_CDPOS AS CHANGES 
;
    SELECT ANALYZE_STATISTICS ('PR_CDHDR_CDPOS'); 

