
DELETE FROM PR_EKPO_STAGING
WHERE EXISTS (SELECT 1 FROM <$EKPO> as NEW_DATA 
              WHERE PR_EKPO_STAGING.MANDT = NEW_DATA.MANDT 
              AND PR_EKPO_STAGING.EBELN = NEW_DATA.EBELN
              AND PR_EKPO_STAGING.EBELP = NEW_DATA.EBELP
              );

INSERT INTO PR_EKPO_STAGING
SELECT DISTINCT
     EKPO.MANDT
    ,EKPO.EBELN
    ,EKPO.EBELP
 	,CAST(EKPO.ABDAT AS DATE) AS TS_ABDAT
    ,CAST(EKPO.AEDAT AS DATE) AS TS_AEDAT 
    ,CAST(EKPO.AGDAT AS DATE) AS TS_AGDAT 
    ,CAST(EKPO.DPDAT AS DATE) AS TS_DPDAT 
    ,CAST(EKPO.DRDAT AS DATE) AS TS_DRDAT 
    ,CAST(EKPO.EILDT AS DATE) AS TS_EILDT 
    ,CAST(EKPO.J_1AIDATEP AS DATE) AS TS_J_1AIDATEP 
    ,CAST(EKPO.LEWED AS DATE) AS TS_LEWED
    ,CAST(EKPO.NFABD AS DATE) AS TS_NFABD 
    ,CAST(EKPO.NLABD AS DATE) AS TS_NLABD 
    ,CAST(EKPO.PRDAT AS DATE) AS TS_PRDAT
    ,IFNULL(EKPO.WERKS,'_CEL_NULL_JOIN') AS "WERKS_JOIN"
    ,T023T.WGBEZ AS "MATKL_TEXT"
	,MAKT.MAKTX AS "MATNR_TEXT"
	,T001.BUTXT AS "BUKRS_TEXT"
	,T001W.NAME1 AS "WERKS_TEXT"
	,T001L.LGOBE AS "LGORT_TEXT"
	,PSTYP.PTEXT AS "PSTYP_TEXT"
	,T163I.KNTTX AS "KNTTP_TEXT"
  ,CASE 
		WHEN EKKO.WAERS = '<%=currency%>' THEN EKPO.NETWR*ISNULL(TCURX.TDEC,1) 
  		WHEN TCURR_CC.UKURS < 0 THEN (EKPO.NETWR*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		WHEN TCURR_CC.UKURS > 0 THEN (EKPO.NETWR*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
	END AS NETWR_CONVERTED
    ,EKKO.LIFNR,
     EKKO.EKORG
FROM 
      <$EKPO> AS EKPO
    INNER JOIN EKKO AS EKKO ON
    		EKKO.MANDT = EKPO.MANDT
    		AND EKKO.EBELN = EKPO.EBELN  
            AND EKKO.BSTYP = 'F'
 	LEFT JOIN PR_TCURR_CC AS TCURR_CC ON 1=1
		AND TCURR_CC.MANDT = EKKO.MANDT
		AND TCURR_CC.TCURR = '<%=currency%>'
		AND TCURR_CC.FCURR = EKKO.WAERS                                             
		AND EKKO.AEDAT >= TCURR_CC.VALID_START AND EKKO.AEDAT  < TCURR_CC.VALID_END
        AND TCURR_CC.KURST = '<%=exchangeRateType%>' 
	LEFT JOIN PR_TCURF_CC AS TCURF_CC ON 1=1
		AND TCURR_CC.MANDT = TCURF_CC.MANDT
		AND TCURR_CC.TCURR = TCURF_CC.TCURR
		AND TCURR_CC.FCURR = TCURF_CC.FCURR
		AND TCURR_CC.KURST = TCURF_CC.KURST
        AND EKKO.AEDAT  >= TCURF_CC.VALID_START	
		AND EKKO.AEDAT  < TCURF_CC.VALID_END
	LEFT JOIN (
		SELECT 
			TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
			TCURX) AS TCURX ON 1=1
		AND EKKO.WAERS  = TCURX.CURRKEY
	LEFT JOIN MAKT AS MAKT ON 1=1
		AND EKPO.MANDT = MAKT.MANDT
		AND EKPO.MATNR = MAKT.MATNR
		AND MAKT.SPRAS = '<%=primaryLanguageKey%>' 
	LEFT JOIN T023T AS T023T ON 1=1
		AND EKPO.MANDT = T023T.MANDT
		AND EKPO.MATKL = T023T.MATKL
		AND T023T.SPRAS = '<%=primaryLanguageKey%>'
	LEFT JOIN T001 AS T001 ON 1=1
		AND EKPO.MANDT = T001.MANDT
		AND EKPO.BUKRS = T001.BUKRS
	LEFT JOIN T001W AS T001W ON 1=1
		AND EKPO.MANDT = T001W.MANDT
		AND EKPO.WERKS = T001W.WERKS
	LEFT JOIN T001L AS T001L ON 1=1
		AND EKPO.MANDT = T001L.MANDT
		AND EKPO.WERKS = T001L.WERKS
		AND EKPO.LGORT = T001L.LGORT
	LEFT JOIN T163Y AS PSTYP ON 1=1
		AND PSTYP.MANDT = EKPO.MANDT
		AND PSTYP.PSTYP = EKPO.PSTYP
		AND PSTYP.SPRAS = '<%=primaryLanguageKey%>'
	LEFT JOIN T163I AS T163I ON 1=1
	    AND T163I.MANDT = EKPO.MANDT
		AND T163I.KNTTP = EKPO.KNTTP	 
		AND T163I.SPRAS = '<%=primaryLanguageKey%>'
           WHERE EXISTS (
    SELECT 1 
    FROM PR_EBAN_STAGING AS C
    WHERE 1=1 
        AND EKPO.MANDT = C.MANDT
        AND EKPO.EBELN = C.EBELN
        AND EKPO.EBELP = C.EBELP)
         ;
     SELECT ANALYZE_STATISTICS ('PR_EKPO_STAGING'); 




        
