
INSERT INTO _CEL_PR_EBAN_ACTIVITIES_DELTA (
	_CASE_KEY
	,MANDT
	,BANFN
	,BNFPO
	,ACTIVITY_DE
	,ACTIVITY_EN
	,EVENTTIME
	,_SORTING
    ,USER_NAME
    ,USER_TYPE
    ,_ACTIVITY_KEY)
SELECT
	  EBAN.MANDT || EBAN.BANFN || EBAN.BNFPO AS _CASE_KEY
	,EBAN.MANDT AS MANDT
	,EBAN.BANFN AS BANFN
	,EBAN.BNFPO AS BNFPO
	,'Lege BANF Position an' AS ACTIVITY_DE
	,'Create Purchase Requisition Item' AS ACTIVITY_EN
	,CASE 
	     WHEN CHANGES.UDATE IS NOT NULL THEN CAST(CHANGES.UDATE AS DATE) + CAST(CHANGES.UTIME AS TIME)
        ELSE CAST(EBAN.BADAT AS DATE) + CAST('00:00:01' AS TIME)
	END AS EVENTTIME
	,200 AS _SORTING
	,EBAN.ERNAM AS USER_NAME
	,USR02.USTYP AS USER_TYPE
     ,EBAN.MANDT || EBAN.BANFN || EBAN.BNFPO AS _ACTIVITY_KEY
FROM 
	<$EBAN> AS EBAN 
	  LEFT JOIN PR_CDHDR_CDPOS AS CHANGES ON 1=1
		AND EBAN.MANDT = CHANGES.MANDANT
		AND EBAN.MANDT + EBAN.BANFN + EBAN.BNFPO = CHANGES.TABKEY
		AND CHANGES.OBJECTCLAS = 'BANF'
		AND CHANGES.CHNGIND = 'I'  
	LEFT JOIN USR02 AS USR02 ON 1=1
        AND EBAN.MANDT = USR02.MANDT 
        AND EBAN.ERNAM = USR02.BNAME
;




--Cleanup

DELETE FROM
    _CEL_PR_EBAN_ACTIVITIES_DELTA
WHERE
    "EVENTTIME" IS NULL;

DELETE FROM
    _CEL_PR_EBAN_ACTIVITIES_DELTA
WHERE
    "ACTIVITY_EN" IS NULL AND
    "ACTIVITY_DE" IS NULL;

DELETE FROM
    _CEL_PR_EBAN_ACTIVITIES_DELTA
WHERE
    YEAR(EVENTTIME) > 5000 
;

-- Statistics
SELECT ANALYZE_STATISTICS('_CEL_PR_EBAN_ACTIVITIES_DELTA');


-- Merge
INSERT INTO _CEL_PR_EBAN_ACTIVITIES
SELECT *
FROM _CEL_PR_EBAN_ACTIVITIES_DELTA AS NEW_ACTIVITIES
 WHERE NOT EXISTS (
                    SELECT 1 FROM _CEL_PR_EBAN_ACTIVITIES AS OLD_ACTIVITIES
                    WHERE NEW_ACTIVITIES._CASE_KEY=OLD_ACTIVITIES._CASE_KEY
                      AND NEW_ACTIVITIES.ACTIVITY_EN=OLD_ACTIVITIES.ACTIVITY_EN
                        AND NEW_ACTIVITIES._ACTIVITY_KEY=OLD_ACTIVITIES._ACTIVITY_KEY 
                    )

;
