DROP TABLE IF EXISTS TMP_PR_EKKO_EKPO;

CREATE TABLE TMP_PR_EKKO_EKPO AS(
	SELECT
    	EKKO.MANDT
	    ,EKKO.EBELN
    	,EKPO.EBELP
        ,EKKO.MANDT || EKKO.EBELN AS "TABKEY_EKKO"
    	,EKKO.MANDT || EKKO.EBELN || EKPO.EBELP AS "TABKEY_EKPO"
        ,EKPO.MANDT || EKPO.BANFN || EKPO.BNFPO AS "TABKEY_EBAN"
	    ,CAST(EKKO.AEDAT AS DATE) AS "AEDAT"
    	,EKKO.ERNAM
        ,EKKO.EKORG
        ,EKKO.EKGRP
        ,EKPO.KONNR
    	,EKPO.KTPNR
    	,EKKO.BSTYP
    	,EKPO.BANFN
    	,EKPO.BNFPO
    	,EKKO.WAERS
    	,EKKO.LIFNR
    	,EKKO.BUKRS
    	,EKPO.NETWR
        ,EKPO.NETPR
    	,EKKO.WKURS
        ,EKPO.MATNR
        ,EKPO.WERKS
    FROM 
        EKKO AS EKKO
    	JOIN EKPO AS EKPO ON
    		EKKO.MANDT = EKPO.MANDT
    		AND EKKO.EBELN = EKPO.EBELN
    WHERE 
        EKKO.BSTYP = 'F'
);

SELECT ANALYZE_STATISTICS('TMP_PR_EKKO_EKPO') ;
