DROP TABLE IF EXISTS TMP_PR_EBAN_EKKO_EKPO;

CREATE TABLE TMP_PR_EBAN_EKKO_EKPO AS(
SELECT 
	EBAN.MANDT
	,EBAN.BANFN 
	,EBAN.BNFPO 
  ,EBAN.ERNAM
  ,EBAN.BADAT
	,EKKO_EKPO.MANDT AS "EKKOMANDT" 
  ,EKKO_EKPO.EBELN
	,EKKO_EKPO.EBELP
	,EBAN.PREIS*EBAN.MENGE AS "NETWR"    
	,EBAN.WAERS
	,CAST(EBAN.ERDAT AS DATE) AS "ERDAT"
	,CAST(EKKO_EKPO.AEDAT AS DATE) AS "EKKOAEDAT"
	,EKKO_EKPO.ERNAM AS "EKKOERNAM"
  ,EKKO_EKPO.NETWR AS "EKPONETWR"
  ,EKKO_EKPO.WAERS AS "EKKOWAERS"
  ,EKKO_EKPO.WKURS
  ,EKKO_EKPO.TABKEY_EKKO
	,EKKO_EKPO.TABKEY_EKPO
	,EBAN.MANDT || EBAN.BANFN || EBAN.BNFPO AS "_CASE_KEY"
FROM 
    EBAN AS EBAN
	LEFT JOIN TMP_PR_EKKO_EKPO AS EKKO_EKPO ON 1=1 
		AND EBAN.MANDT = EKKO_EKPO.MANDT
		AND EBAN.EBELN = EKKO_EKPO.EBELN
		AND EBAN.EBELP = EKKO_EKPO.EBELP);

SELECT ANALYZE_STATISTICS('TMP_PR_EBAN_EKKO_EKPO') ;


