
DROP TABLE IF EXISTS EBAN_CURR_TMP;
    
CREATE TABLE EBAN_CURR_TMP AS(
SELECT 
	 E.MANDT
	,E.BANFN
	,E.BNFPO
  ,E.EBELN
	,E.EBELP
	,E.WAERS
	,E.NETWR
	,CASE 
	    WHEN E.WAERS = '<%=currency%>' THEN E.NETWR*ISNULL(TCURX_NETWR.TDEC,1) 
		WHEN TCURR_CC_NETWR.UKURS < 0 THEN (E.NETWR*ISNULL(TCURX_NETWR.TDEC,1))*(1/ABS(TCURR_CC_NETWR.UKURS)/(CASE WHEN COALESCE(TCURF_CC_NETWR.FFACT, TCURR_CC_NETWR.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_NETWR.FFACT, TCURR_CC_NETWR.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC_NETWR.TFACT, TCURR_CC_NETWR.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_NETWR.TFACT, TCURR_CC_NETWR.TFACT) END)
  		WHEN TCURR_CC_NETWR.UKURS > 0 THEN (E.NETWR*ISNULL(TCURX_NETWR.TDEC,1))*(TCURR_CC_NETWR.UKURS/CASE WHEN COALESCE(TCURF_CC_NETWR.FFACT, TCURR_CC_NETWR.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_NETWR.FFACT, TCURR_CC_NETWR.FFACT) END*CASE WHEN COALESCE(TCURF_CC_NETWR.TFACT, TCURR_CC_NETWR.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_NETWR.TFACT, TCURR_CC_NETWR.TFACT) END)
	END AS NETWR_CONVERTED 
	,CASE 
	    WHEN E.EKKOWAERS = '<%=currency%>' THEN E.EKPONETWR*ISNULL(TCURX_EKPO_NETWR.TDEC,1) 
		WHEN TCURR_CC_EKPO_NETWR.UKURS < 0 THEN (E.EKPONETWR*ISNULL(TCURX_EKPO_NETWR.TDEC,1))*(1/ABS(TCURR_CC_EKPO_NETWR.UKURS)/(CASE WHEN COALESCE(TCURF_CC_EKPO_NETWR.FFACT, TCURR_CC_EKPO_NETWR.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_EKPO_NETWR.FFACT, TCURR_CC_EKPO_NETWR.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC_EKPO_NETWR.TFACT, TCURR_CC_EKPO_NETWR.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_EKPO_NETWR.TFACT, TCURR_CC_EKPO_NETWR.TFACT) END)
    	WHEN TCURR_CC_EKPO_NETWR.UKURS > 0 THEN (E.EKPONETWR*ISNULL(TCURX_EKPO_NETWR.TDEC,1))*(TCURR_CC_EKPO_NETWR.UKURS/CASE WHEN COALESCE(TCURF_CC_EKPO_NETWR.FFACT, TCURR_CC_EKPO_NETWR.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_EKPO_NETWR.FFACT, TCURR_CC_EKPO_NETWR.FFACT) END*CASE WHEN COALESCE(TCURF_CC_EKPO_NETWR.TFACT, TCURR_CC_EKPO_NETWR.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC_EKPO_NETWR.TFACT, TCURR_CC_EKPO_NETWR.TFACT) END)
	END AS EKPO_NETWR_CONVERTED
FROM 
    TMP_PR_EBAN_EKKO_EKPO AS E
	LEFT JOIN PR_TCURR_CC AS TCURR_CC_NETWR ON 1=1 -- NETWR in EBAN
	    AND TCURR_CC_NETWR.MANDT = E.MANDT
	    AND TCURR_CC_NETWR.TCURR = '<%=currency%>'
		AND TCURR_CC_NETWR.FCURR = E.WAERS
		AND TCURR_CC_NETWR.KURST = '<%=exchangeRateType%>'
		AND E.ERDAT >= TCURR_CC_NETWR.VALID_START AND E.ERDAT < TCURR_CC_NETWR.VALID_END
	LEFT JOIN PR_TCURF_CC AS TCURF_CC_NETWR ON 1=1
	    AND TCURR_CC_NETWR.MANDT = TCURF_CC_NETWR.MANDT
		AND TCURR_CC_NETWR.TCURR = TCURF_CC_NETWR.TCURR
		AND TCURR_CC_NETWR.FCURR = TCURF_CC_NETWR.FCURR
		AND TCURR_CC_NETWR.KURST = TCURF_CC_NETWR.KURST
        AND E.ERDAT >= TCURF_CC_NETWR.VALID_START AND E.ERDAT < TCURF_CC_NETWR.VALID_END
	LEFT JOIN (
		SELECT 
		    TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
		    TCURX) AS TCURX_NETWR ON 1=1
		AND TCURR_CC_NETWR.FCURR = TCURX_NETWR.CURRKEY
	LEFT JOIN PR_TCURR_CC AS TCURR_CC_EKPO_NETWR ON 1=1  -- NETWR in EKPO
	    AND TCURR_CC_EKPO_NETWR.MANDT = E.MANDT
	    AND TCURR_CC_EKPO_NETWR.TCURR = '<%=currency%>'
		AND TCURR_CC_EKPO_NETWR.FCURR = E.EKKOWAERS
		AND TCURR_CC_EKPO_NETWR.KURST = '<%=exchangeRateType%>'
		AND E.EKKOAEDAT >= TCURR_CC_EKPO_NETWR.VALID_START AND E.EKKOAEDAT < TCURR_CC_EKPO_NETWR.VALID_END
	LEFT JOIN PR_TCURF_CC AS TCURF_CC_EKPO_NETWR ON 1=1
	    AND TCURR_CC_EKPO_NETWR.MANDT = TCURF_CC_EKPO_NETWR.MANDT
		AND TCURR_CC_EKPO_NETWR.TCURR = TCURF_CC_EKPO_NETWR.TCURR
		AND TCURR_CC_EKPO_NETWR.FCURR = TCURF_CC_EKPO_NETWR.FCURR
		AND TCURR_CC_EKPO_NETWR.KURST = TCURF_CC_EKPO_NETWR.KURST
        AND E.EKKOAEDAT >= TCURF_CC_EKPO_NETWR.VALID_START AND E.EKKOAEDAT < TCURF_CC_EKPO_NETWR.VALID_END
	LEFT JOIN (
		SELECT 
		    TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
		    TCURX) AS TCURX_EKPO_NETWR ON 1=1
		AND TCURR_CC_EKPO_NETWR.FCURR = TCURX_EKPO_NETWR.CURRKEY);

SELECT ANALYZE_STATISTICS('EBAN_CURR_TMP') ;
