--In order to make the connector compatible with DELTA TRANSFORMATIONS this auxiliary changes tableshould not be dropped after the full transformations

DROP TABLE IF EXISTS PR_CDHDR_CDPOS;

CREATE TABLE PR_CDHDR_CDPOS AS (
	SELECT
	CDPOS.MANDANT
	,CDPOS.FNAME
	,CDPOS.TABNAME
	,CDPOS.TABKEY
	,CDPOS.VALUE_OLD
	,CDPOS.VALUE_NEW
	,CDHDR.UDATE  
  ,CDHDR.UTIME 
	,CDHDR.CHANGENR
  ,CDPOS.CHNGIND
	,CDHDR.TCODE
	,CDPOS.OBJECTCLAS
	,CDPOS.OBJECTID
	,CDHDR.USERNAME
	FROM CDHDR AS CDHDR
	    JOIN CDPOS AS CDPOS ON
		    CDPOS.MANDANT = CDHDR.MANDANT AND
		    CDPOS.OBJECTCLAS = CDHDR.OBJECTCLAS AND
		    CDPOS.OBJECTID = CDHDR.OBJECTID AND
		    CDPOS.CHANGENR = CDHDR.CHANGENR
	WHERE 1=1
    AND CDPOS.CHNGIND IN ('U', 'I')
		AND CDPOS.TABNAME IN ('EBAN','EKKO','EKPO')) 
   ORDER BY  MANDANT 
              ,OBJECTCLAS   
              ,OBJECTID
              , CHANGENR
              , TABNAME
              , TABKEY
              , FNAME
              , CHNGIND
    ;

  SELECT ANALYZE_STATISTICS ('PR_CDHDR_CDPOS'); 

