
INSERT INTO _CEL_PR_EBAN_ACTIVITIES (
	_CASE_KEY
	,MANDT
	,BANFN
	,BNFPO
	,ACTIVITY_DE
	,ACTIVITY_EN
	,EVENTTIME
	,_SORTING
    ,USER_NAME
    ,USER_TYPE
    ,_ACTIVITY_KEY)
SELECT 
	EBAN._CASE_KEY AS _CASE_KEY
	,EBAN.MANDT AS MANDT
	,EBAN.BANFN AS BANFN
	,EBAN.BNFPO AS BNFPO
	,'Lege BANF Position an' AS ACTIVITY_DE
	,'Create Purchase Requisition Item' AS ACTIVITY_EN
	,CASE 
	     WHEN CHANGES.UDATE IS NOT NULL THEN CAST(CHANGES.UDATE AS DATE) + CAST(CHANGES.UTIME AS TIME)
        ELSE CAST(EBAN.BADAT AS DATE) + CAST('00:00:01' AS TIME)
	END AS EVENTTIME
	,200 AS _SORTING
	,EBAN.ERNAM AS USER_NAME
	,USR02.USTYP AS USER_TYPE
    ,EBAN._CASE_KEY AS _ACTIVITY_KEY
FROM 
	TMP_PR_EBAN_EKKO_EKPO AS EBAN
  LEFT JOIN PR_CDHDR_CDPOS AS CHANGES ON 1=1
		AND EBAN.MANDT = CHANGES.MANDANT
		AND EBAN.MANDT + EBAN.BANFN + EBAN.BNFPO = CHANGES.TABKEY
		AND CHANGES.OBJECTCLAS = 'BANF'
		AND CHANGES.CHNGIND = 'I'  
		AND CHANGES.TABNAME = 'EBAN'	
	LEFT JOIN USR02 AS USR02 ON 1=1
        AND EBAN.MANDT = USR02.MANDT 
        AND EBAN.ERNAM = USR02.BNAME
    ;

