
INSERT INTO _CEL_PR_EKPO_ACTIVITIES (
	_CASE_KEY
	,MANDT
	,BANFN
	,BNFPO
	,ACTIVITY_DE
	,ACTIVITY_EN
	,EVENTTIME
	,_SORTING
	,USER_NAME
	,USER_TYPE
    ,_ACTIVITY_KEY
	)
SELECT
	EBAN._CASE_KEY AS _CASE_KEY
	,EBAN.MANDT AS MANDT
	,EBAN.BANFN AS BANFN
	,EBAN.BNFPO AS BNFPO
	,'Lege Bestellposition an' AS ACTIVITY_DE
	,'Create Purchase Order Item' AS ACTIVITY_EN
	,CASE 
		WHEN CHANGE_ITEM.UDATE IS NOT NULL THEN CAST(CHANGE_ITEM.UDATE AS DATE) + CAST(CHANGE_ITEM.UTIME AS TIME) 
		WHEN CHANGE_HEADER.UDATE IS NOT NULL THEN CAST(CHANGE_HEADER.UDATE AS DATE) + CAST(CHANGE_HEADER.UTIME AS TIME)
		ELSE CAST(EBAN.EKKOAEDAT AS DATE) + CAST('00:00:01' AS TIME)
	END AS EVENTTIME
	,500 AS _SORTING
    ,COALESCE(CHANGE_ITEM.USERNAME, CHANGE_HEADER.USERNAME) AS USER_NAME
	,COALESCE(USR02_POS.USTYP, USR02_HEAD.USTYP) AS USER_TYPE
    ,EBAN.MANDT || EBAN.EBELN || EBAN.EBELP  AS _ACTIVITY_KEY
FROM 
	TMP_PR_EBAN_EKKO_EKPO AS EBAN
	LEFT JOIN PR_CDHDR_CDPOS AS CHANGE_ITEM
    ON 1=1 
    AND CHANGE_ITEM.TABKEY = EBAN.MANDT || EBAN.EBELN || EBAN.EBELP
		AND CHANGE_ITEM.TABNAME = 'EKPO'
		AND CHANGE_ITEM.CHNGIND = 'I'
		AND CHANGE_ITEM.FNAME = 'KEY'
  LEFT JOIN PR_CDHDR_CDPOS AS CHANGE_HEADER
    ON 1=1 
		AND CHANGE_HEADER.TABKEY=EBAN.MANDT || EBAN.EBELN
		AND CHANGE_HEADER.TABNAME = 'EKKO'
		AND CHANGE_HEADER.CHNGIND = 'I'
		AND CHANGE_HEADER.FNAME = 'KEY'
	LEFT JOIN USR02  AS USR02_POS ON 1=1
    AND CHANGE_ITEM.MANDANT = USR02_POS.MANDT
    AND CHANGE_ITEM.USERNAME = USR02_POS.BNAME
  LEFT JOIN USR02  AS USR02_HEAD ON 1=1
    AND CHANGE_HEADER.MANDANT = USR02_HEAD.MANDT
    AND CHANGE_HEADER.USERNAME = USR02_HEAD.BNAME
WHERE EBAN.EBELP IS NOT NULL;


