
DROP VIEW IF EXISTS PR_EBAN;

CREATE VIEW PR_EBAN AS 
SELECT 
     EBAN.* 
    ,PR_EBAN_STAGING.EKORG_TEXT
    ,PR_EBAN_STAGING.EKGRP_TEXT
    ,PR_EBAN_STAGING.WERKS_TEXT
    ,PR_EBAN_STAGING.MATNR_TEXT
    ,PR_EBAN_STAGING.MATKL_TEXT
    ,PR_EBAN_STAGING.BSTYP_TEXT
    ,PR_EBAN_STAGING.PSTYP_TEXT
    ,PR_EBAN_STAGING.ESTKZ_TEXT
    ,PR_EBAN_STAGING.STATU_TEXT
    ,PR_EBAN_STAGING.NETWR_CONVERTED
    ,PR_EBAN_STAGING.CONCATKEY
    ,PR_EBAN_STAGING.SMTP_ADDR_ERNAM
    ,PR_EBAN_STAGING.FRGGR_TEXT
    ,PR_EBAN_STAGING.REQUISITIONER_NAME
    ,PR_EBAN_STAGING.FRGC1
    ,PR_EBAN_STAGING.FRGC1_APPROVER  
    ,PR_EBAN_STAGING.FRGC2
    ,PR_EBAN_STAGING.FRGC2_APPROVER  
    ,PR_EBAN_STAGING.FRGC3
    ,PR_EBAN_STAGING.FRGC3_APPROVER  
    ,PR_EBAN_STAGING.FRGC4
    ,PR_EBAN_STAGING.FRGC4_APPROVER  
    ,PR_EBAN_STAGING.FRGC5
    ,PR_EBAN_STAGING.FRGC5_APPROVER  
    ,PR_EBAN_STAGING.FRGC6
    ,PR_EBAN_STAGING.FRGC6_APPROVER  
    ,PR_EBAN_STAGING.FRGC7
    ,PR_EBAN_STAGING.FRGC7_APPROVER  
    ,PR_EBAN_STAGING.FRGC8
    ,PR_EBAN_STAGING.FRGC8_APPROVER  
    ,PR_EBAN_STAGING.P2P_CONTRACT_RECOMMENDATION_KEY
    ,PR_EBAN_STAGING.EPOCH
FROM 
    EBAN AS EBAN JOIN 
    PR_EBAN_STAGING ON 1=1
     AND EBAN.MANDT = PR_EBAN_STAGING.MANDT
     AND EBAN.BANFN = PR_EBAN_STAGING.BANFN
      AND EBAN.BNFPO = PR_EBAN_STAGING.BNFPO
        ;
