-- Query No: 1
DROP VIEW IF EXISTS PR_EBAN_HEADER;

-- Query No: 2
CREATE VIEW PR_EBAN_HEADER AS 
SELECT 
      P.MANDT
    , P.BANFN
    ,MAX(P.EPOCH) AS EPOCH
FROM PR_EBAN_STAGING AS P
GROUP BY   P.MANDT,  P.BANFN
;
