DROP TABLE IF EXISTS PR_EKKO_STAGING;

CREATE TABLE PR_EKKO_STAGING AS 
SELECT
    EKKO.MANDT,
    EKKO.EBELN
    ,CAST(EKKO.AEDAT AS DATE) AS TS_AEDAT
    ,CAST(EKKO.ANGDT AS DATE) AS TS_ANGDT
    ,CAST(EKKO.BEDAT AS DATE) AS TS_BEDAT
    ,CAST(EKKO.BNDDT AS DATE) AS TS_BNDDT
    ,CAST(EKKO.BWBDT AS DATE) AS TS_BWBDT
    ,CAST(EKKO.DPDAT AS DATE) AS TS_DPDAT
    ,CAST(EKKO.EQ_EINDT AS DATE) AS TS_EQ_EINDT
    ,CAST(EKKO.GWLDT AS DATE) AS TS_GWLDT
    ,CAST(EKKO.IHRAN AS DATE) AS TS_IHRAN
    ,CAST(EKKO.KDATB AS DATE) AS TS_KDATB
    ,CAST(EKKO.KDATE AS DATE) AS TS_KDATE
    ,CAST(EKKO.RELEASE_DATE AS DATE) AS TS_RELEASE_DATE
	,DD07T.DDTEXT AS "BSTYP_TEXT"
	,DD07T_EKKO_STATU.DDTEXT AS "STATU_TEXT"
	,T161T.BATXT AS "BSART_TEXT"
    ,T024E.EKOTX AS "EKORG_TEXT"
	,T001.BUTXT AS "BUKRS_TEXT"
    ,T001.LAND1 AS "BUKRS_TEXT2"
	,T001.WAERS AS "BUKRS_TEXT3"
	,T024.EKNAM AS "EKGRP_TEXT"
FROM 
    EKKO AS EKKO
	LEFT JOIN DD07T AS DD07T ON 1=1
		AND EKKO.BSTYP = DD07T.DOMVALUE_L
		AND DD07T.DOMNAME = 'BSTYP'
		AND DD07T.DDLANGUAGE = '<%=primaryLanguageKey%>'
	LEFT JOIN DD07T AS DD07T_EKKO_STATU ON 1=1
		AND EKKO.STATU = DD07T_EKKO_STATU.DOMVALUE_L
		AND DD07T_EKKO_STATU.DOMNAME = 'ASTAT' 
		AND DD07T_EKKO_STATU.DDLANGUAGE = '<%=primaryLanguageKey%>'		
	LEFT JOIN T161T AS T161T ON 1=1
		AND EKKO.MANDT = T161T.MANDT
		AND EKKO.BSART = T161T.BSART 
		AND EKKO.BSTYP = T161T.BSTYP
		AND T161T.SPRAS = '<%=primaryLanguageKey%>'
	LEFT JOIN T024E AS T024E ON 1=1
		AND EKKO.MANDT = T024E.MANDT
		AND EKKO.EKORG = T024E.EKORG
	LEFT JOIN T001 AS T001 ON 1=1
		AND EKKO.MANDT = T001.MANDT
		AND EKKO.BUKRS = T001.BUKRS
	LEFT JOIN T024 AS T024 ON 1=1
		AND EKKO.MANDT = T024.MANDT
		AND EKKO.EKGRP = T024.EKGRP
       WHERE EXISTS (
    SELECT 1 
    FROM PR_EBAN_STAGING AS C
    WHERE 1=1 
        AND EKKO.MANDT = C.MANDT
        AND EKKO.EBELN = C.EBELN)
         ;
    
    
SELECT ANALYZE_STATISTICS ('PR_EKKO_STAGING'); 
