
DROP VIEW IF EXISTS PR_EKKO;
    
CREATE VIEW PR_EKKO AS 
SELECT 
    EKKO.*
    ,PR_EKKO_STAGING.TS_AEDAT
    ,PR_EKKO_STAGING.TS_ANGDT
    ,PR_EKKO_STAGING.TS_BEDAT
    ,PR_EKKO_STAGING.TS_BNDDT
    ,PR_EKKO_STAGING.TS_BWBDT
    ,PR_EKKO_STAGING.TS_DPDAT
    ,PR_EKKO_STAGING.TS_EQ_EINDT
    ,PR_EKKO_STAGING.TS_GWLDT
    ,PR_EKKO_STAGING.TS_IHRAN
    ,PR_EKKO_STAGING.TS_KDATB
    ,PR_EKKO_STAGING.TS_KDATE
    ,PR_EKKO_STAGING.TS_RELEASE_DATE
	,PR_EKKO_STAGING.BSTYP_TEXT
	,PR_EKKO_STAGING.STATU_TEXT
	,PR_EKKO_STAGING.BSART_TEXT 
    ,PR_EKKO_STAGING.EKORG_TEXT 
	,PR_EKKO_STAGING.BUKRS_TEXT 
    ,PR_EKKO_STAGING.BUKRS_TEXT2 
	,PR_EKKO_STAGING.BUKRS_TEXT3 
	,PR_EKKO_STAGING.EKGRP_TEXT
    ,PR_EKKO_STAGING.EPOCH
FROM 
    EKKO AS EKKO JOIN 
    PR_EKKO_STAGING ON 1=1
        AND EKKO.MANDT=PR_EKKO_STAGING.MANDT
        AND EKKO.EBELN=PR_EKKO_STAGING.EBELN
;
