
DROP VIEW IF EXISTS PR_LFA1;
    
CREATE VIEW PR_LFA1 AS 
SELECT 
    LFA1.*,
    LFA1.EPOCH
FROM 
    LFA1 AS LFA1
WHERE EXISTS(
    SELECT 1
    FROM PR_EBAN_STAGING AS C
    WHERE 1=1 
    AND LFA1.MANDT = C.MANDT 
    AND LFA1.LIFNR = C.LIFNR)
        ;
