DROP VIEW IF EXISTS PR_LFM1;

CREATE VIEW PR_LFM1 AS
SELECT 
	LFM1.*,
    CAST(LFM1.ERDAT AS DATE) AS TS_ERDAT 
    , CAST(T052U.TEXT1 AS VARCHAR) AS ZTERM_TEXT
     ,  LFM1.EPOCH
FROM 
    LFM1
LEFT JOIN T052U AS T052U ON 
    T052U.MANDT = LFM1.MANDT
    AND T052U.ZTERM = LFM1.ZTERM
    AND SPRAS = '<%=primaryLanguageKey%>'
    AND ZTAGG = '00'
WHERE EXISTS(
    SELECT 1
    FROM PR_EBAN_STAGING AS C
    WHERE 1=1 
    AND LFM1.MANDT = C.MANDT 
    AND LFM1.LIFNR = C.LIFNR
    AND LFM1.EKORG = C.EKORG
    )
        ;
