DROP VIEW IF EXISTS PR_EKBE;

CREATE VIEW PR_EKBE AS (
SELECT 
    EKBE.*,
    CAST(EKBE.BLDAT AS DATE) AS TS_BLDAT,
    CAST(EKBE.BUDAT AS DATE) AS TS_BUDAT,
    CAST(EKBE.CPUDT AS DATE) AS TS_CPUDT,
    CAST(EKBE.CPUTM AS DATETIME) AS TS_CPUTM,
    EKBE.EPOCH

FROM 
    EKBE
WHERE EXISTS(
    SELECT * 
    FROM "PR_EKPO_STAGING" AS "C"
    WHERE 1=1
        AND EKBE.MANDT = C.MANDT
        AND EKBE.EBELN = C.EBELN
        AND EKBE.EBELP = C.EBELP)
);
