DROP VIEW IF EXISTS PR_EKET;

CREATE VIEW PR_EKET AS(
SELECT 
    EKET.*,
    CAST(EKET.ALTDT AS DATE) AS TS_ALTDT, 
    CAST(EKET.DAT01 AS DATE) AS TS_DAT01, 
    CAST(EKET.EINDT AS DATE) AS TS_EINDT, 
    CAST(EKET.ELDAT AS DATE) AS TS_ELDAT, 
    CAST(EKET.LDDAT AS DATE) AS TS_LDDAT, 
    CAST(EKET.MBDAT AS DATE) AS TS_MBDAT, 
    CAST(EKET.SLFDT AS DATE) AS TS_SLFDT,
    EKET.EPOCH
FROM 
    EKET
WHERE EXISTS(
    SELECT * 
    FROM "PR_EKPO_STAGING" AS "C"
    WHERE 1=1 
        AND EKET.MANDT = C.MANDT
        AND EKET.EBELN = C.EBELN
        AND EKET.EBELP = C.EBELP)
)
;
