DROP TABLE IF EXISTS PR_CATALOGS_STAGING;

CREATE TABLE PR_CATALOGS_STAGING AS 
SELECT 
    EINE.MANDT	
    ,EINE.INFNR	
    ,EINE.EKORG	
    ,EINE.ESOKZ	
    ,EINE.WERKS
    ,EINA.UMREN
    ,EINA.UMREZ
    ,EINA.LIFNR
    ,LFA1.NAME1
    ,EINA.MATNR
    ,IFNULL(MAKT.MAKTX,'') AS "MATNR_TEXT"
    ,IFNULL(EINE.WERKS,'_CEL_NULL_JOIN') AS "WERKS_JOIN" -- required for NULL join on EKPO
    ,EINA.LOEKZ AS EINA_LOEKZ
    ,EINA.MEINS
    ,EINE.ERDAT AS TS_ERDAT
    ,CAST(EINE.ANGDT AS DATE) AS TS_ANGDT
    ,CAST(EINE.AMODV AS DATE) AS TS_AMODV
    ,CAST(EINE.AMODB AS DATE) AS TS_AMODB
    ,CAST(EINE.DATLB AS DATE) AS TS_DATLB
    ,CAST(EINE.PRDAT AS DATE) AS TS_PRDAT
    ,IFNULL(T024E.EKOTX,'') AS "EKORG_TEXT"
    ,IFNULL(T001W.NAME1,'') AS "WERKS_TEXT"
    ,IFNULL(T024.EKNAM,'') AS "EKGRP_TEXT"
    -- additions for price analytics
       ,CASE 
		WHEN EINE.WAERS = '<%=currency%>' THEN EINE.NETPR*ISNULL(TCURX.TDEC,1) 
  		WHEN TCURR_CC.UKURS < 0 THEN (EINE.NETPR*ISNULL(TCURX.TDEC,1))*(1/ABS(TCURR_CC.UKURS)/(CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END))*(CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
		WHEN TCURR_CC.UKURS > 0 THEN (EINE.NETPR*ISNULL(TCURX.TDEC,1))*(TCURR_CC.UKURS/CASE WHEN COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.FFACT, TCURR_CC.FFACT) END*CASE WHEN COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT, 0) = 0 THEN 1 ELSE COALESCE(TCURF_CC.TFACT, TCURR_CC.TFACT) END)
	END AS NETPR_CONVERTED
    -- additions END
    , EINE.MANDT || EINE.INFNR || EINE.EKORG || EINE.WERKS || EINE.ESOKZ AS CONCATKEY
    , MARA.MATKL AS MATKL
    , T023T.WGBEZ AS "MATKL_TEXT"
FROM 
    EINE AS EINE
    INNER JOIN EINA AS EINA ON 1=1
        AND EINE.MANDT = EINA.MANDT
        AND EINE.INFNR = EINA.INFNR
    LEFT JOIN T024E AS T024E ON 1=1
		AND EINE.MANDT = T024E.MANDT
		AND EINE.EKORG = T024E.EKORG
    LEFT JOIN T001W AS T001W ON 1=1
		AND EINE.MANDT = T001W.MANDT
		AND EINE.WERKS = T001W.WERKS
    LEFT JOIN T024 AS T024 ON 1=1
		AND EINE.MANDT = T024.MANDT
		AND EINE.EKGRP = T024.EKGRP
    LEFT JOIN LFA1 AS LFA1 ON 1=1
        AND EINA.MANDT = LFA1.MANDT
        AND EINA.LIFNR = LFA1.LIFNR
    LEFT JOIN MAKT AS MAKT ON 1=1
        AND MAKT.MANDT = EINA.MANDT
        AND MAKT.MATNR = EINA.MATNR
        AND MAKT.SPRAS = '<%=primaryLanguageKey%>'
    LEFT JOIN MARA AS MARA ON 1=1
        AND MARA.MANDT = EINA.MANDT
        AND MARA.MATNR = EINA.MATNR 
    LEFT JOIN T023T AS T023T ON 1=1
		AND MARA.MANDT = T023T.MANDT
		AND MARA.MATKL = T023T.MATKL
		AND T023T.SPRAS = '<%=primaryLanguageKey%>' 
    LEFT JOIN PR_TCURR_CC AS TCURR_CC ON 1=1
		AND TCURR_CC.MANDT = EINE.MANDT
		AND TCURR_CC.TCURR = '<%=currency%>'
		AND TCURR_CC.FCURR = EINE.WAERS                                             
		AND EINE.ERDAT  >= TCURR_CC.VALID_START AND EINE.ERDAT < TCURR_CC.VALID_END
        AND TCURR_CC.KURST = '<%=exchangeRateType%>' 
    LEFT JOIN PR_TCURF_CC AS TCURF_CC ON 1=1
		AND TCURR_CC.MANDT = TCURF_CC.MANDT
		AND TCURR_CC.TCURR = TCURF_CC.TCURR
		AND TCURR_CC.FCURR = TCURF_CC.FCURR
		AND TCURR_CC.KURST = TCURF_CC.KURST
        AND EINE.ERDAT >= TCURF_CC.VALID_START	
		AND EINE.ERDAT  < TCURF_CC.VALID_END
	LEFT JOIN (
		SELECT 
			TCURX.CURRKEY
			,CAST(TCURX.CURRDEC AS INT) AS CURRDEC
			,POWER(CAST(10 AS FLOAT),(2-CURRDEC)) AS TDEC 
		FROM 
			TCURX) AS TCURX ON 1=1
		AND TCURR_CC.FCURR = TCURX.CURRKEY
    WHERE EINE.ESOKZ = '0'
;

    
SELECT ANALYZE_STATISTICS ('PR_CATALOGS_STAGING'); 
