DROP VIEW IF EXISTS PR_CATALOGS;

CREATE VIEW PR_CATALOGS AS 
SELECT 
     EINE.*
    ,PR_CATALOGS_STAGING.UMREN
    ,PR_CATALOGS_STAGING.UMREZ
    ,PR_CATALOGS_STAGING.LIFNR
    ,PR_CATALOGS_STAGING.NAME1
    ,PR_CATALOGS_STAGING.MATNR
    ,PR_CATALOGS_STAGING.MATNR_TEXT
    ,PR_CATALOGS_STAGING.WERKS_JOIN
    ,PR_CATALOGS_STAGING.EINA_LOEKZ
    ,PR_CATALOGS_STAGING.MEINS
    ,PR_CATALOGS_STAGING.TS_ERDAT
    ,PR_CATALOGS_STAGING.TS_ANGDT
    ,PR_CATALOGS_STAGING.TS_AMODV
    ,PR_CATALOGS_STAGING.TS_AMODB
    ,PR_CATALOGS_STAGING.TS_DATLB
    ,PR_CATALOGS_STAGING.TS_PRDAT
    ,PR_CATALOGS_STAGING.EKORG_TEXT
    ,PR_CATALOGS_STAGING.WERKS_TEXT
    ,PR_CATALOGS_STAGING.EKGRP_TEXT
    ,PR_CATALOGS_STAGING.NETPR_CONVERTED
    ,PR_CATALOGS_STAGING.CONCATKEY
    ,PR_CATALOGS_STAGING.MATKL
    ,PR_CATALOGS_STAGING.MATKL_TEXT
    ,PR_CATALOGS_STAGING.EPOCH
FROM PR_CATALOGS_STAGING
JOIN EINE ON 1=1
        AND EINE.MANDT=PR_CATALOGS_STAGING.MANDT
        AND EINE.INFNR=PR_CATALOGS_STAGING.INFNR
        AND EINE.EKORG=PR_CATALOGS_STAGING.EKORG
        AND EINE.ESOKZ=PR_CATALOGS_STAGING.ESOKZ
        AND EINE.WERKS=PR_CATALOGS_STAGING.WERKS
    ;

