 DROP TABLE IF EXISTS COUNTRY_CODES; 

CREATE TABLE COUNTRY_CODES (
    COUNTRY VARCHAR (100),
    ISO2 VARCHAR (2),
    ISO3 VARCHAR (3),
    COUNTRY_CODE INT,
    ISO_3166_2 VARCHAR(15),
    REGION_CODE VARCHAR(3),
    SUBREGION_CODE VARCHAR(3),
    REGION_TEXT_EN VARCHAR(50),
    REGION_TEXT_DE VARCHAR(50),
    SUBREGION_TEXT_EN VARCHAR(50),
    SUBREGION_TEXT_DE VARCHAR(50)
);
     
INSERT INTO  COUNTRY_CODES VALUES (  'Benin',    'BJ',   'BEN',  '204',  'ISO 3166-2:BJ',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Burkina Faso', 'BF',   'BFA',  '854',  'ISO 3166-2:BF',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Cape Verde',   'CV',   'CPV',  '132',  'ISO 3166-2:CV',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Côte d''Ivoire',   'CI',   'CIV',  '384',  'ISO 3166-2:CI',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Gambia',   'GM',   'GMB',  '270',  'ISO 3166-2:GM',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Ghana',    'GH',   'GHA',  '288',  'ISO 3166-2:GH',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Guinea',   'GN',   'GIN',  '324',  'ISO 3166-2:GN',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Guinea-Bissau',    'GW',   'GNB',  '624',  'ISO 3166-2:GW',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Liberia',  'LR',   'LBR',  '430',  'ISO 3166-2:LR',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Mali', 'ML',   'MLI',  '466',  'ISO 3166-2:ML',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Mauritania',   'MR',   'MRT',  '478',  'ISO 3166-2:MR',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Niger',    'NE',   'NER',  '562',  'ISO 3166-2:NE',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Nigeria',  'NG',   'NGA',  '566',  'ISO 3166-2:NG',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Saint Helena\, Ascension and Tristan da Cunha',    'SH',   'SHN',  '654',  'ISO 3166-2:SH',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Senegal',  'SN',   'SEN',  '686',  'ISO 3166-2:SN',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Sierra Leone', 'SL',   'SLE',  '694',  'ISO 3166-2:SL',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Togo', 'TG',   'TGO',  '768',  'ISO 3166-2:TG',    '2',    '11',   'Africa',   'Afrika',   'Western Africa',   'Westafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Burundi',  'BI',   'BDI',  '108',  'ISO 3166-2:BI',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Comoros',  'KM',   'COM',  '174',  'ISO 3166-2:KM',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Djibouti', 'DJ',   'DJI',  '262',  'ISO 3166-2:DJ',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Eritrea',  'ER',   'ERI',  '232',  'ISO 3166-2:ER',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Ethiopia', 'ET',   'ETH',  '231',  'ISO 3166-2:ET',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Kenya',    'KE',   'KEN',  '404',  'ISO 3166-2:KE',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Madagascar',   'MG',   'MDG',  '450',  'ISO 3166-2:MG',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Malawi',   'MW',   'MWI',  '454',  'ISO 3166-2:MW',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Mauritius',    'MU',   'MUS',  '480',  'ISO 3166-2:MU',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Mayotte',  'YT',   'MYT',  '175',  'ISO 3166-2:YT',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Mozambique',   'MZ',   'MOZ',  '508',  'ISO 3166-2:MZ',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Réunion',  'RE',   'REU',  '638',  'ISO 3166-2:RE',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Rwanda',   'RW',   'RWA',  '646',  'ISO 3166-2:RW',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Seychelles',   'SC',   'SYC',  '690',  'ISO 3166-2:SC',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Somalia',  'SO',   'SOM',  '706',  'ISO 3166-2:SO',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'South Sudan',  'SS',   'SSD',  '728',  'ISO 3166-2:SS',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Tanzania,  United Republic of',    'TZ',   'TZA',  '834',  'ISO 3166-2:TZ',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Uganda',   'UG',   'UGA',  '800',  'ISO 3166-2:UG',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Zambia',   'ZM',   'ZMB',  '894',  'ISO 3166-2:ZM',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Zimbabwe', 'ZW',   'ZWE',  '716',  'ISO 3166-2:ZW',    '2',    '14',   'Africa',   'Afrika',   'Eastern Africa',   'Ostafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Algeria',  'DZ',   'DZA',  '12',   'ISO 3166-2:DZ',    '2',    '15',   'Africa',   'Afrika',   'Northern Africa',  'Nordafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Egypt',    'EG',   'EGY',  '818',  'ISO 3166-2:EG',    '2',    '15',   'Africa',   'Afrika',   'Northern Africa',  'Nordafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Libya',    'LY',   'LBY',  '434',  'ISO 3166-2:LY',    '2',    '15',   'Africa',   'Afrika',   'Northern Africa',  'Nordafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Morocco',  'MA',   'MAR',  '504',  'ISO 3166-2:MA',    '2',    '15',   'Africa',   'Afrika',   'Northern Africa',  'Nordafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Sudan',    'SD',   'SDN',  '729',  'ISO 3166-2:SD',    '2',    '15',   'Africa',   'Afrika',   'Northern Africa',  'Nordafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Tunisia',  'TN',   'TUN',  '788',  'ISO 3166-2:TN',    '2',    '15',   'Africa',   'Afrika',   'Northern Africa',  'Nordafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Western Sahara',   'EH',   'ESH',  '732',  'ISO 3166-2:EH',    '2',    '15',   'Africa',   'Afrika',   'Northern Africa',  'Nordafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Angola',   'AO',   'AGO',  '24',   'ISO 3166-2:AO',    '2',    '17',   'Africa',   'Afrika',   'Middle Africa',    'Zentralafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Cameroon', 'CM',   'CMR',  '120',  'ISO 3166-2:CM',    '2',    '17',   'Africa',   'Afrika',   'Middle Africa',    'Zentralafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Central African Republic', 'CF',   'CAF',  '140',  'ISO 3166-2:CF',    '2',    '17',   'Africa',   'Afrika',   'Middle Africa',    'Zentralafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Chad', 'TD',   'TCD',  '148',  'ISO 3166-2:TD',    '2',    '17',   'Africa',   'Afrika',   'Middle Africa',    'Zentralafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Congo',    'CG',   'COG',  '178',  'ISO 3166-2:CG',    '2',    '17',   'Africa',   'Afrika',   'Middle Africa',    'Zentralafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Congo,  the Democratic Republic of the',   'CD',   'COD',  '180',  'ISO 3166-2:CD',    '2',    '17',   'Africa',   'Afrika',   'Middle Africa',    'Zentralafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Equatorial Guinea',    'GQ',   'GNQ',  '226',  'ISO 3166-2:GQ',    '2',    '17',   'Africa',   'Afrika',   'Middle Africa',    'Zentralafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Gabon',    'GA',   'GAB',  '266',  'ISO 3166-2:GA',    '2',    '17',   'Africa',   'Afrika',   'Middle Africa',    'Zentralafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Sao Tome and Principe',    'ST',   'STP',  '678',  'ISO 3166-2:ST',    '2',    '17',   'Africa',   'Afrika',   'Middle Africa',    'Zentralafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Botswana', 'BW',   'BWA',  '72',   'ISO 3166-2:BW',    '2',    '18',   'Africa',   'Afrika',   'Southern Africa',  'Südafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Lesotho',  'LS',   'LSO',  '426',  'ISO 3166-2:LS',    '2',    '18',   'Africa',   'Afrika',   'Southern Africa',  'Südafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Namibia',  'NA',   'NAM',  '516',  'ISO 3166-2:NA',    '2',    '18',   'Africa',   'Afrika',   'Southern Africa',  'Südafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'South Africa', 'ZA',   'ZAF',  '710',  'ISO 3166-2:ZA',    '2',    '18',   'Africa',   'Afrika',   'Southern Africa',  'Südafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Swaziland',    'SZ',   'SWZ',  '748',  'ISO 3166-2:SZ',    '2',    '18',   'Africa',   'Afrika',   'Southern Africa',  'Südafrika');
INSERT INTO  COUNTRY_CODES VALUES (  'Australia',    'AU',   'AUS',  '36',   'ISO 3166-2:AU',    '9',    '53',   'Oceania',  'Ozeanien', 'Australia and New Zealand',    'Australien und Neuseeland');
INSERT INTO  COUNTRY_CODES VALUES (  'New Zealand',  'NZ',   'NZL',  '554',  'ISO 3166-2:NZ',    '9',    '53',   'Oceania',  'Ozeanien', 'Australia and New Zealand',    'Australien und Neuseeland');
INSERT INTO  COUNTRY_CODES VALUES (  'Norfolk Island',   'NF',   'NFK',  '574',  'ISO 3166-2:NF',    '9',    '53',   'Oceania',  'Ozeanien', 'Australia and New Zealand',    'Australien und Neuseeland');
INSERT INTO  COUNTRY_CODES VALUES (  'Fiji', 'FJ',   'FJI',  '242',  'ISO 3166-2:FJ',    '9',    '54',   'Oceania',  'Ozeanien', 'Melanesia',    'Melanesien');
INSERT INTO  COUNTRY_CODES VALUES (  'New Caledonia',    'NC',   'NCL',  '540',  'ISO 3166-2:NC',    '9',    '54',   'Oceania',  'Ozeanien', 'Melanesia',    'Melanesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Papua New Guinea', 'PG',   'PNG',  '598',  'ISO 3166-2:PG',    '9',    '54',   'Oceania',  'Ozeanien', 'Melanesia',    'Melanesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Solomon Islands',  'SB',   'SLB',  '90',   'ISO 3166-2:SB',    '9',    '54',   'Oceania',  'Ozeanien', 'Melanesia',    'Melanesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Vanuatu',  'VU',   'VUT',  '548',  'ISO 3166-2:VU',    '9',    '54',   'Oceania',  'Ozeanien', 'Melanesia',    'Melanesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Guam', 'GU',   'GUM',  '316',  'ISO 3166-2:GU',    '9',    '57',   'Oceania',  'Ozeanien', 'Micronesia',   'Mikronesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Kiribati', 'KI',   'KIR',  '296',  'ISO 3166-2:KI',    '9',    '57',   'Oceania',  'Ozeanien', 'Micronesia',   'Mikronesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Marshall Islands', 'MH',   'MHL',  '584',  'ISO 3166-2:MH',    '9',    '57',   'Oceania',  'Ozeanien', 'Micronesia',   'Mikronesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Micronesia,  Federated States of', 'FM',   'FSM',  '583',  'ISO 3166-2:FM',    '9',    '57',   'Oceania',  'Ozeanien', 'Micronesia',   'Mikronesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Nauru',    'NR',   'NRU',  '520',  'ISO 3166-2:NR',    '9',    '57',   'Oceania',  'Ozeanien', 'Micronesia',   'Mikronesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Northern Mariana Islands', 'MP',   'MNP',  '580',  'ISO 3166-2:MP',    '9',    '57',   'Oceania',  'Ozeanien', 'Micronesia',   'Mikronesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Palau',    'PW',   'PLW',  '585',  'ISO 3166-2:PW',    '9',    '57',   'Oceania',  'Ozeanien', 'Micronesia',   'Mikronesien');
INSERT INTO  COUNTRY_CODES VALUES (  'American Samoa',   'AS',   'ASM',  '16',   'ISO 3166-2:AS',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Cook Islands', 'CK',   'COK',  '184',  'ISO 3166-2:CK',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'French Polynesia', 'PF',   'PYF',  '258',  'ISO 3166-2:PF',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Niue', 'NU',   'NIU',  '570',  'ISO 3166-2:NU',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Pitcairn', 'PN',   'PCN',  '612',  'ISO 3166-2:PN',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Samoa',    'WS',   'WSM',  '882',  'ISO 3166-2:WS',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Tokelau',  'TK',   'TKL',  '772',  'ISO 3166-2:TK',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Tonga',    'TO',   'TON',  '776',  'ISO 3166-2:TO',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Tuvalu',   'TV',   'TUV',  '798',  'ISO 3166-2:TV',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Wallis and Futuna',    'WF',   'WLF',  '876',  'ISO 3166-2:WF',    '9',    '61',   'Oceania',  'Ozeanien', 'Polynesia',    'Polynesien');
INSERT INTO  COUNTRY_CODES VALUES (  'Argentina',    'AR',   'ARG',  '32',   'ISO 3166-2:AR',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Bolivia,  Plurinational State of', 'BO',   'BOL',  '68',   'ISO 3166-2:BO',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Brazil',   'BR',   'BRA',  '76',   'ISO 3166-2:BR',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Chile',    'CL',   'CHL',  '152',  'ISO 3166-2:CL',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Colombia', 'CO',   'COL',  '170',  'ISO 3166-2:CO',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Ecuador',  'EC',   'ECU',  '218',  'ISO 3166-2:EC',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Falkland Islands (Malvinas);', 'FK',   'FLK',  '238',  'ISO 3166-2:FK',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'French Guiana',    'GF',   'GUF',  '254',  'ISO 3166-2:GF',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Guyana',   'GY',   'GUY',  '328',  'ISO 3166-2:GY',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Paraguay', 'PY',   'PRY',  '600',  'ISO 3166-2:PY',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Peru', 'PE',   'PER',  '604',  'ISO 3166-2:PE',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Suriname', 'SR',   'SUR',  '740',  'ISO 3166-2:SR',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Uruguay',  'UY',   'URY',  '858',  'ISO 3166-2:UY',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Venezuela\,  Bolivarian Republic of',  'VE',   'VEN',  '862',  'ISO 3166-2:VE',    '19',   '5',    'America',  'Amerika',  'South America',    'Südamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Belize',   'BZ',   'BLZ',  '84',   'ISO 3166-2:BZ',    '19',   '13',   'America',  'Amerika',  'Central America',  'Zentralamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Costa Rica',   'CR',   'CRI',  '188',  'ISO 3166-2:CR',    '19',   '13',   'America',  'Amerika',  'Central America',  'Zentralamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'El Salvador',  'SV',   'SLV',  '222',  'ISO 3166-2:SV',    '19',   '13',   'America',  'Amerika',  'Central America',  'Zentralamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Guatemala',    'GT',   'GTM',  '320',  'ISO 3166-2:GT',    '19',   '13',   'America',  'Amerika',  'Central America',  'Zentralamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Honduras', 'HN',   'HND',  '340',  'ISO 3166-2:HN',    '19',   '13',   'America',  'Amerika',  'Central America',  'Zentralamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Mexico',   'MX',   'MEX',  '484',  'ISO 3166-2:MX',    '19',   '13',   'America',  'Amerika',  'Central America',  'Zentralamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Nicaragua',    'NI',   'NIC',  '558',  'ISO 3166-2:NI',    '19',   '13',   'America',  'Amerika',  'Central America',  'Zentralamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Panama',   'PA',   'PAN',  '591',  'ISO 3166-2:PA',    '19',   '13',   'America',  'Amerika',  'Central America',  'Zentralamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Bermuda',  'BM',   'BMU',  '60',   'ISO 3166-2:BM',    '19',   '21',   'America',  'Amerika',  'Northern America', 'Nordamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Canada',   'CA',   'CAN',  '124',  'ISO 3166-2:CA',    '19',   '21',   'America',  'Amerika',  'Northern America', 'Nordamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Greenland',    'GL',   'GRL',  '304',  'ISO 3166-2:GL',    '19',   '21',   'America',  'Amerika',  'Northern America', 'Nordamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Saint Pierre and Miquelon',    'PM',   'SPM',  '666',  'ISO 3166-2:PM',    '19',   '21',   'America',  'Amerika',  'Northern America', 'Nordamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'United States',    'US',   'USA',  '840',  'ISO 3166-2:US',    '19',   '21',   'America',  'Amerika',  'Northern America', 'Nordamerika');
INSERT INTO  COUNTRY_CODES VALUES (  'Anguilla', 'AI',   'AIA',  '660',  'ISO 3166-2:AI',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Antigua and Barbuda',  'AG',   'ATG',  '28',   'ISO 3166-2:AG',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Aruba',    'AW',   'ABW',  '533',  'ISO 3166-2:AW',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Bahamas',  'BS',   'BHS',  '44',   'ISO 3166-2:BS',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Barbados', 'BB',   'BRB',  '52',   'ISO 3166-2:BB',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Bonaire,  Sint Eustatius and Saba',    'BQ',   'BES',  '535',  'ISO 3166-2:BQ',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Cayman Islands',   'KY',   'CYM',  '136',  'ISO 3166-2:KY',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Cuba', 'CU',   'CUB',  '192',  'ISO 3166-2:CU',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Cura?ao',  'CW',   'CUW',  '531',  'ISO 3166-2:CW',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Dominica', 'DM',   'DMA',  '212',  'ISO 3166-2:DM',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Dominican Republic',   'DO',   'DOM',  '214',  'ISO 3166-2:DO',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Grenada',  'GD',   'GRD',  '308',  'ISO 3166-2:GD',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Guadeloupe',   'GP',   'GLP',  '312',  'ISO 3166-2:GP',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Haiti',    'HT',   'HTI',  '332',  'ISO 3166-2:HT',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Jamaica',  'JM',   'JAM',  '388',  'ISO 3166-2:JM',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Martinique',   'MQ',   'MTQ',  '474',  'ISO 3166-2:MQ',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Montserrat',   'MS',   'MSR',  '500',  'ISO 3166-2:MS',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Puerto Rico',  'PR',   'PRI',  '630',  'ISO 3166-2:PR',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Saint Barth?lemy', 'BL',   'BLM',  '652',  'ISO 3166-2:BL',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Saint Kitts and Nevis',    'KN',   'KNA',  '659',  'ISO 3166-2:KN',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Saint Lucia',  'LC',   'LCA',  '662',  'ISO 3166-2:LC',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Saint Martin (French part);',  'MF',   'MAF',  '663',  'ISO 3166-2:MF',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Saint Vincent and the Grenadines', 'VC',   'VCT',  '670',  'ISO 3166-2:VC',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Sint Maarten (Dutch part);',   'SX',   'SXM',  '534',  'ISO 3166-2:SX',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Trinidad and Tobago',  'TT',   'TTO',  '780',  'ISO 3166-2:TT',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Turks and Caicos Islands', 'TC',   'TCA',  '796',  'ISO 3166-2:TC',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Virgin Islands,  British', 'VG',   'VGB',  '92',   'ISO 3166-2:VG',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'Virgin Islands,  U.S.',    'VI',   'VIR',  '850',  'ISO 3166-2:VI',    '19',   '29',   'America',  'Amerika',  'Caribbean',    'Karibik');
INSERT INTO  COUNTRY_CODES VALUES (  'China',    'CN',   'CHN',  '156',  'ISO 3166-2:CN',    '142',  '30',   'Asia', 'Asien',    'Eastern Asia', 'Ostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Hong Kong',    'HK',   'HKG',  '344',  'ISO 3166-2:HK',    '142',  '30',   'Asia', 'Asien',    'Eastern Asia', 'Ostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Japan',    'JP',   'JPN',  '392',  'ISO 3166-2:JP',    '142',  '30',   'Asia', 'Asien',    'Eastern Asia', 'Ostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Korea\, Democratic People''s Republic of', 'KP',   'PRK',  '408',  'ISO 3166-2:KP',    '142',  '30',   'Asia', 'Asien',    'Eastern Asia', 'Ostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Korea\,  Republic of', 'KR',   'KOR',  '410',  'ISO 3166-2:KR',    '142',  '30',   'Asia', 'Asien',    'Eastern Asia', 'Ostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Macao',    'MO',   'MAC',  '446',  'ISO 3166-2:MO',    '142',  '30',   'Asia', 'Asien',    'Eastern Asia', 'Ostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Mongolia', 'MN',   'MNG',  '496',  'ISO 3166-2:MN',    '142',  '30',   'Asia', 'Asien',    'Eastern Asia', 'Ostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Taiwan',  'TW',   'TWN',  '158',  'ISO 3166-2:TW',    '142',  '30',   'Asia', 'Asien',    'Eastern Asia', 'Ostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Afghanistan',  'AF',   'AFG',  '4',    'ISO 3166-2:AF',    '142',  '34',   'Asia', 'Asien',    'Southern Asia',    'Südasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Bangladesh',   'BD',   'BGD',  '50',   'ISO 3166-2:BD',    '142',  '34',   'Asia', 'Asien',    'Southern Asia',    'Südasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Bhutan',   'BT',   'BTN',  '64',   'ISO 3166-2:BT',    '142',  '34',   'Asia', 'Asien',    'Southern Asia',    'Südasien');
INSERT INTO  COUNTRY_CODES VALUES (  'India',    'IN',   'IND',  '356',  'ISO 3166-2:IN',    '142',  '34',   'Asia', 'Asien',    'Southern Asia',    'Südasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Iran\,  Islamic Republic of',  'IR',   'IRN',  '364',  'ISO 3166-2:IR',    '142',  '34',   'Asia', 'Asien',    'Southern Asia',    'Südasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Maldives', 'MV',   'MDV',  '462',  'ISO 3166-2:MV',    '142',  '34',   'Asia', 'Asien',    'Southern Asia',    'Südasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Nepal',    'NP',   'NPL',  '524',  'ISO 3166-2:NP',    '142',  '34',   'Asia', 'Asien',    'Southern Asia',    'Südasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Pakistan', 'PK',   'PAK',  '586',  'ISO 3166-2:PK',    '142',  '34',   'Asia', 'Asien',    'Southern Asia',    'Südasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Sri Lanka',    'LK',   'LKA',  '144',  'ISO 3166-2:LK',    '142',  '34',   'Asia', 'Asien',    'Southern Asia',    'Südasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Brunei Darussalam',    'BN',   'BRN',  '96',   'ISO 3166-2:BN',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Cambodia', 'KH',   'KHM',  '116',  'ISO 3166-2:KH',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Indonesia',    'ID',   'IDN',  '360',  'ISO 3166-2:ID',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Lao People''s Democratic Republic',    'LA',   'LAO',  '418',  'ISO 3166-2:LA',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Malaysia', 'MY',   'MYS',  '458',  'ISO 3166-2:MY',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Myanmar',  'MM',   'MMR',  '104',  'ISO 3166-2:MM',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Philippines',  'PH',   'PHL',  '608',  'ISO 3166-2:PH',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Singapore',    'SG',   'SGP',  '702',  'ISO 3166-2:SG',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Thailand', 'TH',   'THA',  '764',  'ISO 3166-2:TH',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Timor-Leste',  'TL',   'TLS',  '626',  'ISO 3166-2:TL',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Viet Nam', 'VN',   'VNM',  '704',  'ISO 3166-2:VN',    '142',  '35',   'Asia', 'Asien',    'South-Eastern Asia',   'Südostasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Kazakhstan',   'KZ',   'KAZ',  '398',  'ISO 3166-2:KZ',    '142',  '143',  'Asia', 'Asien',    'Central Asia', 'Zentralasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Kyrgyzstan',   'KG',   'KGZ',  '417',  'ISO 3166-2:KG',    '142',  '143',  'Asia', 'Asien',    'Central Asia', 'Zentralasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Tajikistan',   'TJ',   'TJK',  '762',  'ISO 3166-2:TJ',    '142',  '143',  'Asia', 'Asien',    'Central Asia', 'Zentralasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Turkmenistan', 'TM',   'TKM',  '795',  'ISO 3166-2:TM',    '142',  '143',  'Asia', 'Asien',    'Central Asia', 'Zentralasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Uzbekistan',   'UZ',   'UZB',  '860',  'ISO 3166-2:UZ',    '142',  '143',  'Asia', 'Asien',    'Central Asia', 'Zentralasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Armenia',  'AM',   'ARM',  '51',   'ISO 3166-2:AM',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Azerbaijan',   'AZ',   'AZE',  '31',   'ISO 3166-2:AZ',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Bahrain',  'BH',   'BHR',  '48',   'ISO 3166-2:BH',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Cyprus',   'CY',   'CYP',  '196',  'ISO 3166-2:CY',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Georgia',  'GE',   'GEO',  '268',  'ISO 3166-2:GE',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Iraq', 'IQ',   'IRQ',  '368',  'ISO 3166-2:IQ',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Israel',   'IL',   'ISR',  '376',  'ISO 3166-2:IL',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Jordan',   'JO',   'JOR',  '400',  'ISO 3166-2:JO',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Kuwait',   'KW',   'KWT',  '414',  'ISO 3166-2:KW',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Lebanon',  'LB',   'LBN',  '422',  'ISO 3166-2:LB',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Oman', 'OM',   'OMN',  '512',  'ISO 3166-2:OM',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Palestine,  State of', 'PS',   'PSE',  '275',  'ISO 3166-2:PS',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Qatar',    'QA',   'QAT',  '634',  'ISO 3166-2:QA',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Saudi Arabia', 'SA',   'SAU',  '682',  'ISO 3166-2:SA',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Syrian Arab Republic', 'SY',   'SYR',  '760',  'ISO 3166-2:SY',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Turkey',   'TR',   'TUR',  '792',  'ISO 3166-2:TR',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'United Arab Emirates', 'AE',   'ARE',  '784',  'ISO 3166-2:AE',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Yemen',    'YE',   'YEM',  '887',  'ISO 3166-2:YE',    '142',  '145',  'Asia', 'Asien',    'Western Asia', 'Westasien');
INSERT INTO  COUNTRY_CODES VALUES (  'Albania',  'AL',   'ALB',  '8',    'ISO 3166-2:AL',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Andorra',  'AD',   'AND',  '20',   'ISO 3166-2:AD',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Bosnia and Herzegovina',   'BA',   'BIH',  '70',   'ISO 3166-2:BA',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Croatia',  'HR',   'HRV',  '191',  'ISO 3166-2:HR',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Gibraltar',    'GI',   'GIB',  '292',  'ISO 3166-2:GI',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Greece',   'GR',   'GRC',  '300',  'ISO 3166-2:GR',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Holy See (Vatican City State);',   'VA',   'VAT',  '336',  'ISO 3166-2:VA',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Italy',    'IT',   'ITA',  '380',  'ISO 3166-2:IT',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Macedonia\, the former Yugoslav Republic of',  'MK',   'MKD',  '807',  'ISO 3166-2:MK',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Malta',    'MT',   'MLT',  '470',  'ISO 3166-2:MT',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Montenegro',   'ME',   'MNE',  '499',  'ISO 3166-2:ME',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Portugal', 'PT',   'PRT',  '620',  'ISO 3166-2:PT',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'San Marino',   'SM',   'SMR',  '674',  'ISO 3166-2:SM',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Serbia',   'RS',   'SRB',  '688',  'ISO 3166-2:RS',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Slovenia', 'SI',   'SVN',  '705',  'ISO 3166-2:SI',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Spain',    'ES',   'ESP',  '724',  'ISO 3166-2:ES',    '150',  '39',   'Europe',   'Europa',   'Southern Europe',  'Südeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Belarus',  'BY',   'BLR',  '112',  'ISO 3166-2:BY',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Bulgaria', 'BG',   'BGR',  '100',  'ISO 3166-2:BG',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Czech Republic',   'CZ',   'CZE',  '203',  'ISO 3166-2:CZ',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Hungary',  'HU',   'HUN',  '348',  'ISO 3166-2:HU',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Moldova,  Republic of',    'MD',   'MDA',  '498',  'ISO 3166-2:MD',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Poland',   'PL',   'POL',  '616',  'ISO 3166-2:PL',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Romania',  'RO',   'ROU',  '642',  'ISO 3166-2:RO',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Russian Federation',   'RU',   'RUS',  '643',  'ISO 3166-2:RU',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Slovakia', 'SK',   'SVK',  '703',  'ISO 3166-2:SK',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Ukraine',  'UA',   'UKR',  '804',  'ISO 3166-2:UA',    '150',  '151',  'Europe',   'Europa',   'Eastern Europe',   'Osteuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Aland Islands',    'AX',   'ALA',  '248',  'ISO 3166-2:AX',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Denmark',  'DK',   'DNK',  '208',  'ISO 3166-2:DK',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Estonia',  'EE',   'EST',  '233',  'ISO 3166-2:EE',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Faroe Islands',    'FO',   'FRO',  '234',  'ISO 3166-2:FO',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Finland',  'FI',   'FIN',  '246',  'ISO 3166-2:FI',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Guernsey', 'GG',   'GGY',  '831',  'ISO 3166-2:GG',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Iceland',  'IS',   'ISL',  '352',  'ISO 3166-2:IS',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Ireland',  'IE',   'IRL',  '372',  'ISO 3166-2:IE',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Isle of Man',  'IM',   'IMN',  '833',  'ISO 3166-2:IM',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Jersey',   'JE',   'JEY',  '832',  'ISO 3166-2:JE',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Latvia',   'LV',   'LVA',  '428',  'ISO 3166-2:LV',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Lithuania',    'LT',   'LTU',  '440',  'ISO 3166-2:LT',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Norway',   'NO',   'NOR',  '578',  'ISO 3166-2:NO',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Svalbard and Jan Mayen',   'SJ',   'SJM',  '744',  'ISO 3166-2:SJ',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Sweden',   'SE',   'SWE',  '752',  'ISO 3166-2:SE',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'United Kingdom',   'GB',   'GBR',  '826',  'ISO 3166-2:GB',    '150',  '154',  'Europe',   'Europa',   'Northern Europe',  'Nordeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Austria',  'AT',   'AUT',  '40',   'ISO 3166-2:AT',    '150',  '155',  'Europe',   'Europa',   'Western Europe',   'Westeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Belgium',  'BE',   'BEL',  '56',   'ISO 3166-2:BE',    '150',  '155',  'Europe',   'Europa',   'Western Europe',   'Westeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'France',   'FR',   'FRA',  '250',  'ISO 3166-2:FR',    '150',  '155',  'Europe',   'Europa',   'Western Europe',   'Westeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Germany',  'DE',   'DEU',  '276',  'ISO 3166-2:DE',    '150',  '155',  'Europe',   'Europa',   'Western Europe',   'Westeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Liechtenstein',    'LI',   'LIE',  '438',  'ISO 3166-2:LI',    '150',  '155',  'Europe',   'Europa',   'Western Europe',   'Westeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Luxembourg',   'LU',   'LUX',  '442',  'ISO 3166-2:LU',    '150',  '155',  'Europe',   'Europa',   'Western Europe',   'Westeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Monaco',   'MC',   'MCO',  '492',  'ISO 3166-2:MC',    '150',  '155',  'Europe',   'Europa',   'Western Europe',   'Westeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Netherlands',  'NL',   'NLD',  '528',  'ISO 3166-2:NL',    '150',  '155',  'Europe',   'Europa',   'Western Europe',   'Westeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Switzerland',  'CH',   'CHE',  '756',  'ISO 3166-2:CH',    '150',  '155',  'Europe',   'Europa',   'Western Europe',   'Westeuropa');
INSERT INTO  COUNTRY_CODES VALUES (  'Antarctica',   'AQ',   'ATA',  '10',   'ISO 3166-2:AQ',    '', '', '', '', '', '');
INSERT INTO  COUNTRY_CODES VALUES (  'Bouvet Island',    'BV',   'BVT',  '74',   'ISO 3166-2:BV',    '', '', '', '', '', '');
INSERT INTO  COUNTRY_CODES VALUES (  'British Indian Ocean Territory',   'IO',   'IOT',  '86',   'ISO 3166-2:IO',    '', '', '', '', '', '');
INSERT INTO  COUNTRY_CODES VALUES (  'Christmas Island', 'CX',   'CXR',  '162',  'ISO 3166-2:CX',    '', '', '', '', '', '');
INSERT INTO  COUNTRY_CODES VALUES (  'Cocos (Keeling); Islands', 'CC',   'CCK',  '166',  'ISO 3166-2:CC',    '', '', '', '', '', '');
INSERT INTO  COUNTRY_CODES VALUES (  'French Southern Territories',  'TF',   'ATF',  '260',  'ISO 3166-2:TF',    '', '', '', '', '', '');
INSERT INTO  COUNTRY_CODES VALUES (  'Heard Island and McDonald Islands',    'HM',   'HMD',  '334',  'ISO 3166-2:HM',    '', '', '', '', '', '');
INSERT INTO  COUNTRY_CODES VALUES (  'South Georgia and the South Sandwich Islands', 'GS',   'SGS',  '239',  'ISO 3166-2:GS',    '', '', '', '', '', '');
INSERT INTO  COUNTRY_CODES VALUES (  'United States Minor Outlying Islands', 'UM',   'UMI',  '581',  'ISO 3166-2:UM',    '', '', '', '', '', '');
