DELETE FROM
    _CEL_PR_EBAN_ACTIVITIES
WHERE
    "EVENTTIME" IS NULL;

DELETE FROM
    _CEL_PR_EBAN_ACTIVITIES
WHERE
    "ACTIVITY_EN" IS NULL AND
    "ACTIVITY_DE" IS NULL;

DELETE FROM
    _CEL_PR_EBAN_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
------------------------
DELETE FROM
    _CEL_PR_EKPO_ACTIVITIES
WHERE
    "EVENTTIME" IS NULL;

DELETE FROM
    _CEL_PR_EKPO_ACTIVITIES
WHERE
    "ACTIVITY_EN" IS NULL AND
    "ACTIVITY_DE" IS NULL;

DELETE FROM
    _CEL_PR_EKPO_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
------------------------
DELETE FROM
    _CEL_PR_CDHDR_ACTIVITIES
WHERE
    "EVENTTIME" IS NULL;

DELETE FROM
    _CEL_PR_CDHDR_ACTIVITIES
WHERE
    "ACTIVITY_EN" IS NULL AND
    "ACTIVITY_DE" IS NULL;

DELETE FROM
    _CEL_PR_CDHDR_ACTIVITIES
WHERE
    YEAR(EVENTTIME) > 5000 
;
-----------------
DROP TABLE IF EXISTS TMP_PR_EBAN_EKKO_EKPO;
DROP TABLE IF EXISTS TMP_PR_EKKO_EKPO;
DROP TABLE IF EXISTS PR_TCURF_TMP;
DROP TABLE IF EXISTS PR_TCURR_TMP;
DROP TABLE IF EXISTS EBAN_CURR_TMP; 
----------------
SELECT ANALYZE_STATISTICS('_CEL_PR_EBAN_ACTIVITIES'); 
SELECT ANALYZE_STATISTICS('_CEL_PR_EKPO_ACTIVITIES');
SELECT ANALYZE_STATISTICS('_CEL_PR_CDHDR_ACTIVITIES');
