

CREATE OR REPLACE VIEW "BSEG_UNION_DELTA" AS (
SELECT * FROM <$BSIK>

UNION ALL

SELECT  * FROM <$BSAK>
);



DROP TABLE IF EXISTS "BSEG_DELTA";

CREATE TABLE "BSEG_DELTA" AS(
SELECT
    BSEG.*
    ,ROW_NUMBER() 
        OVER(PARTITION BY "BSEG"."MANDT", "BSEG"."BUKRS", "BSEG"."BELNR", "BSEG"."GJAHR", "BSEG"."BUZEI" 
            ORDER BY "BSEG"."AUGBL","BSEG"."MANDT", "BSEG"."BUKRS", "BSEG"."BELNR", "BSEG"."GJAHR", "BSEG"."BUZEI") AS NUM
    
FROM 
    "BSEG_UNION_DELTA" AS BSEG
);

DELETE FROM "BSEG_DELTA" WHERE NUM > 1;
ALTER TABLE "BSEG_DELTA" DROP COLUMN NUM CASCADE;

DROP VIEW IF EXISTS "BSEG_UNION_DELTA";

SELECT ANALYZE_STATISTICS ('BSEG_DELTA');
