
DELETE FROM P2P_RSEG_STAGING
WHERE EXISTS (SELECT 1 FROM <$RSEG> as NEW_DATA 
              WHERE P2P_RSEG_STAGING.MANDT = NEW_DATA.MANDT 
              AND P2P_RSEG_STAGING.BELNR = NEW_DATA.BELNR
              AND P2P_RSEG_STAGING.GJAHR = NEW_DATA.GJAHR
              AND P2P_RSEG_STAGING.BUZEI = NEW_DATA.BUZEI
              );
INSERT INTO P2P_RSEG_STAGING
SELECT 
	RSEG.MANDT,
    RSEG.BELNR,
    RSEG.GJAHR,
    RSEG.BUZEI,
    RSEG.EBELN,
    RSEG.EBELP,
    CAST(RSEG.RETDUEDT AS DATE) AS TS_RETDUEDT
FROM 
    <$RSEG> AS RSEG
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKPO_STAGING AS C 
    WHERE 1=1 
        AND RSEG.MANDT = C.MANDT
        AND RSEG.EBELN = C.EBELN
        AND RSEG.EBELP = C.EBELP)
;

SELECT ANALYZE_STATISTICS ('P2P_RSEG_STAGING'); 

