
DELETE FROM P2P_EKBE_STAGING
WHERE EXISTS (SELECT 1 FROM <$EKBE> as NEW_DATA 
              WHERE P2P_EKBE_STAGING.MANDT=NEW_DATA.MANDT 
              AND P2P_EKBE_STAGING.EBELN=NEW_DATA.EBELN
              AND P2P_EKBE_STAGING.EBELP=NEW_DATA.EBELP
              AND P2P_EKBE_STAGING.ZEKKN=NEW_DATA.ZEKKN
              AND P2P_EKBE_STAGING.VGABE=NEW_DATA.VGABE
              AND P2P_EKBE_STAGING.GJAHR=NEW_DATA.GJAHR
              AND P2P_EKBE_STAGING.BELNR=NEW_DATA.BELNR
              AND P2P_EKBE_STAGING.BUZEI=NEW_DATA.BUZEI
              );

INSERT INTO P2P_EKBE_STAGING 
SELECT 
    EKBE.MANDT,
    EKBE.EBELN,
    EKBE.EBELP,
    EKBE.ZEKKN,
    EKBE.VGABE,
    EKBE.GJAHR,
    EKBE.BELNR,
    EKBE.BUZEI,
    CAST(EKBE.BLDAT AS DATE) AS TS_BLDAT,
    CAST(EKBE.BUDAT AS DATE) AS TS_BUDAT,
    CAST(EKBE.CPUDT AS DATE) AS TS_CPUDT,
    CAST(EKBE.CPUTM AS DATETIME) AS TS_CPUTM
FROM 
    <$EKBE> AS EKBE
WHERE EXISTS(
    SELECT * 
    FROM P2P_EKPO_STAGING AS C
    WHERE 1=1
        AND EKBE.MANDT = C.MANDT
        AND EKBE.EBELN = C.EBELN
        AND EKBE.EBELP = C.EBELP)
;

SELECT ANALYZE_STATISTICS ('P2P_EKBE_STAGING'); 

