INSERT INTO _CEL_P2P_CDHDR_ACTIVITIES_DELTA (
    _CASE_KEY
    ,MANDT
    ,EBELN
    ,EBELP
    ,ACTIVITY_DE
    ,ACTIVITY_EN
    ,EVENTTIME
    ,_SORTING
    ,USER_NAME
    ,USER_TYPE
    ,CHANGED_TABLE
    ,CHANGED_FIELD
    ,CHANGED_FROM
    ,CHANGED_TO
    ,CHANGE_NUMBER
    ,TRANSACTION_CODE
    ,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY)
SELECT DISTINCT
    E._CASE_KEY AS _CASE_KEY
    ,E.MANDT AS MANDT
    ,E.EBELN AS EBELN
    ,E.EBELP AS EBELP
    ,CASE WHEN CHANGES.VALUE_OLD IS NOT NULL THEN 'Ändere gewünschtes Lieferdatum'
           ELSE 'Erfasse gewünschtes Lieferdatum'
    END AS ACTIVITY_DE
    ,CASE WHEN CHANGES.VALUE_OLD IS NOT NULL THEN 'Change requested delivery date'
           ELSE 'Set requested delivery date' 
    END AS ACTIVITY_EN
    ,CHANGES.EVENTTIME AS EVENTTIME
    ,CASE WHEN CHANGES.VALUE_OLD IS NOT NULL THEN 1520
            ELSE 1510
	END AS _SORTING
    ,CHANGES.USERNAME AS USER_NAME
    ,USR02.USTYP AS USER_TYPE
    ,CHANGES.TABNAME AS CHANGED_TABLE
    ,CHANGES.FNAME AS CHANGED_FIELD
    ,CHANGES.VALUE_OLD AS CHANGED_FROM
    ,CHANGES.VALUE_NEW AS CHANGED_TO
    ,CHANGES.CHANGENR AS CHANGE_NUMBER
    ,CHANGES.TCODE AS TRANSACTION_CODE
    ,NOW() AS _CELONIS_CHANGE_DATE
    ,CHANGES.MANDANT || CHANGES.OBJECTCLAS || CHANGES.OBJECTID || CHANGES.CHANGENR AS _ACTIVITY_KEY
FROM
    TMP_P2P_CDHDR_CDPOS AS CHANGES
    JOIN EKET AS EKET on 1=1
        AND CHANGES.TABKEY = EKET.MANDT || EKET.EBELN || EKET.EBELP || EKET.ETENR
        AND CHANGES.TABNAME = 'EKET'
        AND CHANGES.FNAME  = 'EINDT'
    JOIN P2P_EKPO_STAGING AS E ON 1=1
        AND EKET.MANDT = E.MANDT
        AND EKET.EBELN = E.EBELN
        AND EKET.EBELP = E.EBELP
    LEFT JOIN USR02 AS USR02 ON 1=1
        AND USR02.MANDT = CHANGES.MANDANT
        AND USR02.BNAME = CHANGES.USERNAME
;


