INSERT INTO _CEL_P2P_QAVE_ACTIVITIES_DELTA(
	_CASE_KEY
	,MANDT
	,EBELN
	,EBELP
	,ACTIVITY_DE
	,ACTIVITY_EN
	,EVENTTIME
	,_SORTING
	,USER_NAME
	,USER_TYPE
	,_CELONIS_CHANGE_DATE
    ,_ACTIVITY_KEY) 
SELECT  
	E._CASE_KEY AS _CASE_KEY
	,E.MANDT AS MANDT
	,E.EBELN AS EBELN
	,E.EBELP AS EBELP
	,CASE WHEN Q.VBEWERTUNG = 'A' THEN 'Qualität: Akzeptiert' WHEN Q.VBEWERTUNG = 'R' THEN 'Qualität: Abgelehnt' ELSE 'Qualität: Nicht bewertet' END AS ACTIVITY_DE
    ,CASE WHEN Q.VBEWERTUNG = 'A' THEN 'Quality: Accepted' WHEN Q.VBEWERTUNG = 'R' THEN 'Quality: Rejected' ELSE 'Quality: Not evaluated'END AS ACTIVITY_EN
	,CAST(Q.VDATUM AS DATE) + CAST(Q.VEZEITERF AS TIME) AS EVENTTIME
	,2200 AS _SORTING
	,Q.VNAME AS USER_NAME
	,USR02.USTYP AS USER_TYPE
	,NOW() AS _CELONIS_CHANGE_DATE
    ,Q.MANDANT || Q.PRUEFLOS || Q.KZART || ISNULL ( '' , Q.ZAEHLER  ) AS _ACTIVITY_KEY
FROM
	P2P_EKPO_STAGING AS E
	JOIN QALS as QALS on 1=1
		AND QALS.EBELN = E.EBELN
		AND QALS.EBELP = E.EBELP
		AND QALS.MANDANT = E.MANDT
	JOIN <$QAVE> as Q on 1=1 
		AND Q.MANDANT = QALS.MANDANT
		AND Q.PRUEFLOS	= QALS.PRUEFLOS
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND Q.MANDANT = USR02.MANDT
		AND Q.VNAME = USR02.BNAME
;


--Cleanup

DELETE FROM
    _CEL_P2P_QAVE_ACTIVITIES_DELTA
WHERE
    EVENTTIME IS NULL;

DELETE FROM
    _CEL_P2P_QAVE_ACTIVITIES_DELTA
WHERE
    ACTIVITY_EN IS NULL AND
    ACTIVITY_DE IS NULL;

DELETE FROM
    _CEL_P2P_QAVE_ACTIVITIES_DELTA
WHERE
    YEAR(EVENTTIME) > 5000 
;

-- Statistics
SELECT ANALYZE_STATISTICS('_CEL_P2P_QAVE_ACTIVITIES_DELTA');


-- Merge
INSERT INTO _CEL_P2P_QAVE_ACTIVITIES_DELTA
SELECT *
FROM _CEL_P2P_QAVE_ACTIVITIES_DELTA AS NEW_ACTIVITIES
 WHERE NOT EXISTS (
                    SELECT 1 FROM _CEL_P2P_QAVE_ACTIVITIES_DELTA AS OLD_ACTIVITIES
                    WHERE NEW_ACTIVITIES._CASE_KEY=OLD_ACTIVITIES._CASE_KEY
                      AND NEW_ACTIVITIES.ACTIVITY_EN=OLD_ACTIVITIES.ACTIVITY_EN
                        AND NEW_ACTIVITIES._ACTIVITY_KEY=OLD_ACTIVITIES._ACTIVITY_KEY 
                    );

