
DROP TABLE IF EXISTS TMP_P2P_CDHDR_CDPOS;

DROP TABLE IF EXISTS TMP_P2P_EKKO_EKPO;

DROP TABLE IF EXISTS P2P_TCURF_TMP;
DROP TABLE IF EXISTS P2P_TCURR_TMP;
DROP TABLE IF EXISTS EKPO_CURR_TMP; 

DROP TABLE IF EXISTS BKPF_DELTA;
DROP TABLE IF EXISTS BSEG_DELTA;

