Weighted Days early
PQL: AVG(
CASE WHEN
DAYS_BETWEEN ( "BSEG"."AUGDT", ADD_DAYS("BSEG"."ZFBDT", ROUND ("BSEG"."ZBD3T")) ) > 0
THEN
DAYS_BETWEEN ( "BSEG"."AUGDT", ADD_DAYS("BSEG"."ZFBDT", ROUND ("BSEG"."ZBD3T")) )
* "BSEG"."WRBTR_CONVERTED" / PU_SUM(DOMAIN_TABLE ( "BSEG"."WRBTR_CONVERTED"), ("BSEG"."WRBTR_CONVERTED"))
ELSE NULL
END)
