1. Rework Rate : 

Formula: AVG( CASE WHEN PU_COUNT("VBAP","_CEL_O2C_ACTIVITIES". 
33. VARIABLE_ACTIVITY_COLUMN ,"_CEL_O2C_ACTIVITIES".33. VARIABLE_ACTIVITY_COLUMN 
IN (33. VARIABLE_UNDESIRED_ACTIVITIES) ) > 0 THEN 1.0 ELSE 0.0 END )*100

2. Rejection Rate :

Formula: AVG(CASE WHEN PU_COUNT("VBAP","_CEL_O2C_ACTIVITIES".
33. VARIABLE_ACTIVITY_COLUMN ,"_CEL_O2C_ACTIVITIES".
33. VARIABLE_ACTIVITY_COLUMN = 33. VARIABLE_REJECTION_ACTIVITIES ) >0
THEN 1.0 ELSE 0.0 END)*100


3. On-Time Delivery Rate :

Formula: AVG(
  CASE 
    WHEN PU_COUNT("VBAP", "_CEL_O2C_ACTIVITIES"."33. VARIABLE_ACTIVITY_COLUMN", "_CEL_O2C_ACTIVITIES"."33. VARIABLE_ACTIVITY_COLUMN" = 33. VARIABLE_ON_TIME_DELIVERY_ACTIVITY) > 0 
    THEN 1.0   ELSE 0.0 
  END
)*100


4. Touchless Order Rate :

Formula: AVG(CASE 
WHEN PU_COUNT("VBAK","_CEL_O2C_ACTIVITIES"."USER_TYPE","_CEL_O2C_ACTIVITIES"."US
NOT IN ( 33. VARIABLE_AUTO_TYPES ) ) = 0 THEN 1.0 ELSE 0.0 END)*100


5. Unbilled Revenue Rate :

Formula: AVG(CALC_THROUGHPUT(CASE_START TO 
CASE_END, REMAP_TIMESTAMPS("_CEL_O2C_ACTIVITIES"."EVENTTIME", HOURS))/24)



